### ISSUE TITLE
Tracks And Groups (Import / Save)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#1053]
# Review 
- [ ]  Crash while importing in the background
- [x]  Imported by file, tracks should be saved into "Import"

# ToDo 
Support for folders in "Tracks"
- [x] Import (osf): Support importing tracks into folders 
- [x] Check UI (Tracks) is displayed as designed in Figma (folder support)
Saving other tracks to folders:
- [x] Imported by file, tracks should be saved into **"Import"**
- [x] Recorder tracks should be saved into **"Rec"** folder
- [x] All other tracks should be saved into "Tracks" folder.
