### ISSUE TITLE
Track dialogs: add folders support

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1055]
# Review 
### Save as new track
- [x]  Landscape: horizontal folder scroll is cropped on the side 
- [x] If the user opens "Select folder" > Add folder > adds new folder, "Select folder" screen should be closed and get the user back to the previous screen with the new group as selected 

### Save as new track > [Select folder block ](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=229%3A33)
- [x] Horizontal folder button: corner radius 9pt / px?
- [x] Select folder text color = 000000
- [x] Horizontal folder buttons: left and bottom padding increase to 16pt
- [x] Scroll to selected folder (it should be visible on the sceen if it was selected on the "Select folder" screen).
- [x] "Add folder" use ic_custom_add icon.

### Open existing track / [Add to a track](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=102%3A6877)
All comments about a horizontal scroll bar with folder buttons.
- [x]  Paddings from the left, right, bottom, should be 16 pt
- [x] Max. width of one item should be 120pt.
- [x] Landscape: folders cropped by safe area.
- [x] Button corner radius 9pt

# ToDo 
Add support for folder selection or switching in the Plan route. 

### Plan route -> Save as new track : 
- [x] Add button "Select folder" to access a list of available folders.
- [x] Horizontal scroll with folders: add lasts item "Add new folder"
- [x] Add UI ["Select folder"](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=229%3A1500) for select folder from the list.
- [x] Add UI,[ "Add new folder" ](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=229%3A1500) for adding new folder.

###  Route Details
- [x] Route Details -   Export > OsmAnd: use the "Save as track" dialog from the Plan a Route. (Currently, show alert with a text field)

### Open existing track / Add to a track
- [x] Add buttons to switch between groups. Switching should sort the list"[Open existing track](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=102%3A5512)", "[Add to a track](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=102%3A6877)"

### UI
![Снимок экрана 2021-01-28 в 13 19 40](https://user-images.githubusercontent.com/9365308/106131539-7c50d800-616b-11eb-8369-ede33ccbd805.png)

### Save as track
![image](https://user-images.githubusercontent.com/1042025/106897012-a4ec4b00-66f2-11eb-81dc-2d86379396f9.png)

#### Plan route > Save as track. [Figma](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=229%3A33)
![Снимок экрана 2021-01-28 в 13 43 01](https://user-images.githubusercontent.com/9365308/106134125-c8514c00-616e-11eb-9f56-712fb8241d1d.png)
