### ISSUE TITLE
Imported Parking point from Android

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1309]
# Review 3

- [ ]  iOS doesn't recognize imported Parking point as time-limited.  File created on Android imported to iOS [favourites.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7556160/favourites.gpx.zip)
- [ ]  Parked time is different on iOS. GPX File `<osmand:creation_date>2021-11-17T16:01:53Z</osmand:creation_date>`

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/142237049-ace10c42-31cf-4258-9e94-f9f768f05600.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/142236859-156f376f-7d1d-49d8-a078-fa2337139ab4.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

# Review 2
Android show parked time, iOS set it to 1969
```
  </metadata>
  <wpt lat="50.4357719" lon="30.5088577">
    <time>1969-12-31T23:59:59Z</time>
    <name>parking</name>
    <type>personal</type>
    <extensions>
      <osmand:address>Саксаганського вулиця 53/80, Київ</osmand:address>
      <osmand:icon>parking</osmand:icon>
      <osmand:color>#244dbd</osmand:color>
    </extensions>
  </wpt>
```
- [x]  Fix parked time for parking point. Export from iOS [Export_08-10-21.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7311512/Export_08-10-21.zip)
  - [x]  (Android) Add exporting Creation time field to osf.
  - [x]  (IOS) Add Creation time fields.
  - [x]  (IOS) Save Creation time on parking create.
  - [x]  (IOS) Read creation time from osf.
  - [x]  (IOS) Show creation time on UI.
  - [x]  (IOS) Add export creation time to osf.
  - [x]  (IOS) Test import by osf exported from Android.
  - [x]  (Android) Test import by osf exported from IOS.

&nbsp; 
# Review
- [x]  Big overdue time
![Снимок экрана 2021-07-08 в 13 53 27](https://user-images.githubusercontent.com/9365308/124910106-e1023f80-dff3-11eb-8e1a-dbe367d31a72.png)
exported from Android file https://t.me/c/1265587788/1411

# ToDo
Try to import file, tap on parking point, the app will crash, works only first time.
[Export_25-06-2
1.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/6715440/Export_25-06-21.osf.zip)

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-iOS/pull/1314
