### ISSUE TITLE
Context menu details order and missing items

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1482]
# Review
- [x]  Brand is still missing
https://www.openstreetmap.org/node/34044677#map=19/52.28876/4.87017
- [x] Brand replacing existing name in context menu ? (The Admiralty -> Fuller's (Trafalgar Square) )
# ToDo

The context menu for POI doesn't show some items that the Android version has.
- [x] Add missing items: "wheelchair accessibility", check all other items similarity  to android
- [x] Add icons for: Instagram, Facebook, Operator
- [x] The same items order

## Examples:
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/132306400-d26bce4f-f52e-41a7-a55e-748318c7246e.PNG"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/132306421-fbcfebcc-3972-4a93-8d47-d7437feec3a7.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/132307063-0dd51a9e-f16e-4c6e-9238-5f71402f4e28.PNG"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/132307079-523559c2-4347-441e-9e36-47acb8d1a1c4.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix Context Menu - POI details order](https://github.com/osmandapp/OsmAnd-iOS/pull/1916)

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/322
