### ISSUE TITLE
Crash in Configure Map – Terrain

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1485]
# Review 3
- [x]  "Available maps" is missed at all.

# Review 2
Testflight 4.1.0.9
- [x]  Still crash, I have send it to console.

# Review
- [x]  Still crash, I have send it to console.
# ToDo
Crash when trying to download slope map in Configure Map – Terrain.
