### ISSUE TITLE
"Voice Guidance" UI:  make consistent with Android

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1490]
# Review
- [x] Fix divider below Speed limit 
<img src="https://user-images.githubusercontent.com/9365308/221830321-4c61f6fc-7c68-4d05-b2ef-f9848bf14c4e.png"  width="411" height="auto"/> 

- - - - 
- [x] Repeat after in Repeat navigation instructions menu doesn't save a value
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/220074613-dee455cc-11bd-4546-82f4-e75b16ffb37b.mov"  width="300" height="auto"/>  </td>
  </tr>
</table>   

# ToDo
We need to rearange list of options and add missed from if compare to Android.

- [x]  Change **Voice guidance** to **Voice prompts** 
- - [x]  Use `ic_custom_sound_off` if **Voice prompts**  is disabled

&nbsp;
### Announce
- [x]  Street name (TTS)
- [x] Exit number
**padding**
- [x] Traffic warnings
- [x] Pedestrian crosswalk
- [x] Speed cameras (with alert)
- [x] Tunnels

&nbsp;
### User points
- [x]  Add new group **User points**, it should contain:
- - [x]  **Track waypoints**
- - [x]  **Nearby favorites**
- - [x] **Nearby POI**
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/174329676-c09a883e-5b19-4876-be03-88a69e72ec4c.png"  width="300" height="auto"/></td>
  </tr>
</table>  
 
&nbsp;
### Speed limit
- [x]  Add new group **Speed limit**, it should contain:
- - [x]  **Speed limit** rename to **Announce when exceeded** 
- - [x]  Show **Speed limit tolerance** if **Announce when exceeded** is enabled
<table style="width:100%">
  <tr>
    <th>Disabled</th>
    <th>Enabled</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/174329089-a880bff4-a874-46c2-bd05-c756f4e613af.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/174329092-32d33545-7f3a-45d6-9808-fa02f31b634c.png"  width="300" height="auto"/> </td>
  </tr>
</table>  

&nbsp;
### Other
- [x]  **Announce GPS signal loss and recovery**
- [x] **Announce route recalculation**

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214594307-6ae4f151-0e06-4487-8442-c6d93e0b438a.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

&nbsp;
### Options
- [x]  Add new group **Options**, it should contain:
- - [x] **Repeat navigation instructions**
- - [x]  **Arrival announcement** rename to **Announcement time**

&nbsp;
### Arrival announcement, [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=601%3A40454&t=t9qrM0r1aEIQSuoI-1)
Changed for screen
- [x] Add image [img_help_announcement_time_day@3x.png.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8940858/img_help_announcement_time_day%403x.png.zip)
- [x] Add **Time and distance intervals**, it should depends on selected  **Announcement time**
- [x] **Time and distance intervals** should be closed by default

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214594670-979f523a-f54f-44cc-9d1b-c393ee5321c3.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/214594675-08715b48-bf6d-474a-bbb1-a992a1837801.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Redesign voice prompts screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2521)

**Comment by Zirochkabila** [comment]
19.02.23 master

- [ ] Pedestrian crosswalk displayed like crossing
<details><summary>Crossing</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220074177-366ea39d-e85b-4c62-a5e0-faea315e7518.png">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220074183-b338e345-bb67-4422-b1e4-844da18edbf3.png"">
</details> 

- [ ] Repeat after in Repeat navigation instructions menu doesn't save a value

https://user-images.githubusercontent.com/104760013/220074613-dee455cc-11bd-4546-82f4-e75b16ffb37b.mov

**Comment by Skalii** [comment]
[Fix Voice prompts screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2625)

**Comment by Zirochkabila** [comment]
Comments fixed, except for https://github.com/osmandapp/OsmAnd-iOS/issues/1490#issuecomment-1436673091
Most likely, it was a duplicate translation line - will be fixed in this issue https://github.com/osmandapp/OsmAnd-Issues/issues/1015
