### ISSUE TITLE
Speed cameras POI: show legal warning

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1491]
# Review 2
- [x]  Cancel button doesn't visible if app language is Ukrainian
- [x] Dialog title should be shown whole in two or three lines if needed.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220095819-2cb90d76-9ed6-43c7-abd3-5d2c47230618.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

# Review
- [x]  Description is mixed up
- - [x] Select **Keep active** and you will receive alerts and warnings about speed cameras.
- - [x] Select **Uninstall**. All data related to speed cameras: alerts, notifications, POIs will be deleted until OsmAnd is completely reinstalled.
- [x]  Description test style = `body`, bold parts = `headline`
- - - - 
- [x]  iPhone 8 missed padding below button.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216956797-ab1b61d7-ad95-4c18-a2cb-fc50e0b197c8.png"  width="200" height="auto"/> </td>
  </tr>
</table>   

- - - - 
- [x]  Add alert about restart is needed.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/217001122-a338f0de-972d-4188-a736-d998b009244e.png"  width="200" height="auto"/> </td>
  </tr>
</table>   

# ToDo
We need to add ability to **delete** all data and UI elements related to **Speed cameras** from the app.
Android task https://github.com/osmandapp/OsmAnd/issues/7614

## OsmAnd settings, [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=1207%3A52596&t=h6VNS3IGCNLyEq9g-1)
- [x]  Add group **Legal** with one action **Uninstall speed cameras**.
- - [x] Click → should open **Speed camera POI’s** dialog
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/203514665-cd3eff9e-e35c-440e-8101-a453f98d80b8.png"  width="375" height="auto"/> </td>
  </tr>
</table>   

## Navigation
- [x]  On first launch after installation, show **Speed camera POI’s** dialog.

## Voice prompts, [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=1157%3A50646&t=h6VNS3IGCNLyEq9g-1)
- [x]  Add alert
- - [x] Description `Speed cameras alerts in some countries is prohibited by the law.`
- - [x] Icon `ic_custom_alert_color`
- - [x]  **Read more** button, click should open **Speed camera POI’s** dialog

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/174609156-0870917c-d842-4623-8125-d3e6807fd13a.png"  width="375" height="auto"/> </td>
  </tr>
</table>  

## Speed camera POI’s dialog, [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=1207%3A56796&t=h6VNS3IGCNLyEq9g-1)
How the app should respond.
- [x]  Title **Speed camera POI’s**. https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1235  
- [x] Description: https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1231-L1234

###  Actions:
- [x] **Uninstall**: 
- - [x] Should delete all data related to **Speed cameras** from the app. Speed cameras should not be visible on the map or search.
- - [x] Hide **Uninstall speed cameras** item from the **OsmAnd settings**
- - [x] Hide **Speed cameras** item from the **Voice prompts**
- [x] **Keep active**: Close the dialog, all data stay untouched, but alert in Voice prompts and **Uninstall speed cameras** item should be visible in Menu's

<table style="width:100%">
  <tr>
    <th>OsmAnd Settings</th>
    <th>Speed camera POI’s</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/173804220-8cf3b25c-0094-467f-b754-6ef46f61c1b2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173804202-624d5c0a-b800-4dca-980d-ea0a0261c014.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Speed cameras - Uninstall](https://github.com/osmandapp/OsmAnd-iOS/pull/2506)

**Comment by Zirochkabila** [comment]
05.02.2023 iOS Master branch - **Done**

**Comment by Skalii** [comment]
[Fix uninstall speed cameras](https://github.com/osmandapp/OsmAnd-iOS/pull/2573)

**Comment by Skalii** [comment]
[Fix base navbar VC](https://github.com/osmandapp/OsmAnd-iOS/pull/2614)

**Comment by Zirochkabila** [comment]
03.03 master
There is no " Cancel " button

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222704264-24fa38c9-c1d0-43a9-87b8-456e8a9444a7.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
- [ ]  **Cancel** > **Close**
- [ ] Fix layout on iPad
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223952006-f39a85bd-f915-4470-a243-2762bb32ec4c.jpg"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223952034-2dc6862b-1c64-463d-ac2f-0aecbd2fde3d.jpg"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/navigation/guidance/voice-navigation#speed-cameras
- https://osmand.net/docs/user/navigation/guidance/navigation-settings#screen-alerts
- https://osmand.net/docs/user/personal/global-settings#legal
- https://osmand.net/docs/user/widgets/nav-widgets#alert-widget
