### ISSUE TITLE
POI labels

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1493]
# Review
- [x]  Night style for text always used, it should be used only if map mode = night.
- [x] POI labels work strange, after disabling it is still visible until the app restart.
[IMG_2461.MP4.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8584280/IMG_2461.MP4.zip)

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/165787267-39912daa-b8db-4316-89d2-e72641464c24.jpg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/165787361-4882371e-530b-4b06-8d6b-a6183c6e6c4a.jpg"  width="300" height="auto"/></th>
  </tr>
</table> 

# ToDo
- [x]  Should be visible only from 11 zoom level for all point types
- [x] Add night style for text

**Comment by Skalii** [comment]
[Fix poi labels - show at zoom level 11](https://github.com/osmandapp/OsmAnd-iOS/pull/1888)
