### ISSUE TITLE
My Places > Tracks, add "Edit" action to delete and export several tracks at a time

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1734]
Adding "Selection mode" that will allow applying actions to multiply items at once.

# ToDo

**NavBar**
- [x]  Add "Action" icon to the NavBar right side.
- [x] Taping "Actions" will launch "Selection mode"

## Selection mode:
• Modify NavBar with new actions
• Show ToolBar instead of TabBar, with 3 actions (4 in the future, for Upload to OSM)

&nbsp; 
### NavBar
<img src="https://user-images.githubusercontent.com/9365308/151183060-7e7629cf-163c-42c9-99df-c56809b9a0d1.png"  width="auto" height="auto"/> 

Show two actions:
- [x] **Select all:** selects all items in the list
- [x] **Done:**
- [x] NavBar Title
• Before selection "Select tracks"
• If more then 1 items selected "Tracks: [Quantity]".

&nbsp; 
### Track list
- [x]  Hide right-side action. Lock transition to next screen

&nbsp; 
### ToolBar
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/151183589-af66f23b-a4f6-4800-abc2-dc636c64f90f.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151183593-f5a3820c-83be-436f-9d0c-5ae03bdccbeb.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

- [x] Show toolbar with 3 actions
 
Toolbar actions:
- [x] **Export:** launch export UI with preselected tracks
- [x] **Show on map:** show selected tracks on the map, after taping on the action, selection mode should be closed
- [x] **Delete:** show confirmation dialog:
• **Cancel** > Close bottom sheet
• **Delete** close confirmation dialog and selection mode.

# UI, [Figma](https://www.figma.com/file/0tOguKltp8m6UuLp7biZh5/My-places?node-id=1016%3A26493)
<table style="width:100%">
  <tr>
    <th>Selection mode</th>
    <th>Selected item</th>
    <th>Delete tracks</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/151182765-a9347cdf-f598-41f2-ae38-f0d7ca494020.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151179073-a44bbaec-22c7-4208-9485-134f75a83f18.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151179058-e7db36b9-47de-477b-9763-5d5dd579c559.png"  width="300" height="auto"/> </th>
  </tr>
</table>
