### ISSUE TITLE
Add support for "Dynamic type"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1932]
# ToDo
System "Text size" parameter doesn't apply to OsmAnd. We need to add support for "[Dynamic type](https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically)". [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/typography/)

- [x] Text on all screens should consider system "Text size".
- [x] Fix UI on all screens
- [x] Check and fix RTL
- [x] #2766

### Drawer
<table style="width:100%">
  <tr>
    <th>Before</th>
    <th>After </th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/167116003-29fc9210-263d-456b-a1cc-902ce437a8b6.PNG"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/167115988-baa47af1-c501-4ef1-bd35-4fb2924f3d55.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

### OsmAnd Settings
<table style="width:100%">
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/167116288-b2fea8cc-37ac-47cd-a6de-da5042759929.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/167116279-e70013a9-3109-4591-98e5-9aa77b22c527.PNG"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Add Dynamic type support](https://github.com/osmandapp/OsmAnd-iOS/pull/2536)

**Comment by Skalii** [comment]
[Fix UI for dynamic type (part 1)](https://github.com/osmandapp/OsmAnd-iOS/pull/2568)

**Comment by Skalii** [comment]
[Fix UI for dynamic type (part 2)](https://github.com/osmandapp/OsmAnd-iOS/pull/2582)

**Comment by PaulStets** [comment]
Also fix https://github.com/osmandapp/OsmAnd-Issues/issues/1947 in this task.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2883

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2889

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2894

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2903

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2911

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2915

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2924

**Comment by dmpr0** [comment]
## Review 
- [ ]  Remove chevron ">". Configure Map > Road style
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/69c59706-66e8-4757-81c6-0fecc179d075"  width="300" height="auto"/> </td
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2928

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2936
