### ISSUE TITLE
Route Details - map is too small

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#1998]
Route Preview / Analyze map is too small

## Review
- [ ]  How it should open?
<img src="https://user-images.githubusercontent.com/9365308/178734815-4f1234b5-08c0-4383-98ef-fd8d4c8329ec.PNG"  width="300" height="auto"/> 

## ToDo
- [x]  Open **Route details** full screen.
- [x] Fix status bar text and icon color, it should be visible.
<img src="https://user-images.githubusercontent.com/9365308/172574959-2fa58c31-546a-4cfc-841e-b492b9553044.jpg"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Fix Route Details screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2021)
