### ISSUE TITLE
Goods delivery UI update

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2016]
Core team added new option **Goods vehicles restrictions**, that allows avoiding roads that are forbidden to use in this case. Android task https://github.com/osmandapp/OsmAnd/issues/13123, we need to apply new UI for new option.

## Review 2
- [x]  Out of Safe area in Landscape
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/206177132-594f1686-2e3d-448c-b59c-5e32e54852fb.PNG"  width="500" height="auto"/> </td>  </tr>
</table>   

- - - - - - 

- [x]  Remove **Goods delivery** for **Navigation** > **Settings**

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/206177458-f5bdd276-f6cc-4472-9971-0e35b47cd732.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Review
- [x]  Use system radio button check mark.
<table style="width:100%">
  <tr>
    <th>System</th>
    <th>Current</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/203329559-14897b89-54f8-45b7-ab92-40ed156715c2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/203329565-456eb305-5dfa-4e74-86da-e479f4dcd514.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

- - - - -
- [x]  Open **Goods delivery** in dialog style window
- [x] All description text, should have size 13pt, 

- - - -
- [x]  Different padding between right screen side and chevron ">".
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/203331036-958889b2-4b8c-49df-92ea-31c7e5ba8d8e.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

## ToDo
- [x]  Rename **Goods vehicles restrictions** to **Goods delivery**
- [x]  Icon: `ic_custom_van`. [Download](https://github.com/osmandapp/OsmAnd-iOS/files/8877961/ic_custom_van.zip)
- - [x] Use profile active color if **Yes** selected
- [x]  Use dialog with Yes/No buttons.

<table style="width:100%">
  <tr>
    <th>List item states.</th>
    <th>No</th>
    <th>Yes</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/173043598-a488786e-8230-4f03-8f9a-648396894ad9.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173043589-f5b8acd5-b31b-4b22-9967-ce4ea9d69f46.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173043594-1e0d450d-254d-4994-977b-8948f6585ea4.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.3.0.39

![photo_2022-12-05 16 31 10](https://user-images.githubusercontent.com/104760013/205662317-8a0f9a1b-da79-4c3e-a147-22b649992894.jpeg)

**Comment by dmpr0** [comment]
Parameter is works https://www.openstreetmap.org/way/49989742#map=17/50.82637/12.89621&layers=T
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/205888301-dc26dea8-d395-428c-8932-4903b72f9b64.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/205888326-64d11d96-66e6-4b37-b464-8e61234c643d.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.1.3
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/207381432-f8780b49-e848-4d4c-bfa4-aa128a9767bb.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2318
