### ISSUE TITLE
Make “Attach to the roads” default behavior for navigating tracks with road-following nav profiles

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2132]
Currently the user has to go into navigation options, then the “follow track” menu and manually select “Attach to the roads” and then pick a navigation profile again (which probably has been selected already before in the main navigation menu). This feels cumbersome and unnecessary. If a road-following nav profile is already selected, it can be assumed the user wants to follow the track approximately by the allowed roads.

My proposal is to make the “attach to the roads” behavior automatically apply if the user wants to navigate a track with a road-following profile.

**Comment by christianCasRo** [comment]
I hope this too

**Comment by christianCasRo** [comment]
PS: I understand that this would be in both version, android and ios, right?🫶

**Comment by dmpr0** [comment]
> Android task https://github.com/osmandapp/OsmAnd/issues/19745

## ToDo

## Navigation settings 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/92ee5f78-08e9-4a62-a672-bf119ba91853"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new option – `Detailed track guidance`
- - [x] icon `ic_action_attach_track`
- - [x] Tap – open Detailed track guidance screen

### Detailed track guidance
<table style="width:100%">
  <tr>
    <th>Always</th>
    <th>Ask every time</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/974712d2-270b-4325-bd2a-299772629cdc"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6cabad8c-dc12-4f7b-85c5-0dd4e2b5102a"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Image – `img_detailed_track_guidance` and `img_detailed_track_guidance_dark`
- [x] Description – `OsmAnd will match your track to nearby roads for enhanced turn-by-turn guidance.`

**Options:**
- [x] **Ask every time** – empty state should be always visible in Navigation if Follow track is active 
- [x] **Always** – Attach to the road should be applied automatically for the selected track while in Navigation.
- - [x] Show **Threshold distance** slider 

### Route preparation

<table style="width:100%">
  <tr>
    <th>Always</th>
    <th>Ask every time</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b94ac474-46a1-4b29-8e22-87f6f56cc7a6"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/143f1412-9860-49e5-a876-7d1e7585e0c8"  width="200" height="auto"/> </td>
  </tr>
</table>   

Attach to the roads empty state visibility should depend on Detailed track guidance option

- [x] Change description – `OsmAnd can match your track to nearby roads for enhanced turn-by-turn guidance.`

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4273

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4318

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4331

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.5.4955` - Function implemented

To be improved:
[As Android too](https://github.com/osmandapp/OsmAnd/issues/21812)

1. The route is not updated immediately after changing the settings in Detailed track guidance - need to exit the navigation and enter again (probably not critical - looks as in Android)
2. The settings in Detailed track guidance that were changed in the Car profile are applied to another profile



<details><summary>2</summary>
<video src="https://github.com/user-attachments/assets/e9ca5a80-2730-4cfc-93fb-44f1773f95cb"></video>
</details>

**Comment by DmitryAlexei** [comment]
To do:
- [ ] when changing profiles, attach to the roads setting from the new profile should be applied (same behavior in Android) - probably a separate task is needed

The progress bar on the old screens works incorrectly: it shows wrong data (not related to that task - most likely refactoring needed).

**Comment by vshcherb** [comment]
Didn't reproduce with Android changing profiles, reinvestigation needed

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4344

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.5.4967`

When switching to a profile that has “Ask every time” set, an empty line is displayed in place of the diagram

[Thu 06 Feb 2025.gpx.zip](https://github.com/user-attachments/files/18693588/Thu.06.Feb.2025.gpx.zip)

<details><summary>Chart</summary>
<video src="https://github.com/user-attachments/assets/9655bc40-68a4-4057-9c7d-a39aa20a2816
"></video>
</details>

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/692ac3c5-41e8-4c5b-a1fa-f6886e7fe30c"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Use Dynamic type / Subhead (15pt) font size for description

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4385

**Comment by Zirochkabila** [comment]
# Testing 3
`4.9.5.4980` - Fixed

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b3014658-f86c-4874-a5e6-a58edc2f6d6a"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/bd1aef12-a425-4659-b26b-2abcb1ea9817"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Remove animation for graph

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/navigation/setup/gpx-navigation#detailed-track-guidance
https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-the-roads
