### ISSUE TITLE
Favorites - local backup

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2142]
## Review 2
- [x]  Two backup files is created for one edit.
- [x] After unpacking, favorite backup file should be visible in the same folder.

<table style="width:100%">
  <tr>
    <th> Two backup files</th>
    <th>After unpacking</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/188884231-8172c03b-64e2-4c8f-8bcc-2ea4b1145f3b.MP4"  width="300" height="auto"/>  </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/188884773-ca9fc443-2d71-4c2f-8258-ec54b569c317.MP4"  width="300" height="auto"/>  </td>
  </tr>
</table>     

## Review
- [x]  Use date instead of a number to store versions. Example: 2022_31_08__13_40__01.gpx.zip . Maximum Total 10 Files and maximum 3 per day.
- [x] Use `.zip` instead of `.gz`

## ToDo
To not lose user data, we need to implement a favorites backup similar to Android.
- [x] Create the new backup file for each file saving
- [x] Limited quantity of backup files (similar to Android version)
- [x] Investigate issue with empty favorite file

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/357
https://github.com/osmandapp/OsmAnd-iOS/pull/2148
