### ISSUE TITLE
CarPlay: show search history and recent route in menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2144]
## Review
- [x]  Use night version of icons for Dark UI mode.
- [x] Icons [CarPlayNightIcons.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10882952/CarPlayNightIcons.zip)
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/222748918-01629774-44a5-47a4-8a16-af02c6b8c724.png"  width="600" height="auto"/> </td>
  </tr>
</table>   

- - - 

- [x]  Previous route icon should be the same size. It's get bigger after tap on it.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/222747072-d85d196c-787f-4541-81d1-ae37d456dd85.PNG"  width="600" height="auto"/> </td>
  </tr>
</table>   

## ToDo
We need to find a place to show search history and recent route in the CarPlay menu.

- [x]  Add new item to **Navigation** grid, **History**. 
- - [x] Tap open screen with search history and last route sorted by last used 
- - [x]  Icon `ic_carplay_history`
- [x]  Replace all icons for main grid from [Archive.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10754715/Archive.zip)

<table style="width:100%">
  <tr>
    <th>Grid</th>
    <th>History</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/219334357-26f9551b-c30f-4b00-873e-4311dca632f3.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/219080309-9f117653-d695-4ddd-ae5c-4cbe2411680f.png"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
To Doc team
Some cars dynamically limit lists to 12 or 24 items.

**Comment by Skalii** [comment]
[CarPlay - add search history screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2618)

**Comment by Zirochkabila** [comment]
03.03 master
location that was last searched and to which the route was calculated is duplicated in the History
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222701798-e3ad3eb2-fd6e-4c0c-92af-f8c4a838ec78.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Skalii** [comment]
[CarPlay - icons for night mode](https://github.com/osmandapp/OsmAnd-iOS/pull/2656)

**Comment by Zirochkabila** [comment]
4.4.6.7
Still present - 
"Оазис миру - Looking up address.." 815m same search result

https://user-images.githubusercontent.com/104760013/225693871-895f78d4-4cf7-482b-8183-446bf9fe0906.mov
