### ISSUE TITLE
Allow to use OAuth for OSM

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2170]
# ToDo
Next part of https://github.com/osmandapp/OsmAnd-Issues/issues/1591. We need to add OAuth authorisation method for OpenStreetMap (OSM): to add/edit OSM POI; add/comment OSM Notes; upload GPX; register as Free Mapper.

- [x]  Add **Sing in with OpenStreetMap** button to **Login to OpenStreetMap.org** view
- - [x]  Try to use new `WebAuthenticationSession` method https://developer.apple.com/documentation/authenticationservices/webauthenticationsession
- - [x] Button  should be visible only for users with supported iOS version, 16.4

[Figma](https://www.figma.com/file/tFOVdxhVgFAPI3D194lusr/OpenStreetMap?node-id=521%3A29436&t=wFeuMAt2FC4Zj0Qi-1)

<table style="width:100%">
  <tr>
    <th>Login to OpenStreetMap.org</th>
    <th>Sing in with OpenStreetMap</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220665236-a1e0533f-5525-4e80-acec-ce0c515b7e33.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220665251-ca9a9e0d-7b77-4516-85a0-8572d253593a.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
https://twitter.com/swiftyalex/status/1627446146472763393

**Comment by Zirochkabila** [comment]
On the latest build of Xcode and iOS 16.4, the new interface is not displayed.
@dmpr0  additional verification is required

**Comment by vshcherb** [comment]
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md 



14.3.1 | 14E300c | /Applications/Xcode_14.3.1.app
-- | -- | --

**Comment by dmpr0** [comment]
# Review
- [ ]  Make all button area clickable, currently only text is clickable.

- - - 

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/01d41b98-68ca-42fd-aa6c-244216b676bb"  width="300" height="auto"/> 

- [ ]  Account TabelCell without user  name
- [ ] Unable to open account screen / unable to logout
