### ISSUE TITLE
The arrows for the bulk downloads do not disappear even if you load all regions

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2218]
## How to reproduce
Tested on Italy:
1. Download all regions
2. The arrows for multiply downloads will be still there (should be replaced by the I icon). If you click on the download maps arrows, the loading process will start again.

<img src="https://user-images.githubusercontent.com/80623554/193867431-3f076661-528b-4f6f-939a-bc301962fdf7.png"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
# ToDo
### Open Country screen
- [ ]  Add info icon for map collection, if all regions are downloaded.

### Download map dialog
- [ ]  Change icon color to green, for downloaded maps.
- [ ] Add info icon to the right side, for downloaded maps.
<table style="width:100%">
  <tr>
    <th>Open Country</th>
    <th>Download map dialog</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214549045-08d7c3a8-dc75-47d7-8e15-8f3c0148561d.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/214549057-c1e41a48-14cc-4d95-8629-3b8a1ee0d674.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
25.02
Done

**Comment by dmpr0** [comment]
## Reviiew

### Open Country screen
 - [ ]  Add info icon for map collection, if all regions are downloaded.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223990407-337eb6e7-5ed3-4aa6-973f-2dbd801b6591.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223990400-2e357603-fd75-4dee-b5bb-2d16f5ca1e57.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223990405-1749e0b0-61f4-4f0a-843e-499b4ed38910.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2705

**Comment by Zirochkabila** [comment]
4.4.6.11
Still present

https://user-images.githubusercontent.com/104760013/227709153-5e454ae4-678e-4945-a67c-86d8a5a239cf.mp4

**Comment by dmpr0** [comment]
## Review
I have download contour lines for Australia in Feet, but after download, both Feet and Meters format is marked as downloaded.

**Comment by Zirochkabila** [comment]
4.4.6.14
Main issue is fixed

- [ ] However, the Select аll button does not work in the downloaded maps


https://user-images.githubusercontent.com/104760013/228804403-7fdd1250-79c9-4e7c-b72d-37251ced76ae.mp4
