### ISSUE TITLE
Downloading maps dialog for Maps & Resources

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2222]
If the country map is split into a regional map and you click Country map to download all regions, is not possible to see the queue of the regions and remove some regions.
This option is realized in Android version. When you click on the memory bar appear an additional menu with the queue of the map downloads. (check the screenshot below). 

<details>
    <summary>Android</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://user-images.githubusercontent.com/80623554/194081609-5e7f5c83-477a-4e73-9037-24847b8b56d7.png"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>

**Comment by dmpr0** [comment]
## ToDo


### Download item

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1c0c981c-b1cf-4057-9ab1-102146849dbe"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>  
   


### Downloading dialog

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ab41108b-c0e2-4703-8551-bfb131ea9aa9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/be44fb10-6d1e-4f8b-8fec-3077f5edfba4"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>

**Comment by dmpr0** [comment]
# Review 
- [ ] Last added files should be added to the bottom 

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/b4df0210-c6d3-45d2-b473-1201c0d483a3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Strange download size on Mac

**Comment by dmpr0** [comment]
# Review 

- [ ] Download tabelcell should show progress for current downloaded map, it changes after adding new map

- - -

- [ ] Can we do something with jumping download size digits?

**Comment by vshcherb** [comment]
1. Solution Constant formatting like ```70.0 of 350.1 MB``` not like now ```70 of 350.1 MB```

**Comment by dmpr0** [comment]
# Review
- [ ] Use monospace numbers for font that we are using


```
let systemFont = UIFont.systemFont(ofSize: 17) // Or any size you prefer

// Create a UIFontDescriptor that enables monospaced numbers
let fontDescriptor = systemFont.fontDescriptor.addingAttributes([
    UIFontDescriptor.AttributeName.featureSettings: [
        [
            UIFontDescriptor.FeatureKey.featureIdentifier: kNumberSpacingType,
            UIFontDescriptor.FeatureKey.typeIdentifier: kMonospacedNumbersSelector
        ]
    ]
])

// Create a UIFont with the descriptor
let monospacedFont = UIFont(descriptor: fontDescriptor, size: 17)

// Assign this monospaced font to your label
label.font = monospacedFont
```

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e6097837-233a-421a-8dce-a1bc77814132"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Use the same method in all places where map download counter is shown
