### ISSUE TITLE
Add the ability to resize text for distance measurement 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2293]
# ToDo
We need to improve Distance by tap tool, by adding ability to change text size for distance value showed on the line. 

## Configure Screen

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8bae5ca5-63a4-44f7-bbf4-2475fb0d161b"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4d16eec4-7d1a-46ac-a37e-eacd9c292be7"  width="150" height="auto"/> </td>
  </tr>
</table>   
Currently we have only switch to turn On or Off option on the map.

- [x] Replace switch with chevron
- [x] Show tool state next to it: On or Off

## Distance by tap, view. [Figma](https://www.figma.com/design/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?node-id=1207-58151&m=dev)
<table style="width:100%">
  <tr>
    <th>Off</th>
    <th>On</th>
    <th>Menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/65f5f4c5-0062-4d98-8583-e79461b893e1"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1f0e3422-88da-45d7-a22b-9af0862e8a30"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a59a30c2-fcb1-4662-942c-50b9ef0ece03"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Display the `img_distance_by_tap` image.
- [x] Add description: "Tap on the map to view the distance between your **Current Location** and the tapped point. Tap with two fingers on the map to view the distance between the two tapped points."
- [x] Implement a switch to enable or disable the entire **Distance by Tap** functionality.

**Appearance**
- [x] Add a new settings group: **Appearance**.
- [x] Add a parameter: **Text Size**.
  - [x] Set the default value to **Normal**.
  - [x] Add an option: **Large**, text should be 1,5 size bigger

**Comment by dmpr0** [comment]
## UI Review 

Additional to @Zirochkabila findings.


<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c2b92ead-7ed9-4567-a6b3-68e2e9f6b85d"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Align Text size TabellCell Height

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/20b2907c-42fc-4cb1-be2a-deffce92056e"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Add padding between line and text when Text is bigger

**Comment by Zirochkabila** [comment]
# Testing 2
`5.2.1.5220`


Distance by tap starts working immediately, the text is aligned, and access is added if the text is large.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2a063cda-6b70-404e-a18d-e7810cf94150"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f7e7aedc-9c5a-4086-ba6c-2d98bf010395"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
