### ISSUE TITLE
Map orientation: add mode "Manually rotated (fixed)"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2534]
# ToDo
Follow changes on Android version https://github.com/osmandapp/OsmAnd/issues/15836
- [x] Add fourth mode **Manually rotated (fixed)**
- [x] Rename **Fixed (north is up)** to **North is up (fixed)**
- [x] Description from "compass_click_desc"
- [x] Long tap on compass button on the map, should open **Map orientation** bottom sheet.
- [x] Update icons – [map_orientation_icons.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10579015/map_orientation_icons.zip)

<table style="width:100%">
  <tr>
    <th>General settings</th>
    <th>Long tap on compass</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216602707-59d2b4af-6776-4fba-99ff-04e04b7cf196.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216602688-b190dbc7-3fb3-45ca-9bcf-ce6879fab48e.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2628

**Comment by Zirochkabila** [comment]
04.04 master

- [ ] Names of the map rotation modes differ from those in the task
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222918889-ac0ca974-d5be-4c74-9916-f7e3236db7b7.png"  width="300" height="auto"/> </th>
  </tr>
</table>  


- [ ] If selected "To direction of movement", the name "Map orientation" is moved to the third line
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222918923-f4e557af-ad05-40b1-96e1-7181f32beda6.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
- [ ] Use proper colored icons
- [ ] **Manually rotated** remember orientation set by user.
- [ ] **Compass direction** if user change orientation, it should go back to compass direction.

**Comment by dmpr0** [comment]
## Review 2
- [ ]  Use the same colored icons for UI in Menu - Settings – General settings.
![Screenshot 2023-03-23 at 18 08 22](https://user-images.githubusercontent.com/9365308/227265053-9a6937ce-cb24-42e2-9a3d-4224af7f8d41.png)

**Comment by Skalii** [comment]
[Map orientation - fix icons for manual value](https://github.com/osmandapp/OsmAnd-iOS/pull/2736)

**Comment by Skalii** [comment]
\+

**Comment by Zirochkabila** [comment]
4.4.6.15
Still present https://github.com/osmandapp/OsmAnd-iOS/issues/2534#issuecomment-1481471302

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229474080-b9f1b597-a642-4de0-87a6-871fe03cd181.jpeg"  width="400" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/229474084-a4626893-98b6-499b-8e0a-f56d90b392b2.jpeg"  width="400" height="auto"/> </th>
  </tr>
</table>

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2780

**Comment by shurasmiling** [comment]
- https://docs.osmand.net/docs/user/personal/profiles#general-settings
- https://docs.osmand.net/docs/user/widgets/map-buttons/#compass
- https://docs.osmand.net/docs/user/map/interact-with-map#map-orientation--compass
