### ISSUE TITLE
Add "Moped" profile

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2643]
## ToDo
Follow Android changes https://github.com/osmandapp/OsmAnd/issues/16446

We need to create a new ApplicationMode "MOPED", which will use a "moped" routing profile, have a bicycle as a parent, and be disabled by default.

- [x]  Icon`ic_action_motor_scooter`
- [x]  Name **Moped**
- [x]  Place right after Motorcycle profile in Application profile list.

- - - 
Additional
- [x]  Fix default profiles hard code

**Comment by Skalii** [comment]
[Profiles - Moped](https://github.com/osmandapp/OsmAnd-iOS/pull/2673)

**Comment by Zirochkabila** [comment]
4.4.6.9
Done

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/navigation/routing/moped-routing
