### ISSUE TITLE
Add Search to My Places: Tracks / OSM Edits

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2681]
## ToDo
Similar to #2431 we need to add search bar to the rest My Places screens: Tracks, OSM Edit.

- [x] Search Tracks
- [x] Search OSM Edits.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2792

**Comment by dmpr0** [comment]
## Review
### OSM Edits
- [ ]  Segment view is over safe area
- [ ] Update NavBar icons
- - [ ] Delete – `ic_navbar_trash`

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2811

**Comment by dmpr0** [comment]
# Review 
- [ ]  Search bar, use **Search** instead of **Search favorites** on **ALL** screens.
<table style="width:100%">

  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/233607128-eafe5bde-9417-4e99-a738-9c9c89b16055.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233607242-f142cd64-7386-48f3-bd84-efb6c0ad2d5e.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233607315-1c86406d-3837-4e75-9754-ba095b985bd2.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2822
