### ISSUE TITLE
External input device – additional buttons

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2698]
## ToDo
Tested on TestFlight 4.4.6.9

- [x]  **External input device**, by default set to **Generic keyboard**.
- [x] Zoom in, bind to two keys, `+` and `=`. _(- make '=' equals '+')_
- [x] Bind `Esc` to back? _(to close **Context menu** and **Modal views**)_
- [x] Bind `N` to open **Navigation** view 
- [x] Bind `S` to open **Search** view
- [x] Bind `P` to switch to the next app profile. Show toast like message **App profile: Name**. https://github.com/osmandapp/OsmAnd-iOS/issues/2476
- [x] Bind `O` to switch to the previous app profile.

### Mouse Scroll Wheel
If possible add support for few actions:
- [ ] Change map zoom ? _(- Zoom in / out  with mouse (try))_
- [ ] List scroll

### Fix
For Bluetooth Keyboard  https://github.com/osmandapp/OsmAnd-iOS/issues/2000
- [x]  This action ("D") works for any Profiles (with disabled "External input devices > None")

Button | Action
-- | --
D | "Map orientation"

**Comment by Zirochkabila** [comment]
1. Pressing "S" twice, quickly, opens the search menu, which cannot be closed with "Esc" or "Hide" - you can only drag down

https://user-images.githubusercontent.com/104760013/233391568-96e4954b-c24c-48aa-850f-bad624a6cac5.mov

**Comment by Skalii** [comment]
[External input - fix opening search screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2857)

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/map/interact-with-map/#external-input-device-buttons
+ edited https://docs.osmand.net/docs/user/map/interact-with-map/#settings

**Comment by vshcherb** [comment]
Review docs: Bind P to switch to the next app profile. Show toast like message App profile: Name. https://github.com/osmandapp/OsmAnd-iOS/issues/2476

**Comment by shurasmiling** [comment]
[Add a keybinding to switch to next profile #16327](https://github.com/osmandapp/OsmAnd/issues/16327)

https://docs.osmand.net/docs/user/map/interact-with-map/#external-input-device-buttons
