### ISSUE TITLE
Replace all custom NavBars with system

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2766]
## ToDo
Part of https://github.com/osmandapp/OsmAnd-iOS/issues/1932

- [x]  Replace all custom NavBars with system

### List of replaced NavBars
- [x]  Login to OSM

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2911

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2924

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2928

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2936

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2943

**Comment by dmpr0** [comment]
## Pull 2911 
https://github.com/osmandapp/OsmAnd-iOS/pull/2911

- - - 
<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a7ae2a99-e0ee-4bf3-aae2-23863d62589d"  width="300" height="auto"/> 

- [ ]  Remove search action from NavBar in Menu – Configure Screen – Quick actions – Add action

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2958

**Comment by Zirochkabila** [comment]
4.4.10.8
Search still present


https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/6ec8aa85-df42-4f72-9f0a-ca9378078b15
