### ISSUE TITLE
Bearing – Widgets

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2805]
## Description
Add new **True** nearing widgets. Currently iOS supports **Relative** and **Magnetic** bearing.
* Relative
* Magnetic
* True

## ToDo
- [x]  Functionality of the widgets, remain the same 
- [x]  Separate current Bearing widget into two: **Relative** and **Magnetic**
- [x] **Relative**
- - [x] Icon - `widget_relative_bearing_day/night`
- [x] **Magnetic**
- - [x] Icon – `widget_bearing_day/night`
- [x]  Add new **True** bearing widget. 
- - [x] Icon `– widget_true_bearing_day/night`
