### ISSUE TITLE
Custom button binding for external controllers

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2818]
<details>
    <summary>Android tasks </summary>

> * https://github.com/osmandapp/OsmAnd/issues/18821
> * https://github.com/osmandapp/OsmAnd/issues/20636

</details>  

<details>
    <summary>Related or completed tasks</summary>

> * https://github.com/osmandapp/OsmAnd-iOS/issues/2000
> * https://github.com/osmandapp/OsmAnd-iOS/issues/2698
> * https://github.com/osmandapp/OsmAnd-iOS/issues/921
> * https://github.com/osmandapp/OsmAnd-Issues/issues/2583

</details>  

## ToDo

Add ability to add External controller with custom set of binding buttons.
- [x] Allow to add new device 
- [x] All actions should be from Quick Actions

# Main screen

- [x] Show actions for default devices: **Keyboard**, **WunderLINQ**
- - [x] Hide toolbar for this types

### Device is not selected
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/551546e8-e15b-492c-bcbd-8f0b66a863c4"  width="250" height="auto"/> </td>
  </tr>
</table>   

<details>
    <summary>Full Screenshot</summary>
    <table style="width:100%">
      <tr>
    <td><img src="https://github.com/user-attachments/assets/cd703b73-db90-44d4-a87f-bc0c8209a964"  width="300" height="auto"/> </td>      </tr>
    </table>
</details>  

- [x] Show when **None** is selected for Device. 
- [x] Icon – `ic_custom_keyboard`
- [x] Description – `To use an external input device with OsmAnd, select one from the list above or add a new one`

### New device

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/31722007-5db7-4c9b-b05a-3f422fce901b"  width="250" height="auto"/> </td>
  </tr>
</table>   

<details>
    <summary>Full Screenshot</summary>
    <table style="width:100%">
      <tr>
    <td><img src="https://github.com/user-attachments/assets/a60e0fb2-be84-4ad0-a6c7-e9f53018790a"  width="300" height="auto"/> </td></tr>
    </table>
</details>  
 
- [x] Show when device without Key Assignments is selected. 
- [x] Icon – `ic_custom_keyboard_disabled`
- [x] Description – `Select an action and assign a key by tapping the 'Add' button.`
- [x] Button – Add
- - [x] Tap should open **New key assignment** view

## Main screen With actions, [Figma](https://www.figma.com/design/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=3179-54736&m=dev)

<table style="width:100%">
  <tr>
    <th>Actions list</th>
    <th>Edit mode</th>
    <th>Clear all confirmation</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e986a0a4-fd7b-498e-93f4-ccfbdc2d558b"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d90ab034-9079-4ddd-a402-faad8c8e5198"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/38ea45bb-dc21-4581-8bb0-90e345b7c536"  width="150" height="auto"/> </td>
  </tr>
</table>   

**Default**
- [x] Show **Type** cell
- - [x] Show seleted type on the right side
- - [x] Tap on cell, should open **Devices** list
- [x] Show list of key assignments
- [x] Add ToolBar with two actions:
- - [x] **Add** – tap should open **New key assignment** view
- - [x] **Edit** – open Edit mode

**Edit mode**
- [x] Hide **Device** cell
- [x] ToolBar – Add action **Clear all**
- - [x] Action should allow to clear all key assignment's
- - [x] Show confirmation alert on tap

### Item TabellCell

<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>Edit mode</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/47fbf732-b488-4302-8bc7-d1369ecd17e6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e033f6f5-e9c8-40a8-8f1f-9f41397021df"  width="300" height="auto"/> </td>
  </tr>
</table>   

**Default:**
- [x] Icon
- [x] Key assignment name, (`Map – Move up`)
- [x] Assigned button, could be more than one, (`P`)
- - [x] Colors
- [x] Chevron
- [x] Tap on item open Key assignment screen

**Edit mode:**
- [x] **Remove** button
- [x] Icon
- [x] key assignment name
- [x] Assigned button

# Device selection

<table style="width:100%">
  <tr>
    <th>Device list</th>
    <th>Edit mode</th>
    <th>Add new device</th>
    <th>Device actions</th>
    <th>Remove device</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/689e22de-f5c3-43ca-83f3-37805e0c770a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/079ade87-98b6-48d9-a842-ba701c3f97b6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d66cbd1a-3e2e-4e0e-a0f5-d4c55aaed12b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/bd882e65-3d82-45df-ac13-dda50323e0fb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7aa8c6c2-4636-4dd0-9b19-df38287b5feb"  width="300" height="auto"/> </td>
  </tr>
</table>  

### Default
- [x] Display a **Toolbar** with two actions:
- - [x] **Add**: Tapping this opens the **Add New Device** alert.
- - [x] **Edit**: Tapping this enters **Edit Mode**.
- [x] Tapping a device selects it and closes the view.
- [x] Display an **Info** button to the right of user-added devices.
- [x] Tapping the **Info** button opens an action sheet.

### Edit mode
- [x] Hide the **Toolbar**.
- [x] Display only the list of user-added devices.
- [x] Display a **Remove** button next to each device.

**Add new device** alert
- [x] Title – Add new device
- [x] Include an input field for the device name.
- [x] Actions – **Cancel** and **Save**

**Remove device** alert
- [x] Title – **Remove device**
- [x] Description – ``Are you sure you want to remove “Keyboard 2” and all key assignments?``
- [x] Actions: **Cancel** / **Remove**

**Custon device Action sheet**
- [x] Display the device name.
- [x] **Rename** – Opens an alert to rename the device.
- [x] **Duplicate** – Creates a copy of the device, including all key assignments.
- [x] **Remove** – Opens the **Remove Device** confirmation alert.
- [x] **Cancel** – Closes the action sheet.

# Key assignment

## Default mode, [Figma](https://www.figma.com/design/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=2901-27840&m=dev)

<table style="width:100%">
  <tr>
    <th>Default view</th>
    <th>Additonal Menu</th>
    <th>Remove key assigement - Alert</th>
    <th>Rename - Alert</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f6149389-f075-4226-9c7c-9a198d41de0c"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4b853274-08a5-4f6b-852b-7a10d1c689fa"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/732f4b36-9b3d-433d-8ce6-dc4624fb8f03"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/0dafc109-1d43-49b7-a124-e1152717117d""  width="150" height="auto"/> </td>
  </tr>
</table>  

**Context menu**
- [x] Edit – open edit mode. Icon – `ic_custom_key_edit`
- [x] Rename – Show **Rename** alert on tap. Icon – `ic_custom_edit`
- [x] **Remove** – Show **Remove key assigement** alert on tap. Icon – `ic_custom_trash_outlined`

## New / Edit key assignment

<table style="width:100%">
  <tr>
    <th>Empty</th>
    <th>With action</th>
    <th>With action and a Key</th>
    <th>Edit</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/de36fc9d-8c26-468f-bb59-d235d73cce31"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/5c15fa0b-c00b-4bd9-b653-9bb47c13f860"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1cf27ece-988b-487a-84cc-f119304a30a1"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2af8cfc1-5d09-4070-b42d-adc8d86a0309"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Show two groups **Action** and **Assigned Keys**
- [x] With **Add action** and **Add key** button
- - [x] Tap on **Add key** should open Add key view 
- [x] Max one action per assignment
- [x] Few buttons can be added to one action

## Add key, [Figma](https://www.figma.com/design/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=3188-11974&m=dev)

<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>After press on button</th>
    <th>Warning</th>
  </tr>
  <tr>
      <td><img src="https://github.com/user-attachments/assets/a74e6c00-c650-4b29-b370-48d793b2e9f6"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7ce6b53a-c348-4e66-84a0-fad7b8800d3b"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2d96df87-47dd-4160-8c27-48806f8e17a5"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Show description with action name: ``Press the button on your device to assign it to the action: ACTION_NAME``
- [x] Show Default state, before user pressed on button
- [x] Show warning if pressed button is alreasdy taken, include key and action name
- - [x] Text – ``The “KEY” key is already assigned to action: “ACTION_NAME.”``

**Comment by dmpr0** [comment]
## UI Review

- [ ] Unable to add Custom keyboard

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/a751f676-bf90-464f-90a0-73899748b197"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/a5053f75-675c-4af2-ae8d-a3016caac0af"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Broken strings

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/4134cdf0-e29c-42f8-b07c-74e9ccdd55a7"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Support long click for move map actions
