### ISSUE TITLE
Map buttons jumps on start

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2853]
## ToDo
- [x]  Fix Navigation button color
- [x] Remove bottom button jump

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/235594804-8afd48f2-f2bf-45c9-bd83-b53e5e22e173.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/235594799-9922e0ca-532e-4794-94ea-15089919c272.png"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/235594993-4ede12cf-49ad-4868-bb33-05e9ba32d772.mov"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3036

**Comment by dmpr0** [comment]
# Review – 1

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ebe0e5f1-68af-4c4b-bb5a-9da284ebb9c5"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Quick action button is orange for few second after start too.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/49bc2418-b228-462d-a8d6-ce82934ca024

**Comment by DmitrySvetlichny** [comment]
It looks like a 3D mode button, there was such a problem, this button appeared on the screen with a quick action icon, but this problem was fixed in the previous PR. This bug doesn't work for me! Perhaps this is due to the position of the 3D and quick action modes?

**Comment by yuriiurshuliak** [comment]
Upon initiating the application, I was unable to replicate the bug. The buttons' appearance in terms of color and placement appears as expected.


https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/9b5a097f-e273-464d-93a5-8ed7e62b63b1
