### ISSUE TITLE
Button to switch 3D/2D Mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2861]
# ToDo
Add separate button to control 3D mode. Currently 3D mode can be enabled by gesture or by second tap on my location button.  

* Icons [3DModeIcons.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11382957/3DModeIcons.zip)

## Map
- [x] Allow to move button, similar to Quick action
- [x] Button position is profile depended option.
- [x] **3D** 
- - [x] Icon –  `ic_custom_3d`
- - [x] Tap – switch map to 3D mode.
- - [x] `accessibilityLabel` = 3D mode
- - [x] `accessibilityValue` =  
- [x] **2D** 
- - [x] Icon – `ic_custom_2d`
- - [x] Tap – switch map to 2D mode.
- - [x] `accessibilityLabel` = 2D mode
- - [x] `accessibilityValue` =  
- [x]  Remove 2.5D mode button from location button
<table style="width:100%">
  <tr>
    <th>Map in 2D</th>
    <th>Map in 3D</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/235867383-6f5f5bc4-16fb-4f2e-baec-91b9beed9614.png"  width="375" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/235867388-3e12f3d8-0549-4936-9aec-e5e74fbcfe70.png"  width="375" height="auto"/> </td>
  </tr>
</table>   

## Configure screen
- [x]  Add new item to **Button** group in **Configure Screen**, 
- - [x] Name **3D Mode**
- - [x] Icon = depends on status
- - [x] `accessibilityLabel` = `3D Mode`
- - [x] `accessibilityValue` =  Selected mode, for example `Visible`
- [x]  Tap on item should open screen with modes.

### View, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=729%3A86767&t=SEoWcAnAFE0yhvG4-1)
- [x] Default state – **Visible in 3D mode**
- [x] Title – `3D Mode`
- [x] Description below title – `Touch map with two fingers and moves them up and down to adjust map tilt.`
- [x] Tap on any action should close the bottom sheet

**Actions:** 
- [x]  **Hidden** – button always hidden
- - [x] Icon – `ic_action_button_3d_off`
- - [x] `accessibilityLabel` = `Hidden` 
- [x] **Visible** – button is always visible
- - [x] Icon – `ic_action_button_3d`
- - [x] `accessibilityLabel` = `Visible` 
- [x] **Visible in 3D mode** – button visible if map is titled. User can switch map to 3D Mode by two finger gesture, in this case button should be shown.
- - [x] Icon – `ic_action_button_3d `
- - [x] `accessibilityLabel` = `Visible in 3D mode` 
- [x] Add hint below actions: `Long tap on button allows to change button position.`
<table style="width:100%">
  <tr>
    <th>Configure Screen</th>
    <th>3D Mode – Bottom sheet</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/235869771-e6defeeb-fcd7-4a00-9ac1-c937c10fc5da.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/235869766-4abebddd-213d-4721-bb36-2944cb0184fe.png"  width="180" height="auto"/> </td>
  </tr>
</table>   

## Additional   
- [x] Remove **2.5 D view** option from **General settings**
- [x] Remove 2.5D mode from location button

Android task https://github.com/osmandapp/OsmAnd/issues/16026

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/widgets/map-buttons#3d-mode

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <th>Result</th>
    <th>Figma</th>
  </tr>
  <tr>
    <td valign=top><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e1fcb070-1819-4ee4-8cb9-4aa882a9acec"  width="375" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/235869766-4abebddd-213d-4721-bb36-2944cb0184fe.png"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Move description from HEADER to separate item.


- - - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fc796213-2cde-4559-b47b-2ad25f3a4be3"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Remove second line with duplicated string

**Comment by DmitryAlexei** [comment]
@dmpr0 
There is a typo in the text *Touch map with two fingers and moves them up and down to adjust map tilt*. Word **move** should be without **S** on the end.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3026

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3051

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/profiles#appearance
https://osmand.net/docs/user/widgets/map-buttons#3d-mode
