### ISSUE TITLE
Settings are not preserved while enabling / disabling Routes 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2878]
## ToDo
- [x]  Remember selected value for Hiking routes
- [x] Remember selected value for Cycle route
- [x] Remember selected value for MTB routes
- [x] Test export/import

## How to reproduce
* Open **Configure Map** - **Hiking routes** – Turn on
* Switch **Color routes by** to **Node network**
* Turn off **Hiking routes**
* Turn on **Hiking routes**

### Actual result
* After enabling **Hiking routes** option **Color routes by** will be reset to first value: **OSMC**

### Expected result
* **Hiking routes** should save previously selected value in **Color routes by** option.

<table style="width:100%">
  <tr>
    <th>Hiking routes</th>
    <th>CycleRoutes</th>
    <th>MTB Routes</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f2821309-d210-46ed-900f-b3200b03bba8"  width="auto" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/542678b8-fd1e-4f17-b60e-f93e22d147fd"  width="auto" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d913f72b-f599-4801-8eda-492aa1ee1eab"  width="auto" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2970
