### ISSUE TITLE
Default appearance for favorite folders

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2902]
# ToDo
* Add context menu for Favorites folders
* Allow to set default appearance for Favorites folders. Sync code with Android.

## Backend
- [x]  Import / Export should work for folder appearance 
- [x]  Appearance parameters should be added as <extension> to GPX files

## My Places
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cda31304-d7b1-422f-9487-b1e8838244ad"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Long tap on folder, should show context menu
- [x] Context menu actions. Use SF Symbols for icons.
- - [x] **Change appearance** –  `paintpalette`
- - [x] **Share** – `square.and.arrow.up`
- - [x] **Delete** – `trash`

## Add new group / Change appearance
<table style="width:100%">
  <tr>
    <th>Add new group</th>
    <th>Save dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f483ca0a-acaa-4c7c-be6a-ad1b6ca937a8"  width="300" height="auto"/> </td>
    <td valign=top><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4fc57baf-33f5-4b44-98e2-517bddd47da1"  width="300" height="auto"/> </td>
  </tr>
</table>  

* **Add new group** and **Change appearance** dialogs share the same UI, difference is only in title and additional actions sheet after saving.
- [x]  Add option to set **icon** folder
- [x] Add option to set **shape** for folder

## Adding favorite / waypoint
* Color / Shape / Icons should be preselected when user select the group in Add favorite / Waypoint dialog. It currently works for color

**Comment by vshcherb** [comment]
* Apply to existing points dialog
- Should **explicitly** specify what will be changed (all is fine)
- Or shouldn't propose the change

**Comment by Skalii** [comment]
[add appearance for group (iOS)](https://github.com/osmandapp/OsmAnd-iOS/pull/3185)
[add appearance for group (core)](https://github.com/osmandapp/OsmAnd-core/pull/640)

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/261f6452-8343-4708-8306-6ae179bb2688"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/aa39593b-c55f-4c34-a730-6948c88e5433"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Unable to change shape

**Comment by Skalii** [comment]
fix update of favorite appearance after group selection
