### ISSUE TITLE
Hiking route details: highlight URL

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2909]
## Description
URL in route details is shows as regular text, 
* Route https://hiking.waymarkedtrails.org/#route?id=2757894
* Coordinates `51.18045° N, 16.23554° E`

### ToDo
- [x]  Make link tapable
- [x]  Use active color for link
<table style="width:100%">
  <tr>
    <th>Szlak dookoła Legnicy</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5af05038-41fa-4522-aef9-3b2089774c04"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2966

**Comment by dmpr0** [comment]
# Review
- [ ]  Open link in inner safari tab (without leaving OsmAnd)
<table style="width:100%">
  <tr>
    <th>Website</th>
    <th>Wikipedia</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d7f2b89e-5701-4b23-88ee-5bf0f27de7ca"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4240f95a-9cdb-4ecf-acf2-4b194e8cbb9b"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2979
