### ISSUE TITLE
Elevation Profile - add min and max elevation information

### ISSUE THREAD

**Issue by rouletout** [osmandapp/OsmAnd-iOS#2930]
Feature Request

See screenshot, the elevation profile would be more useful if it would also show the min and max elevation of the route and not just the meters climbed / descended. There is actually space for it just next to these numbers.

Additional helpful info would be the introduction of a marker for each waypoint / destination in the route (eg a vertical tick or line) on the elevation profile.
<img src="https://github.com/osmandapp/OsmAnd/assets/19162952/876a5d47-5a7a-4cb3-b87e-2febcf12a709"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
## ToDo

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7f48637e-e8c4-4f6c-88eb-887e93766579"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

* Altitude range can be show next to Uphill / Downhill
* Horizontal scroll should be added for cases when **Vehicle engine** type is provided, CO2 emission is shown in this line too.

**Comment by dmpr0** [comment]
# Review 
 

<table style="width:100%">
  <tr>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3f253bef-54d4-4432-8687-b914ecc8dcd5"  width="375" height="auto"/></td>
  </tr>
</table>   

I propose to replace all icons with SF Symbols.
- [ ] Uphill `arrow.up.right`
- [ ] Downhill `arrow.down.right`

Elevation information:
- [ ] Show Max first.
- [ ] Split into two separate values:
- [ ] Max `arrow.up`
- [ ] Min `arrow.down`

**Comment by dmpr0** [comment]
@vshcherb feedback for other part of review is needed.

**Comment by dmpr0** [comment]
# Review - 3

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>App</th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/58211abb-53cf-4f28-a699-c8054b020280"  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by vshcherb** [comment]
Incorrect implementation from (non-approved review) - this how it should be

To do:
- [ ]  Use iconColorDefault for icons
- [ ]  Use textColorSecondary for text
![image](https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/2248fc6c-6180-4886-ac00-4e3794b4ec72)
