### ISSUE TITLE
Hard to hide context menu

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2938]
# Part 1

## What's here, [Figma](https://www.figma.com/file/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?type=design&node-id=2368-30331&mode=dev)
We need to add close button

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2eb1fac8-debe-41d4-8318-1d3a19b50975"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/83ee0a19-b379-4593-bad3-ed72b7f5a64a"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Add title `What’s here`
- [x] Add close button 
- - [x] Icon `ic_custom_close`
- - [x] Tap area should be 44x44

- - -

<details>
    <summary>Orignal description</summary>

## Description
- On basemap it's impossible to touch outside the menu, cause regions are selected
- On detailed zoom it's hard to touch outside cause lots names / icons
- It's very hard to drag and pull menu down

## ToDo
- [ ]  Disable selecting regions (when tap on the empty space and menu is open)
- [ ]  Add close button to not broke behavior for which users get used to. (Move icon to the left)

</details>  

# Part 2

## POI Context menu

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current look</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/85732c91-4f8c-4db6-8cb1-41b5418f097a"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2766be88-c50e-4fd4-9559-4b1e3e3d57c6"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

**Pin**
- [ ] Use new icon for pin `ic_map_pin`
- [ ] Move icon to PIN on the map, icon size should be `30x30`

**Context menu**
- [ ] Remove POI icon Place close button instead of icon

**Comment by dmpr0** [comment]
# Review 
- [ ] Look to custom
