### ISSUE TITLE
Wikipedia links doesn't works in hiking route details

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2944]
## Description
Hiking route details info can have Wikipedia link, for example: [Waymarkedtrails](https://hiking.waymarkedtrails.org/#route?id=1221214&type=relation&map=11.0/51.3475/6.8927), [OSM](https://openstreetmap.org/relation/1221214). Currently in Route details OsmAnd shown only `Wikipedia: de:Jacobsweg`.

> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/1955

## ToDo
- [x]  Wikipedia links in Route details should work the same way as in context menu.

### Expected result
* User will able to tap on Wikipedia link:
* * if user have downloaded wikipedia file for this region, link should open offline.
* * If offline data is absent, Wikipedia link should be opened online using Chrome tabs.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4130eda7-20a7-40bc-9351-459a1fbf90ca"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[fix wikipedia url in track menu](https://github.com/osmandapp/OsmAnd-iOS/pull/2968)

**Comment by dmpr0** [comment]
## Review
- [ ]  Read task details

**Comment by Skalii** [comment]
[open wiki from track menu](https://github.com/osmandapp/OsmAnd-iOS/pull/2977)

**Comment by dmpr0** [comment]
# Review – 2
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/98703d2f-c28c-4be3-9bca-53b9cde23411"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Crash after searching for wiki article

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/8c43f28d89a3dd4582f66a61a2e5f98063d7de49
