### ISSUE TITLE
Turn Instructions – Route details

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2981]
## ToDo
* Add missing turn instructions to Route details screen

<table style="width:100%">
  <tr>
    <th>Half screen</th>
    <th>Full screen</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bbd7e826-f892-48cf-9299-76c1a1ede028"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f95ff8e1-82a8-4b52-82ff-1976faf540b1"  width="150" height="auto"/> </td>
  </tr>
</table>   

# Route details 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1002b75c-d0a2-49b5-8a67-5583bf2e29d1"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add segment control to divide information on the screen into two tabs: **Instructions** and **Analysis**

## Instructions, [Figma](https://www.figma.com/design/ZHXxcxI05wG6OUlOjwFHXn/Route-Preparation?node-id=1402-24275&m=dev)
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fceb7b20-b5bf-4470-afcb-34c07a28361f"  width="375" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/665966b2-c746-430e-9f09-8bdd81f2261c"  width="375" height="auto"/> </td>
  </tr>
</table>   

> Android https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java#L735

- [x] Show detailed route instructions
- [x] Show main turn arrow, size 40x40 pt
- [x] Show distance to manoeuvre `600 m`
- [x] Show turn instruction, example `Turn right and go вулиця Гетьмана Павла Скоропадського`
- [x] Show total route distance and time `500 m • 00:45`
- [x] Show lanes

## Analysis
- [x] Should contain all graphs data that already presented on Route details screen

### Share sheet

- [ ] Add **Print** action, icon –

**Comment by vshcherb** [comment]
3 separate tasks are needed?

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/navigation/guidance/navigation-settings#recalculate-route

**Comment by nnngrach** [comment]
RouteDirectionsCard.java
route_directions_card.xml

**Comment by tigrim** [comment]
**Technical Plan:**

1)Check the implementation on Android.
2)Synchronize missing code.
3)Examine how OADestinationsLineWidget is implemented.
4) - (void) drawArrow:(OADestination *)marker inContext:(CGContextRef)ctx

**UI:**
UISegmentedControl
https://developer.apple.com/design/human-interface-guidelines/segmented-controls

**Testing:**
Since the main content has moved to the Analysis tab, which is displayed after switching to UISegmentedControl (Instructions and Analysis), it is necessary to ensure that in all cases when opening this screen, the correct tab is preselected.

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3737

**Comment by dmpr0** [comment]
# Review 
- [ ] Show total route distance and time on the right sie `500 m • 00:45`

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bee13dc3-b8bf-40db-9df9-11a1d07e20ff"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Info block is lost on Analysis screen

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3754

**Comment by dmpr0** [comment]
# Review 2
Additional functionality.

<table style="width:100%">
  <tr>
    <th>Left</th>
    <th>Right</th>
    <th>Ahead</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/52cf203f-8f99-49b4-b3a7-0d135bf4236c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1acbc842-61dc-4c11-907f-d9487ad19c34"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/358e5574-81f6-460a-b8a7-3d847945385a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by shurasmiling** [comment]
- [Route details](https://osmand.net/docs/user/navigation/setup/route-details#turn-by-turn-information)
- [Route maneuvers widget](https://osmand.net/docs/user/widgets/nav-widgets#route-maneuvers)
- [Lane widget](https://osmand.net/docs/user/widgets/nav-widgets#lanes)
