### ISSUE TITLE
One list of widgets for Top/Bottom panel

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2989]
# Description

Allow to use the same widgets on top and bottom panel. Currently we have 3 widgets on Top panel:
* Coordinates: 
* * Map center, 
* * Current location
* Lanes
* Street name
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ae5a0c2f-cf99-4e69-afe8-cb3cb5cee567"  width="300" height="auto"/> </td>
  </tr>
</table>    

## ToDo
- [x] Allow to use bottom side of the screen for widgets
- [x] Allow to make duplicated for widgets
- [x] Rework how Markers TopBar appears

## Markers 
We need to allow for users to add Markers ToBar and two Map marker widgets separately and unlinked it from 
- [x]  Remove **Distance indication** group for Map Markers – Appearance
- [x]  Add settings **Active markers**, One or Two

### Map markers bar

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Screen</th>
    <th>Bottom sheet</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/65e0d01d-d6e8-4389-b77f-b4c8a6754a8f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ea1ec2ae-46c4-46b0-9aa8-1f1d3ddeef30"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

- [x] Add **Map markers bar** as widget for Top / Bottom panel
- - [x] Icon `widget_markers_topbar_day/night`

### Map markers widget

<details>
    <summary>Screenshots</summary>
<table style="width:100%">
  <tr>
    <th>Screen</th>
    <th>Click on widget</th>
    <th>Show</th>
    <th>Click on widget</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6bf1841d-7363-467e-89ed-46e2d745738b"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b20296be-726f-4f55-9aa0-e30fae5de8b8"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a30f5e33-a9eb-4c05-9d65-597ff3623f3b"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a8f08cdf-d2ca-4815-835f-2bd9fbfd6c7f"  width="200" height="auto"/> </td>
  </tr>
</table>   
</details> 

**Settings**
- [x]  **Show**
- - [x] **Distance** - show distance to the widget
- - [x] **Estimated arrival time** – show ETA for widget
- [x]  **Interval** – Allows to set interval for witch ETA will be calculated
- - [x] By default 30 min
- - [x] Max 60 min
- [x] **Click on widget**
- - [x] **Switch mode** – tap on widget will switch what widget show: Distance or Arrival time
- - [x] **Go to marker location** - tap on widget will move map to the marker location

**Comment by Skalii** [comment]
[Widgets - top/bottom panels](https://github.com/osmandapp/OsmAnd-iOS/pull/3057)

**Comment by Skalii** [comment]
[Widgets - top/bottom panels r4.5](https://github.com/osmandapp/OsmAnd-iOS/pull/3070)

**Comment by dmpr0** [comment]
# Review - 1
## Coordinates widget

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/21454475-ab75-49ba-a30f-c848bdcf2350"  width="375" height="auto"/> </td>
  </tr>
</table>   

Apply new look for coordinates widget
- [ ]  Use coordinates format selected in profile settings
- [ ] Widget height – 44pt
- [ ] Left / Right padding – 16pt

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/e3d0349aebcafff9360e6011a5b94a22882cd825

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3091

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c34e48ff-261f-4f7e-a78d-f38fc5baf97e"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

- [ ] Center arrows horizontally on Lanes widget.

- - - 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4e17a112-8b0b-4ab1-84a1-4f9c685c459e"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ]  Horizontal separator is missed

**Comment by dmpr0** [comment]
# Review - 2

**Comment by Skalii** [comment]
- [x] show marker icons on side widgets
- [x] update ruler on map (RulerDistanceWidget) after changing settings

**Comment by Skalii** [comment]
[Fix top/bottom widgets r4.5](https://github.com/osmandapp/OsmAnd-iOS/pull/3120)

**Comment by dmpr0** [comment]
# Review
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>UK</th>
    <th>EN</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/31fc7dad-2aa9-4a26-bb21-c62279a7019a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c50b279c-6e42-4b60-9f62-ad42e5faf042"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ] Show **First Map marker** always as first item in Add widget > Map markers

**Comment by Skalii** [comment]
[Fix top/bottom widgets 2 r4.5](https://github.com/osmandapp/OsmAnd-iOS/pull/3127)

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/configure-screen#top--bottom-panel-widgets

**Comment by EugeneZmeuk** [comment]
**15-04-2024 Review**
