### ISSUE TITLE
Navigation settings loose icons

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3060]
## Description
Regression. Navigation settings loose icons

### ToDo
Fix listed tabel cells
- [x]  **Avoid roads** – `ic_custom_alert`
- [x] **Follow track** – `ic_custom_trip`
- [x] **Navigation settings** – current profile icon
- [x] **Customise route line** – `ic_custom_appearance`

### Actual result

<table style="width:100%">
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/320cfdb1-4c51-45de-bc5c-16e2fae6c592"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0edf7123-adbe-4156-9ce8-63bb456cae86"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3063
