### ISSUE TITLE
Introduce new Help screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3161]
# ToDo
Related to Android / iOS.
Offline Cache is preferable once page is open
Android task https://github.com/osmandapp/OsmAnd/issues/17228

<table style="width:100%">
  <tr>
    <th>Help</th>
    <th>Menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b5f17ad4-af2b-4d46-affd-e90c76de24c2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1bfad3bb-9456-49aa-9b17-0756f05cb8d6"  width="300" height="auto"/> </td>
  </tr>
</table>   

## NavBar

**Menu**
- [x] **Copy build version**
- - [x] Icon `ic_custom_clipboard`
- - [x] Tap should copy build information
- [x] **Send log file** 
- - [x] Icon `ic_custom_file_send_outlined`
- - [x] Tap should open share sheet with log file

## Most viewed
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2956e09e-dce0-42a7-abd4-be2914a8d858"  width="300" height="auto"/> </td>
  </tr>
</table>   
 
Card with the list of most viewed articles.

- [x]  Use file to get most viewed articles https://github.com/osmandapp/web/blob/main/main/static/help-links-ios.json
- [x]  Show list of all articles from `popularArticles`
- [x] Use icon `ic_custom_file_info`

## User guide
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b3172e19-d5d9-4539-9da5-a9573f93de86"  width="300" height="auto"/> </td>
  </tr>
</table> 
Card with the list on links to user guide categories similar to docs.osmand.net

- [x]  Icon `ic_custom_book_info`

## Troubleshooting
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b8cf9733-ba82-43ec-9c6d-4409f867c5a1"  width="300" height="auto"/> </td>
  </tr>
</table>  

## Contact us
<table style="width:100%">
  <tr>
    <th>Contact us</th>
    <th>Telegram chats</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/535543e4-bb11-4de3-9dc4-4016ced1246d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0ddeaf3d-5776-4297-8b31-ff4403cf84da"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x]  **Contact support**
- - [x] Icon `ic_custom_at_mail`
- [x] **GitHub Discussion**
- - [x] Icon `ic_custom_logo_github`
- [x] **Telegram chats**
- - [x] Icon `ic_custom_logo_telegram`
- - [x] Tap open new screen with the list

## Report an issues
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5697508a-3291-4dcf-94ab-030a59e494e7"  width="300" height="auto"/> </td>
  </tr>
</table>  

Separate card with the button to repost issues or send log files.

- [x]  **Open issue on GitHub**
- - [x] Icon `ic_custom_logo_github`
- - [x] Link `https://github.com/osmandapp/OsmAnd-iOS/issues`
- [x]  **Share log**
- - [x] Icon `ic_custom_file_send_outlined`
- - [ ]Tap, send log file?

## About OsmAnd
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/02cd8958-11b1-41ca-8e75-e13e74a6efdf"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x]  **About OsmAnd**
- - [x] Icon `ic_custom_osmand_logo_big`
- - [x] Link `https://docs.osmand.net/help-online/about`
- [x]  **What’s new**
- - [x] Icons `ic_custom_clipboard`
- - [x] Link 
- - [x] Show version number on second line
- - [x] Long tap on list item should copy build number to clipboard
- [x]  **TestFlight**
- [x] Second line `Download and install beta version of OsmAnd `
- - [x] Icon `ic_custom_download`
- - [x] Link  `https://docs.osmand.net/docs/versions/nightly_versions#testflight`

**Comment by dmpr0** [comment]
# Review 
**User guide group**
- [ ] Begin with OsmAnd link is missed

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3304

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3305

**Comment by vshcherb** [comment]
- [ ] Sorting

**Comment by dmpr0** [comment]
# Review - 2

**Contact support** action

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/987cd605-729e-4bc1-9fde-71070717a3c8"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Remove subject
- [ ] Broken encoding?

**Comment by DmitrySvetlichny** [comment]
https://developer.apple.com/documentation/uikit/uidevice/1620015-name

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3368

**Comment by EugeneZmeuk** [comment]
[**25.03.2024 Review**](https://github.com/osmandapp/OsmAnd/issues/17228#issuecomment-2018736482)
