### ISSUE TITLE
iOS tracks imported from GPX seen as unique track    

### ISSUE THREAD

**Issue by Baldo81** [osmandapp/OsmAnd-iOS#3182]
### Description

On iOS when importing a GPX with different tracks on it the behaviour is very different from Android  

1. on iOS I can’t choose witch track I want to import from the GPX 
2. On iOS I see a single track with different segments but I can’t modify the appearance of each segment. It modifies the appearance of all the track
3. On iOS I can’t make visible only one of the track of the GPX

I attach the screenshot of iOS and what would be expected in Android 

### Steps to reproduce

Import the attached GPX with iOS device
Import attached GPX with Android device and check the different behaviour. 

### Actual result

On iOS the GPX is seen as single track with segments. 
on Android (as I would expect) is seen as different tracks. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/36080584/8fffa3a4-e548-4777-acbe-4421dc753e5c"  width="300" height="auto"/> </td>
  </tr>
</table>

On iOS I can’t modify appearance of each segment as I can do in Android. It modifies the whole track. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/36080584/3e078c13-6c34-46fa-8ee6-8a7e01c196b8"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

I would expect the same behaviour as Android as is the best user experience 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/36080584/bb0f08a8-f500-4f7e-a060-c4971a29a9f8"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5
Android/iOS version: IOS 17
Device model: iPhone 13
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/OsmAnd-iOS/issues/1928

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/2730

**Comment by dmpr0** [comment]
# ToDo
> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/892


# Import track, [Figma](https://www.figma.com/design/0tOguKltp8m6UuLp7biZh5/My-places?node-id=3797-25229&m=dev)

## Loading state

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9810f639-caa9-4f7a-bbaa-5940dd67cb37"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show progress while reading file

## Import state


<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8f2b0ef2-410a-4068-9e1b-dea9021d935d"  width="200" height="auto"/> </td>
  </tr>
</table>   

### NavBar

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1ffc1b00-5fdc-44c9-bfd3-65a487b1b309"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title – `Import tracks`
- [x] Leading action – `Close`
- - [x] Show confirmation dialog on tap
- [x] Trailing action – `Select all` or `Deselect all` depending on the current state
- - [x] Select or deselect all tracks on tap

#### Confirmation dialog

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/45a0d7b4-84e8-4cc2-bac5-0663db28cce8"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title: `Cancel import?`
- [x] Message: `If you close now, your track selections will not be imported.`
- [x] Left action (Default/Cancel style): `Continue`
- [x] Right action (Destructive style): `Close`

### Description

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0103a010-8fa3-49f2-81dd-5f65080ffa0d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Display as top item
- [x] Description – `The file [File name] contains [tracks qty] separate tracks. Select the ones you want to import.`
- - [x] Use plurals for `separate tracks`
- [x] Button – `Import as one track`
- - [x] Import file as one track
- - [x] Implement using a standard native iOS list button cell.

### Track group

<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>Selected</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/825f7f18-3f8d-4253-954a-d872f5d22b16"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4af3eb57-3d1f-4bab-af89-7710b069fa09"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Use grouped list style
- [x] Show checkbox
- [x] Show track name: Use the name from `<name>` for each track if available. If it's empty, use the main track/file name + quantity. **Example:** File `Amsterdam.gpx` contains tracks: `Amsterdam - 1`, `Amsterdam - 2`
- [x] Show the track count on the second line `Track 1 of 4`
- [x] Show map preview with the track line.
- [x] Show stats. Use the same component we use in the track context menu
- [x] Waypoints: Show the selected and total quantity of waypoints from the file.
- - [x] Tapping on the item should open the Waypoints view.

### Select folder
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/12035956-70cd-4ad6-b215-67489885cf97"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Use a grouped list style
- [x] Use the group selection component we already use in Add/Edit Favorite
- [x] Move the **Add** button to the first position
- [x] Description: `Select a destination folder for the imported tracks.`

### Button

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9d81762c-bc75-4d2f-a0db-705431018d83"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show at the bottom of the screen
- [x] Disable if no tracks are selected
- [x] Indicate the selected tracks quantity – `Import 1/4`

# Waypoints

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c78f5c3e-450a-4412-ae8e-da58b5af97bf"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show list of all Waypoints and groups
- [x] Compare waypoints coordinates with track coordinates, preselect waypoints to nearest track. The same waypoints can be selected for two or more tracks.

### NavBar

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/aa6ae347-bfdd-46b0-b0df-cf68e139852f"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [x] Title – `Waypoints`
- [x] Leading action – `Close`
- - [x] Show confirmation dialog on tap
- [x] Trailing action – `Select all` or `Deselect all` depending on the current state
- - [x] Select or deselect all tracks on tap

### Confirmation dialog

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/40eb3da2-54fb-45a6-a59f-f8d1d9a8c92a"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title – `Unsaved changes`
- [x] Description – `Your waypoint selections will not be saved if you close now`
- [x] Actions – `Continue` / `Close`


### Description

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0103a010-8fa3-49f2-81dd-5f65080ffa0d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Display as top item
- [x] Description – `Selected waypoints will be added to the [TrackName] track.`
- [x] Button – `Auto-select nearest points`
- - [x] Select nearest points on the tap
- - [x] Implement using a standard native iOS list button cell.
- [x] Description – `Automatically find and select the waypoints closest to this track.`


### Folder

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/37729e29-a2dd-425f-8bb8-184fe09abb3e"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Try to use UI component we use in Track context menu > Waypoints
- [x] Use a grouped list style


### Button

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9d81762c-bc75-4d2f-a0db-705431018d83"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show at the bottom of the screen
- [x] Disable if no tracks are selected
- [x] Label – `Apply`



# After import
- [x]  More than 1 track: open My Places > Tracks > user selected Folder, to show all tracks
- [x]  For 1 track – open map with context menu for the imported track. (current default behavior)


## Additionally 
https://github.com/osmandapp/OsmAnd-Issues/issues/2896

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd Maps 5419, released 29.06.26

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [x] 1. Other points are selected when tapping the **Auto-select nearest points** button.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/1eb75478-f60b-4789-ab92-0aedd133d9b4"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/6bda52dc-3ec0-4572-8e18-3edbe9e42dce"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/38ec3bfa-0ab6-4f90-8a27-84658df0e228"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] File reading speed is slower than on a mid-range Android device.  This was tested on the TET Sweden track with a file size of 10MB.
* * **Google Pixel 6A** ~ 10 sec
* * **iPhone 16 Pro Max**  ~ 20 sec

- - - - - -
 
- [x] Replace statistics icons
	- [x] Set size to 20x20 pt
	- [x] Length – `ic_custom_length`
	- [x] Uphill – `ic_custom_uphill`
	- [x] Downhill – `ic_custom_downhill`
	- [x] Average speed – `ic_custom_speed_average`
	- [x] Max.speed – `ic_custom_speed_max`
	- [x] Duration – `ic_custom_time_span`
	- [x] Time in motion – `ic_custom_time_in_motion`

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2358bff0-9425-457c-8c63-4cc26d5d05fc"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Left/right paddings for separator, map and statistic should be the same.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd Maps 5425, released 10.07.26

**Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [ ] 1. The flickering of a dot that does not belong to a specific group is still present, though it is less noticeable than in Testing 1.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/f9a7c031-ed26-43fe-8fc9-9b8f1b967346"></video>
</details>
