### ISSUE TITLE
Bookmarks for Travel

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3186]
# ToDo

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/29724a74-1471-4454-8ee4-041be8fedb99"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ee72cbaf-bc26-44b7-a40c-77a411d98b5c"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x]  Add new tab, **Travel** to My Places 
- [x] Show all user bookmarks sort by Name 
- [x] Add context menu for long tap

**Comment by dmpr0** [comment]
# Review 
- [ ] Use `ic_tabbar_travel` for tab bar icon

**Comment by dmpr0** [comment]
# Review - 2

<details>
    <summary>Crash</summary>

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6ece3901-f622-4e28-84b5-139ab96338a4"  width="auto" height="auto"/> 
</details>  

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bad8658d-a5c7-47f9-bb88-0bd7adc5bdd2"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Crash, taping on Navigation in bookmarked article without file. Link to crash `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=hyz0akG9C8W-Y1yQeg1oF&bundleId=net.osmand.maps`
