### ISSUE TITLE
Add "Reset to default" action for plugin settings

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3187]
# Description 
Some plugins is missed Reset to default option:
* Weather 
* OpenStreetMap Editing
* Wikipedia
* Trip recording, align style with other

## ToDo
<details>
    <summary>Weather</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/93d79597-7c5e-461c-ab78-23ee73b41e9e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/90e5ad75-9197-4056-938d-deea70202eaa"  width="300" height="auto"/> </td>
  </tr>
</table>    
</details> 

<details>
    <summary>OpenStreetMap Editing</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d881bd81-9f06-4b16-9a37-c98f4d15fd8f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6146895a-b3d6-457a-b8be-bed1b157d1f7"  width="300" height="auto"/> </td>
  </tr>
</table>    
</details> 

<details>
    <summary>Trip recording</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3dab60bf-0c2b-47b9-ac3f-49c36581f663"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7c16a36b-df8a-421d-95e3-cb3781ea22c3"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

<details>
    <summary>Wikipedia</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bd5afc16-1530-400d-b5de-4b9b1d7da9bb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/90cc3ddb-f0ec-4a13-8fe9-ac7d91d2324b"  width="300" height="auto"/> </td>
  </tr>
</table>    
</details> 

- [x]  Add **Reset to default** action to NavBar, icon `ic_navbar_reset`
- [x] Show confirmation action sheet on tap
- [x]  Plugin settings for active profile should be reseted to default

**Comment by dmpr0** [comment]
# Review
- [ ] It doesn't seem to work

**Comment by dmpr0** [comment]
# Review 2 

> Tested on build from master at 13.11.23, 16:00

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6355b8d0-61e1-4fe9-aa2b-eeebd9cf3348"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  




- [ ] Reset doesn't work for Wikipedia plugin
