### ISSUE TITLE
Dark theme for splash screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3232]
## Description 
After adding Dark theme, OsmAnd can be set to it allways, but splash screen doesn't change background color depends on theme.

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>OsmAnd Maps</th>
        <th>Maps+</th>
        <th>OsmAnd Pro</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ce35cd5d-2ea5-407d-a4b0-70365952ba94"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7c724474-4acd-42bf-b4e4-1d1e46b8df6a"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/73651cd0-9a0a-4cad-a529-0f7c3b3b1f3e"  width="300" height="auto"/> </td>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/17fba4eb-8361-456b-a78f-6453c6f89512"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/48ca2998-5dfb-41ad-a7fa-9bfbe23d2001"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3d626889-51a2-4f8a-ad13-641cc849767a"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

## ToDo
- [x] Use system setting for theme to set dark or light splash screen.
- [x] Background color – `launchScreenBgColor`

**App name** 
We need to show app name depends on purchased in-app:
- [x] Without in-app – `img_text_osmand_maps`
- [x] **Maps +** – `img_text_osmand_maps_plus `
- [x] **OsmAnd Pro** – `img_text_osmand_maps_pro`
- [x] Powered by OSM – `img_text_openstreetmap`

- - -

- [x] Remove old unused resources from https://github.com/osmandapp/OsmAnd-iOS/tree/master/Resources/IntroImages

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3314
