### ISSUE TITLE
Show recorded data from sensors on graph

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3293]
## Description
Show data from sensors on Analyse on map screen for GPX tracks.
* Android task https://github.com/osmandapp/OsmAnd/issues/17201
* Colors https://github.com/osmandapp/OsmAnd-Issues/issues/2309

## ToDo
Allow to select 2nd axis on Analyze Map

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Analyze</th>
        <th>Select graph</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cee1cebe-ee6c-44a0-80f3-6dcd68179466"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0ece8dd0-9ff6-456c-ba5b-2c4a2d37a2c5"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Heart rate
- [x]  Show **Heart rate** if present
- [x] Icon – `ic_custom_sensor_heart_rate_outlined`
- [x] Values color - `chartTextColorHeartRate`
- [x]  Graph line color – `chartLineColorHeartRate`

### Speed Sensor
- [x] Show **Speed Sensor**  if present
- [x] icon – `ic_custom_sensor_speed_outlined`
- [x] Values color – `chartTextColorSpeedSensor`
- [x]  Graph line color – `chartLineColorSpeedSensor`

### Cadence
- [x] Show **Cadence** if present
- [x] Icon – `ic_custom_sensor_cadence_outlined`
- [x] Values color – `chartTextColorBicycleCadence`
- [x] Graph line color – `chartLineColorBicycleCadence`

### Bicycle Power
- [x] Show **Bicycle Power** if present
- [x] Icon – `ic_custom_sensor_bicycle_power_outlined`
- [x] Values color – `chartTextColorBicyclePower`
- [x] Graph color – `chartLineColorBicyclePower`

### Temperature
- [x] Show **Temperature** if present
- [x] Icon  – `ic_custom_sensor_thermometer`
- [x] Values color – `chartTextColorTemperature`
- [x]  Graph line color – `chartLineColorTemperature`
