### ISSUE TITLE
Change default values for widget navigation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3311]
## ToDo

New default values for listed options should be:

**Pedestrian**
- [x] **Snap to road** = `true`
- [x] Add **Second next turn** widget to  Widgets > Left panel
- [x]  **Map orientation** = `Movement direction`

**All profiles**
- [x]  **Transparent widgets** – `Off`
- [x] **3D Mode** – `Visible`
