### ISSUE TITLE
Add "Open track" button to Waypoints context menu 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3350]
## ToDo
Add **Open track** button to context menu of track Waypoint to easy go back to parent track.

<table style="width:100%">
  <tr>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e5d1dfa6-801c-4b8d-bff5-4ecaa59b9dfa"  width="300" height="auto"/> </td>
  </tr>
</table> 

<details>
    <summary>Android</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f1210140-3361-48dd-bd53-d1517149cb4b"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Add **Open track** button for context menu of Waypoint.
- - [x] Tap should open track context menu.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3446

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d6a6961f-faa1-4c5a-b054-63fbed5cb9c8"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a0c6d608-b957-4dee-bcee-6007ecdc7c99"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Close first context menu when open next one. Track context menu shows above Waypoint context menu.

**Comment by dmpr0** [comment]
# Review 2 

<table style="width:100%">
  <tr>
    <th>Android (Release version)</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/479643b7-ee2e-4044-a2d4-17512cbe2bae"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3609d3af-85cb-4146-a032-3387be06996f"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Works to slow

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3479

**Comment by dmpr0** [comment]
To slow

**Comment by alex-osm** [comment]
Fix slow track menu opening - https://github.com/osmandapp/OsmAnd-iOS/commit/915483d0f841dba289f72891fcc925296f10575c
