### ISSUE TITLE
Add support for additional tags for OSM routes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3370]
## Description 
We need to show additional tags for OSM route: `description`, `from`, `to`, `distance`, `direction`, `state`, `colour`, `ascent`, `descent`, `roundtrip`, `tourism`

Routes to test:
* https://www.openstreetmap.org/relation/16115660
* https://www.openstreetmap.org/relation/110309
* https://www.openstreetmap.org/relation/11685878
> Android task https://github.com/osmandapp/OsmAnd/issues/18611

## ToDo
Show tags for OSM routes in **Route info** card.

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6503b124-10cb-4766-9f56-734fc1bd4dff"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] `description`
- [x] `from`
- [x]  `to`
- [x]  `distance` 
- - [x] if units not specified, show `km`, example route https://www.openstreetmap.org/relation/6946425#map=15/52.1393/5.2710
- [x] `ascent` if units not specified, show `m` 
- [x] `descent`  if units not specified, show `m`
- [x] `direction` show units 
- [x] `colour`
