### ISSUE TITLE
Add ability to open Wikivoyage article from the track

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3388]
## Description 
Currently there is no button to go back to article from track with points that was generated from this article.

## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2cc72a62-63e6-4963-9628-dbdedcb0386d"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/045964ab-e101-4d43-bb2f-56405dde7f20"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Wikivoyage group
- [x] Show Wikivoyage article as separate group in track context menu
- [x] Show article preview similar to bookmarked Wikivoyage article 
- [x] Tap **Read** should open article
- - [x] Should work the same as in My Places > Travel
- - [x] Should work without downloaded Wikivoyage file
- [x] Don't show Wikivoyage article as Description
