### ISSUE TITLE
Sun position – Widget 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3394]
## Description 
Combined Sunrise / Sunset widget, that can show next event (sunrise on sunset) or Sunrise / Sunset.

> Android task https://github.com/osmandapp/OsmAnd/issues/18559

# ToDo

## Widget group, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1210-34639&mode=dev)

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/27f14307-cfe2-48e0-bd28-c03c477ce112"  width="360" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Rename widget group `Sunrise, sunset` to `Sun position`
- [x] Add new widget `Sun position`
- - [x] Icon – `widget_sunset`

## Widget settings, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1210-37409&mode=dev)

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Settings</th>
    <th>Mode</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/29e6a877-85b3-4fa8-9cd8-b4c887234211"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/040820c5-51d3-4417-8a33-72465c3b15d2"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

### Mode, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1210-39268&mode=dev)

Allows to choose one on three modes:

- [x] **Next event**, show time left to sunset after sunrise, show time left to sunrise after sunset.
- [x] **Sunrise**, show sunrise time depends on selected Format.
- [x] **Sunset** , show sunset time depends on selected Format.

### Format, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1210-39464&mode=dev)
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Next event</th>
    <th>Sunrise</th>
    <th>Sunset</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f481c671-dd29-4189-8f17-09d8592f0922"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d02c8009-1829-433b-9828-6cef97815c99"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/461a16a1-34e0-42cf-945f-daee2caeaf10"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

Allows to select time format between, depend on selected mode
- - [x] **Time left**
- - [x] **Next sunrise**
- - [x] **Next sunset**
- - [x] **Next event**

### Widget on the list

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/40c5370f-dfda-40ce-8792-178b1725d60f"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Name should include selected mode.

### Widget on the map screen
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>After sunrise</th>
    <th>After sunset</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8574cca8-e0e3-4261-b3c4-9dc95b28c625"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5d4188f2-f55a-410a-8aeb-e1d47854558e"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Should be available in all layouts on all panels
