### ISSUE TITLE
Sort Subfolders – Tracks

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3415]
## Description 
Add action that will allow to sort all folders and tracks in the present folder.

> Android task https://github.com/osmandapp/OsmAnd/issues/17467

# ToDo
<table style="width:100%">
  <tr>
    <th>Folder menu</th>
    <th>Sorting menu</th>
    <th>Toast message</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6fd29bcd-102d-4c30-9312-c7d49d23ec5e"  width="300" height="auto"></td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e6724410-bb98-4bc7-b54c-9fcaa83208f9"  width="300" height="auto"></td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6685168c-0627-47e7-b128-697cec4fa475"  width="300" height="auto"></td>
  </tr>
</table>  

&nbsp; 

### Open folder menu
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/28733457-a378-4db2-a267-6be163433654"  width="auto" height="auto"/> </td>
  </tr>
</table>   
Context menu available as action on NavBar for open folder.

&nbsp; 

- [x] Add action **Sort subfolders**
- - [x] Add Icon if possible – `ic_custom_sort_subfolder`
- - [x] Tap – open **Sort by** context menu.

### Sort by
- [x] Parent folder sorting option should be highlighted by default.
- [x] Apply selecting sorting order to all levels of subfolder and tracks.

### Confirmation
- [x] Show toast after sorting:
- - [x] Text `Subfolders in “FOLDER NAME” is sorted by: “SORTING ORDER NAME”`, example `Subfolders in “Summer 2021” is sorted by: “Name A – Z”`

**Comment by tigrim** [comment]
Technical Plan:

- Technical Details:

1) Work with the class TracksViewController.
2) Function setupNavBarMenuButton.

3) To display a toast, use:
   OAUtilities.showToast(text, details: nil, duration: 4, in: view)

4) Example of implementing a nested menu:

```swift
buttonView.isUserInteractionEnabled = true
let interaction = UIContextMenuInteraction(delegate: self)
buttonView.addInteraction(interaction)

extension ViewController: UIContextMenuInteractionDelegate {
    func contextMenuInteraction(_ interaction: UIContextMenuInteraction, configurationForMenuAtLocation location: CGPoint) -> UIContextMenuConfiguration? {
        let configuration = UIContextMenuConfiguration(identifier: nil, previewProvider: nil) { actions -> UIMenu? in
            // Creating Save button
            let save = UIAction(title: "Save", image: UIImage(systemName: "tray.and.arrow.down.fill")) { action in
                // Just showing some alert
                // self.showAlert(title: action.title)
            }

            // Creating Rotate button
            let rotate = UIAction(title: "Rotate", image: UIImage(systemName: "arrow.counterclockwise")) { action in
                // self.showAlert(title: action.title)
            }
            // Creating Delete button
            let delete = UIAction(title: "Delete", image: UIImage(systemName: "trash.fill")) { action in
                // self.showAlert(title: action.title)
            }
            // Creating Edit, which will open Submenu
            let edit = UIMenu(title: "Edit...", children: [rotate, delete])

            // Creating main context menu
            return UIMenu(title: "Menu", children: [save, edit])
        }
        return configuration
    }
}
```

Testing:

- Conduct testing to verify the correctness of sorting and displaying toast messages.
- Ensure that sorting is correctly applied to all folders and tracks at all levels of nesting.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3940

**Comment by DmitrySvetlichny** [comment]
I spent 8 hours building the project due to issues that arose after adding the Kotlin library.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4125

**Comment by Zirochkabila** [comment]
# Sort subfolder problem
`4.9.0.8`


https://github.com/user-attachments/assets/92a998a5-93e1-4878-8bb6-b9e385714c45

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/web/commit/bab791c96e905c239363981e9c91a07a942f3dc7
