### ISSUE TITLE
Selection mode – Tracks

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3434]
## ToDo
Add selection mode for My Places – Tracks https://github.com/osmandapp/OsmAnd-Issues/issues/1914

## Tracks

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a602ce23-0b58-4e54-9cb9-6964a7f3199f"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new option **Select** to the NavBar menu
- - [x] Icon – `ic_custom_select_outlined`
- - [x] Tap should open Selection mode
- [x] Should be present on all Tracks sub screens

## Selection mode
<table style="width:100%">
  <tr>
    <th>Selection mode</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4b994f50-37d3-4582-a564-b7aa54253100"  width="230" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5997e563-321c-486f-b184-5249653a877c"  width="230" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/dd57b2cf-b511-4595-9e5e-60d052462a89"  width="230" height="auto"/> </td>
  </tr>
</table>  
![Menu]()

- [x] Should show content of the current screen
- [x] Add checkbox to the left side of each item
- [x] Add toolbar with Select all / Deselect all aciton

#### NavBar
- [x] Show quantity of selected items: (folders and tracks visible on the screen) and quantity of selected tracks from all subfolders.
- [x] Add **Cancel** button, tap should close the view
- [x] Add Menu button

**Actions**

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c602f451-6784-4420-a18a-c103f8ef9231"  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Show on map
- - [x] Icon – `ic_custom_map_pin_outlined`
- - [x] Action – turn on visibility of the selected tracks on the map, close the view
- [x] Export
- - [x] Icon – `ic_custom_export_outlined`
- - [x] Action – open Export view with preselected files
- [x] Upload to OSM
- - [x] Icon – `ic_custom_upload_to_openstreetmap_outlined`
- - [x] Action – open Upload to OpenStreetMap view for selected GPX files.
- [ ] Move
- - [ ] Icon – `ic_custom_folder_move_outlined`
- - [ ] Action – open Move folder view
- [x] Delete
- - [x] Icon – `ic_custom_trash_outlined`
- - [x] Action – show confirmation alert, after confirm delete selected folder and files.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3777

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ccc7e297-1c7d-45bd-bece-62c140a928a7"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Wrong calculation of selected tracks in NavBar

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3788

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1cc93f6a-2bea-46d0-92cc-d025cdeb158c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/374e7187-8c0f-42b1-8a5a-adf15a1eb219"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Disable pull to refresh for Selection mode

**Comment by dmpr0** [comment]
# Review 3
- [ ] Hide right side action for tabelCell (chevron)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3848

**Comment by vshcherb** [comment]
http://localhost:3000/docs/user/personal/tracks/manage-tracks#selection-mode
