### ISSUE TITLE
Round up numbers in navigation widgets 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3463]
## ToDo UI

> Android task https://github.com/osmandapp/OsmAnd/issues/18762

## Functionality
* Add option to round up numbers in navigation widgets (lanes, next turns, next intermediate, target point, tunnel alerts). 

### General settings
<details>
    <summary>General settings</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bd5774f3-bb2e-422f-92fc-fc7ae5c15f0c"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details> 

- [x] Add new item **Distance during navigation**, with two options:
- - [x] Precise, icon – `ic_custom_distance_number_precise`
- - [x] Round up, icon – `ic_custom_distance_number_rounded`
- [x] Tap on **Distance during navigation**, open new screen 

### Modal view, [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?type=design&node-id=2862-8887&mode=dev)
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Precise</th>
        <th>Round up</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/198575c1-8866-4eeb-af93-6cf3f26c755c"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3d0b9918-436c-476c-89f7-73b447bb4cc1"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Title – `Distance during navigation`
- [x] Add **Cancel** button. Tap should close the dialog 
- [x] Add description to the group footer – `Choose how distance information is displayed in navigation widgets (distance to point, next turn, lanes).  Choose “Precise” for exact numbers, or “Round up” for easier readability.`
- [x] Use radio button to switch between options
- [x] Add preview frame with icon corresponding to selected option, icon should be scaled to 90x90 dp.
- [x] Tap open unselected item, should make it selected and close the bottom sheet

## CarPlay
- [x] Should apply to CarPlay

**Comment by vshcherb** [comment]
Technical notes:
```
Algorithms
public static int lowerTo10BaseRoundingBounds(int num, int[] roundRange) {
public static int[] generate10BaseRoundingBounds(int max, int multCoef) {

```

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3513
