### ISSUE TITLE
Exit number and circle from roundabout turn arrow isn't visible in Dark mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3490]
## Description
Circle part of roundabout asset isn't visible in Dark mode.

### How to reproduce
* Calculate route from `52.23996 4.50341` to `52.23599 4.50283`
* Turn on Simulation

### Actual result

<table style="width:100%">
  <tr>
    <th>Light</th>
    <th>Dark</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b8fc9b11-d431-4f49-8106-2055b584101f"  width="414" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/27207484-ce4a-4484-93f6-9c19a2e707fe"  width="414" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* Whole icon is fully visible

## ToDo
We need to start using colors from assets for navigation arrows,  currently the defined in [OAColors.h](https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/Constants/OAColors.h#L17)
- [x] Use `navArrowColor` from assets, instead of `color_nav_arrow`
- [x] Use `navArrowDistantColor` from assets, instead of `color_nav_arrow_distant`
- [x] Use `navArrowImminentColor` from assets, instead of  `color_nav_arrow_imminent`
- [x] Stroke, use `navArrowStrokeColor` for stroke outisde arrow and circle
- [x] Exit number, use `widgetValueColor`

**Circle**

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ed56f005-9b82-4bf3-aa7a-a84037b01713"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e5d93699-315a-428b-b259-37946bb05e50"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Fill circle shape, use color `navArrowCircleColor`

**Environment**
OsmAnd Version: 4.7.2.6
iOS version: 17.3
Device model: XS Max

**Comment by dmpr0** [comment]
# Review

> Tested on TestFlight 4.7.3.1

- [ ] Crashed first time

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src=""  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src=""  width="300" height="auto"/> </td>
        <td><video src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Roundabout turn arrows is missed with Next turn widget

**Comment by dmpr0** [comment]
Done
