### ISSUE TITLE
Unable to change "Wheel circumference"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3503]
## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cb296a20-ae89-4e35-b6e2-ef18cbf36e1d"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Open dialog after tap on **Wheel circumference** cell
- [x] Settings should be saved for each sensor individually

### Wheel circumference view
- [x] Open with active keyboard
- [x] Show input field
- [x] Always use **Millimetres**

**Comment by DmitryAlexei** [comment]
- change millimeters to mm (?)
- round to 2500.0 > 2500
