### ISSUE TITLE
Analyze tab – Plan a route

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#3527]
# Tasks

> * Android tasks – https://github.com/osmandapp/OsmAnd/issues/18872
> * Related duplicate - #3682

**Related:**
1. #1323
2. #3527
3. #5668
4. #5609

# ToDo, [Figma](https://www.figma.com/design/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=1805-55067&m=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/70a53e42-5a63-4c33-ab63-90ee74568c1a"  width="200" height="auto"/> </td>
  </tr>
</table>   

The overall layout will be similar to the Route Details screen but with some minor redesigns to certain elements. 

- [x] **Overview**
- [x] **Overview statistic** 
- [x] **Road types**
- [x] **Steepness**
- [x]  **Surface**
- [x] **Smoothness**

### Overview

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/573753b4-e81b-4b27-b444-1f20bced8b68"  width="300" height="auto"/> </td>
  </tr>
</table>   

This UI element is similar the one we user in Route details, but we need to redesign Axis selection buttons.

- [x] Show graph for the selected axis

**Axis selection buttons**:

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/05163a17-b41a-45fc-bf95-c6bc96be83a4"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Background color – **cellButtonBg**
- [x] Corner radius – 
- [x] Show popover symbol on the right side `chevron.up.chevron.down`

**Action**
- [x] **Recalculate elevation** – should launch **Get elevation data** bottom sheet.

### Overview statistic

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/6de798d5-4962-44ce-b8f0-3d12db14efc2"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Display a 3x2 native data grid containing
- [x] Row 1: **Uphill**, **Downhill**, **Alt. range**
- [x] Row 2: **Avg. speed**, **Max. speed**, **Time in motion**
- [x] Show `–` if data is missing. For example for planned routes Time in motion, and Speed will be missed.
- [x] Data text size – `footnote`
	- [x] Value text color – `textColorActive`
	- [x] Data field name text color – `textColorSecondary`

### Road types / Steepness / Surface / Smoothness

<table style="width:100%">
  <tr>
    <th>Collapsed</th>
    <th>Open</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a827328c-fa24-4fa0-8f8a-5d62d17669df"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/9f369c13-f57c-4579-a6e5-ef61e8d8955b"  width="300" height="auto"/> </td>
  </tr>
</table>   

**Collapsed State (Default):**
- [x] Header with trailing chevron icon (>).
- [x] Horizontal graph (Previous version of it is used in Route details)
- [x] Compact inline legend with color dots and category labels below the bar.

**Open state**

- [x] Show the same horizontal graph
- [x] detailed legend for the graph

## Empty state, [Figma](https://www.figma.com/design/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?node-id=1805-68423&m=dev)

<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Bottom sheet</th>
    <th>Calculation</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/600b7123-b3ab-4573-b34e-c4a42d7a9d88"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/09cd6dbf-e515-4481-84f4-20b7416f798c"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f3f1be38-1dc4-4854-a270-e4bc03c6b2d6"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Show if track doesn't have any data to show
- [x] Title – `No elevation data`
- [x] Description – `OsmAnd can retrieve elevation data from nearby roads or terrain maps.`
- [x] Action – **Get elevation data**
	- [x] Show **Get elevation data** bottom sheet on tap

### Get elevation data

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/08e9b2c5-2bbd-4b1e-8e25-810c76cd0b24"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title – `Get elevation data`
- [x] Description – `Select a method to calculate elevation using data from offline maps or terrain maps.`

**Actions:**
- [x] **Use nearby roads**
	- [x] Icon – `ic_custom_attach_track`
	- [x] Second line – `May adjust track geometry`
- [x] **Use Terrain maps**
	- [x] Icon – `ic_custom_terrain`
	- [x] Second line – `Track geometry stays unchanged`
- [x] Tap on action should trigger elevaton calculation using one of the selected method

### Calculating elevation...

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f99e5d72-d13d-47d8-86f0-ce07e81bc2f1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ee39d40f-0fed-4272-b052-81fdbfa559c1"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show while calculating 
- [x] Description, depend on selected method:
	- [x] For **Use nearby roads** – `Adjusting track to nearby roads to retrieve altitude data.`
	- [x] For **Use Terrain maps** – `Retrieving altitude data from terrain maps.`
- [x] Action – **Cancel**
	- [x] Should stop elevation calculation

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd Maps 5436, released 04.08.26

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. The animation jerks when the last two stops on the route are opened.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/5bda1f8b-43c5-4785-85f8-f801048a731d"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0f4a4d00-b1f5-4211-80f4-ccaf2f8138c9"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/8e1cf57d-bab9-41fb-b4a7-21147c810016"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Calculation elevation is falsely showing for Straight line profile. **No elevation data** - empty state should be shown

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/89df7a2b-ba4a-4c08-8eac-d972b957cc4d"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/85db2abe-ac12-42dc-a553-3394bda918e0"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Show **Attach to the roads** dialog after taping on **Use nearby roads**

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/41672efe-b46c-4701-b27f-2c4b19788fc2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

**Small preview**
- [x] Circle size – 16x16 pt
- [x] Text size - footnote 13 pt

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/fc99a9c7-9ec0-4760-a185-abebb75092f7"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/0ba557d5-5a95-4a5e-899a-9ef277cb5908"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Add stroke around to bright colors, we have similar in Android for Color component, make this here and we will transfer it to Color component too.

## Accessibility

### Stats block

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/528d2981-520d-4d49-86c0-3cd58f5d1cc4"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Make each stat cell a single accessibility element:
```
isAccessibilityElement = true
accessibilityLabel = caption ("Підйом")
accessibilityValue = formatted measurement
```

- - - - - -

- [x] `—` dash, set `accessibilityValue = NSLocalizedString("shared_string_not_available")`

- - - - - -
 
- [x] Don't reuse the visual string for accessibility. Build a separate value with MeasurementFormatter:
```
unitStyle = .long
unitOptions = .providedUnit
locale = Locale.current
numberFormatter.maximumFractionDigits = 0
```
This gives correct Ukrainian plural forms (1 метр / 2 метри / 15 метрів). Do not concatenate manually — use .stringsdict if a manual path is unavoidable.


### Attributes block

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/98c446fc-e114-4f5d-a10d-0369185bc35b"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Unable to select each row separately 

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0d2ba19c-740d-4871-9a10-ba532c95e4af"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Show PRO button on **Use Terrain maps** item for user without OsmAnd Pro
- [x] Tap on **Use Terrain maps** in this case should open Choose Plan – Terrain maps item

**Comment by dmpr0** [comment]
## UI Review


<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Plan a Route</th>
    <th>Track context menu</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5869d470-43d7-4d02-9c0e-0b9c0c4f33a4"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/0341e0a4-1ce0-4cfb-93c3-d197c8fa7556"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f9d84b8e-366b-46c1-8c97-bd4b7404ea00"  width="300" height="auto"/> </td>
  </tr>
</table>  

</details>  



- [x] Elevation data should be present

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd Maps 5443, released 13.08.26

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. The **Get elevation data** window opens when tapping on the description.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/7e6366c1-2c29-4b3a-a4c4-fa5c1ec3679d"></video>
</details>

* [ ] 2. Show the **Attach to the roads** dialog after tapping **Use nearby roads**.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/ae59abbd-420f-4b07-95e6-b17993dafd15"></video>
</details>

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. When opening the **Get elevation data** window and closing **Plan a route** without saving changes, the **Save** button turns dark.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/03371d65-7fa5-49c9-bd90-febed88f7564" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/bf272b2c-744f-439b-80d8-126d8a48328b" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [ ] 2. After collapsing the information about the last item, the information in the entire window jumps.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/b60f8171-2ce9-4952-aedd-b7d432f968f7"></video>
</details>

* [ ] 3. The text in the **Get elevation data** window is not adjusted to fit the screen size in landscape orientation.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/42256684-32ac-404c-b35a-4ef5beadba35"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

* http://github.com/osmandapp/OsmAnd-iOS/issues/5669
