### ISSUE TITLE
Total track statistic in folder footer

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3533]
## Description

> Android task https://github.com/osmandapp/OsmAnd/issues/14673

## ToDo
Add total track stars below list of tracks in all subfolders.

`Tracks – 4, distance – 246.6 km, uphill – 325 m, downhill – 456 m, duration – 08:50:35, size – 14 MB.`
- [x]  Tracks quantity in folder
- [x] Total sum of distance
- [x] Total sum of uphill
- [x] Total sum of downhill
- [x] Total sum of duration
- [x] Total size in MB

<table style="width:100%">
  <tr>  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3e418b9d-2b5f-4828-a3fa-ed8ebb07b215"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3944

**Comment by tigrim** [comment]
When using OsmAndShared in Objective-C files, to access class methods and properties, you need to use the import statement:

```objc
#import <OsmAndShared/OsmAndShared.h>

OASGpxFile *gpxFileKotlin = [KSharedUtil loadGpx:@""];
NSLog(@"%@", gpxFileKotlin.author);
``````
However, during compilation, we encounter an error as shown in the image:

![Image](https://github.com/user-attachments/assets/b7bd474f-18de-468e-a527-ebeb6ccadc66)

The assumption is that in `build.gradle.kts` for `iosMain.dependencies`, an alternative to `implementation("com.squareup.okio:okio:$okioVersion")` should be used, as they are not compatible.

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/f4c1525e-fe7a-4200-891f-a58479844297"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Missed on Tracks (Main folder)

**Comment by Skalii** [comment]
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/20686417-172f-47b2-bff3-af48218f7ad4" width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] open hiking gpx

**Comment by DmitryAlexei** [comment]
Only bugs related to the total track statistic issue are left in this task.
Other bugs are transferred into a new issue - https://github.com/osmandapp/OsmAnd-Issues/issues/2764

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4101

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4102

**Comment by DmitrySvetlichny** [comment]
The primary issue under the item "Different stats" is that the values of diffElevationUp and diffElevationDown differ for segmented tracks, depending on how GpxTrackAnalysis is initialized. When initialized with getGeneralSegment, the values differ from initialization per each segment (https://github.com/osmandapp/OsmAnd-iOS/pull/4102/files). Initializing per each segment yields results that match the information in getFolderAnalysis. However, it does not record information in totalDistanceWithoutGaps, which is used in the UI to display the total distance for segmented tracks.

**Comment by DmitrySvetlichny** [comment]
Fixes did not solve the problem "Different stats. Only one track in folder. Track EuroVelo 6 - developed 2.gpx.zip"

**Comment by vshcherb** [comment]
For testing:
- [x] Fixes for distance for join segments done in master 
- [ ] Difference uphill / downhill (present in Android for track EuroVelo6) - separate issue should be created. On graph 10  430 m, 10 507 m (in overview and in My places). Join segments doesn't update screen for uphill downhill. iOS has same issue.
- [ ] iOS doesn't have switch on / off join segments - separate task
- [ ] Test that track with join segments on parameter is transferred from Android to iOS via Track export

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/21767

**Comment by Zirochkabila** [comment]
# Test 1
`4.9.5.4953` - Velo6 still present

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.5.4960`

3. iOS doesn't have switch on / off join segments - **It does, but it is located elsewhere.**
Should I leave it as it is or create a task to transfer the function (to the same place as in Android)? @vshcherb 

<details><summary>Switch</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/537123ad-edcc-4826-9181-938eadcf4542"  width="700" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d5057130-a395-410a-8789-c3458a4e8d30"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

_________

4. Test that track with join segments on parameter is transferred from Android to iOS via Track export - [4341](https://github.com/osmandapp/OsmAnd-iOS/issues/4341)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/e15021351aadbf0a697746d3a815d9660ed9b029
