### ISSUE TITLE
Group `name` tag for Routes and POI's

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3554]
## Description 

<details>
    <summary>Current</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c3618f30-6a9a-435e-898e-3ae01458e586"  width="180" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f7196b1d-db31-4a36-aa71-9f2b20d1f570"  width="180" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Example https://www.openstreetmap.org/relation/51855

## ToDo

<table style="width:100%">
  <tr>
    <th>Route menu</th>
    <th>POI menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a8c93ac5-192d-4de1-ad7c-f51cf8f3519d"  width="180" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d13425fa-13a8-4b20-b989-5ddd1314a4d9"  width="180" height="auto"/> </td>
  </tr>
</table>   

- [x] Add **Name** item to **Route info** card.
- [x] Group all name tags in POI context meny, by one filed **Name**
- [x] Show only if data is present, tags: `int_name` , `nat_name`, `reg_name`, `loc_name`, `old_name`, `alt_name`, `short_name`, `official_name`
- [x] Tap on item should open new View with grouped list of names

### Name view

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/19a2bb31-0cda-47eb-a5c2-376dfefb8f55"  width="180" height="auto"/> </td>
  </tr>
</table>   

- [x] Show data for all tags, divided by groups, group = tag
- [x] Show language on the second line

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3786

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/88737802-4e9c-4cbb-abc9-a99279076c98"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/f7fab566-76bf-41f0-a9e2-afa1e4b63391"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   



- [ ] Missed name tag for Antalya https://www.openstreetmap.org/node/428039517

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3867
