### ISSUE TITLE
Use Relation ID as name if it's missing for OSM Route

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3586]
## Description
We need to use relation id instead of the name for routes that missing names and add link to OSM in route context menu.

> Android / Core task https://github.com/osmandapp/OsmAnd/issues/14938

## ToDo
* Example routes – https://www.openstreetmap.org/relation/51855

### Route name
- [x] Use relation ID as route name for routes with missing names

### Route info

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ac814039-9dd0-4394-bdeb-02d9c40041e7"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new item `OSM ID`
- [x] Show ID as value – `51855`
- - [x] Tap on ID should open relation on OSM `https://www.openstreetmap.org/relation/51855`
- [x] Show only if OpenStreetMap plugin is On

**Comment by vshcherb** [comment]
Section Route Info could have screenshot (https://docs.osmand.net/docs/user/map/tracks-on-map#save-as-a-track). Route info is related to OSM tags - it should be clarified.

**Comment by shurasmiling** [comment]
[Routes on map](https://osmand.net/docs/user/map/tracks-on-map/tracks-types#routes-on-map)
