### ISSUE TITLE
Change / Default appearance for selected tracks - iOS

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3687]
## ToDo
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d5949f82-9227-45e2-99f3-d020d7f5fa9a"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/0c7d8362-c4a4-4661-a4a7-4fc9fbbcab4e"  width="150" height="auto"/> </td>
   <td><img src="https://github.com/user-attachments/assets/6176c43c-87d8-4034-b5eb-b9231a3abe16"  width="150" height="auto"/> </td>
  </tr>
</table>   

## Selection mode

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/37b36b92-27b4-4ef6-8906-6bd608d3b306"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new parameter **Change appearance**
- - [x] Icon – `ic_custom_appearance_outlined`
- - [x]  Tap should open Change appearance screen

### Original vs Unchanged 
>**Original** option value is stored in the track file; OsmAnd doesn't rewrite it, and it can be used after resetting appearance to its original state.

>**Unchanged** means the state of the parameter while group appearance editing. Parameters (for example color) would not be changed during the current editing session.  

**Description**
- [x] **Original** – Each track will retain its original parameters.
- [x] **Unchanged** – Each track will retain its own parameters.

### Switch

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/33285c34-53dc-4fc1-a874-35f1fb92c373"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c7b4ba4d-7f7a-45ec-a2b9-5033f72439b9"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Applied for parameters with On/Off switch
- [x] Applied for 
- - [x] **Direction arrows**
- - [x] **Show start and finish icons**
- [x] Change switch to popup button with 4 actions: 
- - [x] **Unchanged** – 
- - [x] **Original** – 
- - [x] **On** – turn on parameter for all tracks
- - [x] **Off** – turn off parameter for all tracks

### Color

<table style="width:100%">
  <tr>
    <th>Menu</th>
    <th>Original</th>
    <th>Unchanged</th>
    <th>Solid color</th>
    <th>Speed</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/622fae46-7448-4451-908c-d572ccdd2a6e"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/82441b84-0728-4c6d-adc5-e251b668ddd8"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/dd1a09c5-3de8-49b8-b322-802e319c06cb"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e98f8086-2c7e-4aca-9958-556fcd0e78f3"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/bda46749-4c4d-436e-b53a-35b8b8c266f9"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Show menu with the list of all available types
- [x] **Unchanged**
- [x] **Original**
- [x] **Solid color**
- [x] List of all available color types
- [x] Show `ic_custom_pro_logo_outlined` for features available only for Pro users
 

### Width

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/dee275f3-c181-42e7-885d-4a1a42f58498"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7fd18afc-7aa2-4660-8cec-e115bc5220c2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1454435a-a8da-47c8-8b7b-be82b15fd202"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/b4ea1060-e452-49c5-8d59-a48ef1bbf866"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c168353d-1a67-4277-a1de-cb154159ab0c"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Unchanged**
- [x] **Original**
- [x] Show segment control after after selecting.
- - [x] **Thin**
- - [x] **Medium**
- - [x] **Bold**
- - [x] **Custom**

### Split interval

<table style="width:100%">
  <tr>
    <th>Menu</th>
    <th>Original</th>
    <th>None</th>
    <th>Time</th>
    <th>Distance</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d8fd1b17-2c76-45fc-809e-e59b7401c2d7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/fb41f056-f676-46f0-a0b1-6d6226233f10"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d8125f34-b2b9-4746-ae78-2d544d430eaf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/58f67bf4-8973-4ad6-94bf-81b59a44ca87"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f817ce0d-dd74-43ab-b339-d31d5fe97602"  width="300" height="auto"/> </td>
  </tr>
</table>  

- [x] **Unchanged**
- [x] **Original**
- [x] Show segment control after after selecting.
- - [x] **None**
- - [x] **Time**
- - [x] **Distance**

### Unsaved changes

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a58a86fd-f67f-4be3-a149-3437a5dc26fb"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show action sheet, if user make changes and tap on Cancel

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4386

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4389

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4429

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.5.5001`

### 🟠 Major

- [ ] **1. “Change appearance” item is displayed (but not clickable) even if no track is selected.** The “Change appearance” item is visible but not interactive when no track is selected, causing confusion as the user might expect this option to be functional.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/1a652b53-17cc-404e-90eb-cec31729ea9c"></video>
  </details>

- [ ] **2. The Unchanged and Original settings are not saved when you reopen the window.** The settings are not retained when the window is reopened, which can be frustrating for the user, as they might expect their previous settings to persist.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/4de1c346-b0ae-40ad-ba9a-c30154d86898"></video>
  </details>

---

### 🟡 Minor

- [ ] **1. Text in the description of the “Coloring” function differs from the actual result.** The description of the “Coloring” function does not match the actual result on-screen. This could confuse users, but it does not significantly impact functionality.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/b4a08168-3b85-45d7-8912-9adb607d179a"></video>
  </details>

- [ ] **2. “Change appearance” window closes after selecting a color from the “All colors” item.** After selecting a color in the “All colors” section, the window closes automatically, which might be inconvenient as the user may expect the option to make further adjustments.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/18cf6e1d-4a4e-4249-99a8-d7f39f491887"></video>
  </details>

- [ ] **3. Information about the need for a Pro subscription is displayed even after the subscription is renewed (logged in Cloud).** Even after the subscription is renewed and the user is logged in, the information about needing OsmAnd Pro still appears. This can cause confusion.

  <details><summary>Details</summary>
  <img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/6effb3ff-8ae3-48d8-8731-b5ed5b04e9c3">
  </details>

- [ ] **4. The “Pro” category colors do not apply if a single track is selected.** The “Pro” category colors are not applied when a single track is selected, limiting the user experience.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/d781eebf-ad69-4476-bd3c-ae64d535f212"></video>
  </details>

- [ ] **5. The test description of the “Width” function differs from the actual result.** The description of the “Width” function does not match the result displayed, which may confuse users.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/50a5aca8-e40a-40f5-9ea8-0ce69b67143e"></video>
  </details>

- [ ] **6. The “Split interval” selection window closes in the upper right corner + the actual description of the function differs from the one on the renders.** The “Split interval” window closes in the upper right corner, and the description does not match the one shown in the renders. This could cause confusion.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/43fe962f-f5b2-44ff-b610-ce7ce2bda8b7"></video>
  </details>

- [ ] **7. The time interval slider cannot be set to halfway.** Users are unable to set the time interval slider to the halfway position, which limits the customization options.

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/5006e8d4-15e3-4a24-b563-9fe09fd9ece6"></video>
  </details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/820da4af-1c4a-4f12-a1a5-302f8d99f072"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Use default padding from the from the popup button to the right side of the screen

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/tracks/manage-tracks#selection-mode
https://osmand.net/docs/user/map/tracks/appearance#change-appearance-for-multiple-tracks

**Comment by Zirochkabila** [comment]
# **Testing 2**
`5.0.0 (5006)`

## 🟠 Major
- [ ] **Selected color in "All colors" is not applied or shown as selected**  
- **Issue:** When selecting a color from the **All colors** section, the color:
  - is not visually marked as selected
  - is not applied to the track or item

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/56118591-26ee-4509-96f1-e39e387d7133"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review 2

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8b15d480-2b06-4349-97e4-ddb80e5ed07a"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] **TableCell** has different heights. Is this broken? Please check **Figma** and other screens.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4497

**Comment by dmpr0** [comment]
## UI Review

- [ ] Open Choose plan view after tap on Coloring types that available only for Pro subscribers.

**Comment by Zirochkabila** [comment]
# **Testing 4**
`5.0.2.5014`

## 🟡 Minor

- [ ] **1. Refreshing the color bar after selecting a color is still present**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/cd8425d8-3b11-44da-abaa-f7ecbe62a673"></video>
</details>

## 💡 Suggestion
@dmpr0  **Coloring types marked as subscription-only do not trigger any action.** **Proposal:** When tapping on the icon/text, show the "Subscriptions" screen to explain access better.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/a2ab3309-080c-47f0-80d6-24e1846e35f2"></video>
</details>

**Comment by dmpr0** [comment]
## Ui Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c5f22eee-32ea-46c7-be0f-931f39300e28"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Different height

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4540

**Comment by DmitrySvetlichny** [comment]
<img width="1437" alt="Image" src="https://github.com/user-attachments/assets/bbba7e21-21c0-49fa-8d9c-f45c1769bfb7" />

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4546

**Comment by Zirochkabila** [comment]
# **Testing 5**
`5.0.2.5018`

## 🚨 Critical

- [ ] **1. Spinner does not stop after opening the purchase page — app becomes blocked**
<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/50fff6ee-79f2-4a8b-8f50-7f2e3badf089"></video>
</details>

## 🟠 Major

- [ ] **1. All Colors page does not refresh after adding duplicate colors — refreshes only after re-login**
<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/89eb15d4-5dd3-4480-bc85-4c944addb5fb"></video>
</details>

- [ ] **2. Deleted colors reappear when reopening the All Colors page**
<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/fcaa7e19-9c79-4f47-a643-54c31bf3a1a8"></video>
</details>

## 🟡 Minor

- [ ] **1. The color bar blinks (refreshes) when opening Change Appearance**
<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/6c3fb31f-1fb2-40aa-b301-afcdece9a476"></video>
</details>

**Comment by nnngrach** [comment]
- [ ] UI bug with duplicate/delete color. Changes from AllColors screen don't appears on main screen
- [ ] UI bug with duplicate/delete pallete. Changes from AllPaleetes screen don't appears on main screen

- [ ] bug with deleting many items ant one

**Comment by Zirochkabila** [comment]
# Testing 7
`5.0.3.5021`

[May 07, 2025 14:13.log.zip](https://github.com/user-attachments/files/20083609/May.07.2025.14.13.log.zip)

- [ ] 1. Color removal crashes - sometimes it happens immediately, and sometimes it takes several steps (as in the video)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/fb1b7f4f-7e49-49b2-95b5-a72cdfa6c1a9"></video>
</details> 


- [ ] 2. It seems as if there is an invisible border that limits the display of duplicate colors until the window is reopened


<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/f6a12c1f-3fe8-4bd4-90d2-e07e66d87262"></video>
</deta


- [ ] 3. The page automatically returns to the previous page when changing a color that has a gradient

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/659e4d46-f2a9-4961-8ce6-f17ff0e83687"></video>
</deta

**Comment by Zirochkabila** [comment]
# **Testing 8**

`5.0.3.5022`

## 🟡 Minor

* [ ] **1. Strange animation during update to the width selection bar**
* Animation looks unusual or jumpy when the width value changes.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/71fd909b-ded8-494c-b9ec-8fdd0c9db673"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/71fd909b-ded8-494c-b9ec-8fdd0c9db673"></video>
</details>


- [ ] Strange animation during update to the width selection bar. Animation looks unusual or jumpy when the width value changes.

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/21fd5e92-b7e6-4f16-b220-8005dc8193c8"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Color is different?
