### ISSUE TITLE
Redesign elevation graphs

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3731]
## Description

> Part of the 
> 1. https://github.com/osmandapp/OsmAnd-iOS/issues/3731
> 2. https://github.com/osmandapp/OsmAnd-iOS/issues/3686
>
> Android task – https://github.com/osmandapp/OsmAnd/issues/18204

## ToDo
* We need new UI for graphs without overlapping labels

### Default presentation, [Figma](https://www.figma.com/design/2x4AwbISAr2rUvcH61ySiW/UI-Library-%5BiOS%5D?m=dev&node-id=1535-20265)
<table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/05fa462c-6846-4a5d-89b6-38d00446f9a9"  width="375" height="auto"/> </td>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4e14ff56-c262-49ef-b472-864199706516"  width="375" height="auto"/> </td>
      </tr>
    </table> 

- [x] Move Y-axis labels to the right side
- [x] Graphs should take all free space between paddings and Y-axis column
- [x] Add left and right paddings `16 pt`

- - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b714e799-d48d-4b8b-8f8c-3c963d935037"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Add vertical padding `6 pt` between chart and Y-axis labels.

- - -

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2c21a2a1-3b92-4fc8-b514-47ab90a98aae"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/bc43026a-79de-4cd4-8cc2-3fff5491d3e0"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Column with Y-axis label should have dynamic width
- [x] Labels should be placed below horizontal grid lines

- - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0989caca-1430-49a7-beb3-2efc7973c374"  width="300" height="auto"/> </td>
    <td valign=bottom><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/247ca051-610e-4d75-b182-4d49501420bb"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] We need to have ability to set different chart height on different screens

- - -

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f914418a-ae63-40e8-b025-08be7355e678"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [ ] Add option to show  X-Axis on graph (it will be used in Elevation widget)

**Comment by tigrim** [comment]
Technical Plan:
1) Remove all warnings from the GpxUIHelper class.
2) Check the library version for relevance. Use the latest version of the library.
3) Verify that the new version plots the graph correctly.
4) Android uses https://github.com/PhilJay/MPAndroidChart, the implementation is similar to what we use. Examine which methods are called there.

Key code parts:
- Library for charts we use: https://github.com/ChartsOrg/Charts
- `GpxUIHelper class`
- `@objc static public func setupGPXChart(chartView: LineChartView, yLabelsCount: Int, topOffset: CGFloat, bottomOffset: CGFloat, useGesturesAndScale: Bool)`

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Figma</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/48b073af-9f85-4f0b-80e9-da7e247305be"  width="400" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/c5c804fe-1095-40f5-9621-83afb09238f3"  width="400" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] X-Axis marks is missing

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Figma</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/48b073af-9f85-4f0b-80e9-da7e247305be"  width="400" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/c5c804fe-1095-40f5-9621-83afb09238f3"  width="400" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] X-Axis marks is missing

- - -

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2c71bd9e-d2e8-4abc-bf64-027f684f12c2"  width="500" height="auto"/> </td>
  </tr>
</table>   

</details>  

- [ ] Try to align text on one horizontal line 

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/7758c7c4-79fb-4a49-b77c-49d38b4e3999"  width="300" height="auto"/> </td>
      </tr>
    </table>

- [ ] Units are missing to Temperature

**Comment by DmitryAlexei** [comment]
Pin doesn't move on the map, when you use the Analyze on map option

https://github.com/user-attachments/assets/cc9b2390-813f-4798-b93d-ea5c76ad3762

**Comment by dmpr0** [comment]
<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2c71bd9e-d2e8-4abc-bf64-027f684f12c2"  width="500" height="auto"/> </td>
  </tr>
</table>   

</details>  

- [ ] Try to align text on one horizontal line

**Comment by DmitryAlexei** [comment]
4.8.5.2
Pin still doesn't move on the map when using Analyze on map option
- 47.78603 15.31554
- Bike and hiking routes are enabled on the map
- pin doesn't move for every track I tried 
 
https://github.com/user-attachments/assets/70db384a-26ee-4c99-ab62-79c8f11d7ec9

**Comment by Skalii** [comment]
- [x] fix display of analytical points on map after reopening "Segments" tab

**Comment by dmpr0** [comment]
# Review
![Screenshot 2024-10-31 at 17 43 15](https://github.com/user-attachments/assets/1c6ead77-0529-4239-ad2f-9f0c606c5725)

- [ ] It seems that last dashed line is overlay on x-axis line
