### ISSUE TITLE
Remove login/password authorization in OpenStreetMap Editing plugin

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3736]
## Description
Due to deprecation https://github.com/openstreetmap/operations/issues/867 of this methods of authorization we need to remove button **Use username and password** in login dialog.

> Android tasks 
> https://github.com/osmandapp/OsmAnd/issues/18243
> https://github.com/osmandapp/OsmAnd/issues/19970

## ToDo

<table style="width:100%">
  <tr>
    <th>Main bottom sheet</th>
    <th>Benefits...</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/8e7a7453-07b2-4948-bbc7-f80a5e2d9765"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ba3580ab-cfd3-4a4c-90ae-250ee791e05d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Remove **Use username and password** button from:
- - [x] Main bottom sheet
- - [ ] Benefits for active OSM contributors

## Old iOS versions

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e51ce2b6-b94f-4b0c-a9d5-be398c8071b9"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show alert for user with incompatible iOS version
- [x] Title – `Update Required`
- [x] Description – `OpenStreetMap login needs iOS 16.4+`

- [ ] Remove login&password from settings
- [ ] Fix all code used login&password

**Comment by DmitryAlexei** [comment]
- probably exit from the OSM account is needed at app start

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3846

**Comment by DmitryAlexei** [comment]
TestFlight 4.8.0.1 Works well on iPhone 13 mini (cannot test Benefits for active OSM contributors)
on iPhone 6s (iOS 15.7.7)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2c064af3-6f43-4e8c-8dbe-75efc9fc1583"  width="300" height="auto"/> </td>
  </tr>
</table>
