### ISSUE TITLE
Indicate road side where destination – Road details

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3771]
# ToDo

> Next part for https://github.com/osmandapp/OsmAnd-iOS/issues/2981

Angle between Destination (Bearing from last point) and last segment (Bearing last 2 route points)  should be measured and split in 3 sectors by 120 degree. 
* `-60 °` – `+60 °` = straight
* `-180 °` – `-60 °` = left
* `60 °` – `180 °` = right.

### Left

<table style="width:100%">
  <tr>
    <th>Less then 5 m</th>
    <th>More then 5 m</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/52cf203f-8f99-49b4-b3a7-0d135bf4236c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7872e031-780b-4481-a20b-87d469540a51"  width="300" height="auto"/> </td>
  </tr>
</table>    

- [x] Icon – `ic_custom_road_side_left`
- [x] If distance is <  5 m:
- - [x] Title – `You have arrived.`
- - [x] Description – `Your destination is on the left.`
- [x] If distance is >  5 m:
- - [x] Title – distance to destination (when app draw straight line from the road)
- - [x] Description – `You have arrived, your destination is on the left.`

### Right
<table style="width:100%">
  <tr>
    <th>Less then 5 m</th>
    <th>More then 5 m</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6cef00af-5f6b-4057-8196-0047b27afd7f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1ca29db9-cc64-4f95-aebd-a732a80037d4"  width="300" height="auto"/> </td>
  </tr>
</table>    

- [x] Icon – `ic_custom_road_side_right`
- [x] If distance is <  5 m:
- - [x] Title – `You have arrived.`
- - [x] Description – `Your destination is on the right.`
- [x] If distance is >  5 m:
- - [x] Title – distance to destination (when app draw straight line from the road)
- - [x] Description – `You have arrived, your destination is on the right.`

### Ahead
<table style="width:100%">
  <tr>
    <th>Less then 5 m</th>
    <th>More then 5 m</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/18034ebe-c29e-4ff6-b23b-fa210948999a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4b134b20-d737-4718-b9b2-0628f34770cc"  width="300" height="auto"/> </td>
  </tr>
</table>    

- [x] Icon – `ic_custom_road_side_front`
- [x] If distance is <  5 m:
- - [x] Title – `You have arrived.`
- - [x] Description – `Your destination is straight ahead`
- [x] If distance is >  5 m:
- - [x] Title – distance to destination (when app draw straight line from the road)
- - [x] Description – `You have arrived, your destination is straight ahead`

**Comment by dmpr0** [comment]
## Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/61a4dc58-3095-4b91-b0a6-53ca9f85c01b"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] OsmAnd says it on the left, but on map in on the right? 
* * Route from `50.43608° N, 30.50634° E` to `50.43690° N, 30.50871° E`

**Comment by dmpr0** [comment]
`‎52.49536° N, 13.36632° E‎` > ‎`52.49797° N, 13.36698° E‎`

**Comment by EugeneZmeuk** [comment]
**Docs**
 - [ ] [Turn-by-turn information](https://osmand.net/docs/user/navigation/setup/route-details#turn-by-turn-information)
 - [ ] [Instructions](https://osmand.net/docs/user/navigation/setup/route-details#instructions) - add the info about Road side indicator: new screenshot and info [from the Blog](https://osmand.net/blog/osmand-ios-4-8-released/#road-side-indicator)
