### ISSUE TITLE
3D Icons from Plugin (test) - iOS

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3778]
## Description
Goal of this task to repeat Android prototype and let Custom plugin work the same as in Android

> OpenGL task From https://github.com/osmandapp/OsmAnd-Issues/issues/2545
> Plugin – [3DIcons.osf.zip](https://github.com/user-attachments/files/15871898/3DIcons.osf.zip)

<details>
    <summary>Folder structure</summary>
<table style="width:100%">
  <tr>
    <th colspan=2>Folder structure</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/88bec0b5-b85b-4da9-ab04-3be84acb862b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/ade08c73-84a8-43b9-87cb-091bb9206915"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

<details>
    <summary>Android</summary>

<table style="width:100%">
  <tr>
    <th colspan=2>Android</th>
  </tr>
  <tr>
    <th>Profile appearance</th>
    <th>Map</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/fa8e932e-45e0-417d-8232-2b00b0816072"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/106130e7-dbb7-4f28-95dd-2e9b4cc78e60"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

## ToDo
- [x] Move code to iOS –https://github.com/osmandapp/OsmAnd/commits/48850bc1821ef19daa2c370a4795a183a2abd4ab/OsmAnd/src/net/osmand/plus/helpers/Model3dHelper.java
- [x] Follow the same file structures as on screenshot (`models/...`)
- [x] Show 3D icons on the map if selected
- [x] Show icons preview if they present

**Comment by tigrim** [comment]
### Technical Plan

1. **Rewrite** `Model3dHelper.java` -> `Model3dHelper.swift`
2. `ProfileAppearanceFragment` -> `OAProfileAppearanceViewController`
3. `PointLocationLayer` -> `OAMyPositionLayer`

### Key Methods:

- Useful method:
  ```cpp
  std::shared_ptr<const OsmAnd::Model3D> OsmAnd::ObjParser::parse(const bool translateToOrigin /*= true*/) const
  ```

### Testing:

1. **Test** 3D icons for current location during movement(different profiles).
2. **Test** 3D icons between sessions on the map and in the selected state on the icon selection screen.

**Comment by nnngrach** [comment]
todo: fix raster / 3d layers order.
https://github.com/osmandapp/OsmAnd/pull/20184/files

**Comment by nnngrach** [comment]
video:
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/a51a9fe1-94d3-42cc-9fcd-189a3dc5423b

request:
https://github.com/osmandapp/OsmAnd-iOS/pull/3830

**Comment by vshcherb** [comment]
- [ ] Use 3D icons by default (optionally switch in developer settings enable/disable 3d icons)

**Comment by nnngrach** [comment]
- [x] Fix import/export profile settings

**Comment by DmitryAlexei** [comment]
TestFlight 4.8.0.3
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ce33eb89-a2b7-475e-a6e8-e4624620e49d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7ed12238-9331-4296-8ac3-bcebb60effa6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by EugeneZmeuk** [comment]
**Docs**
- [ ] [Profile appearance](https://osmand.net/docs/user/personal/profiles#profile-appearance)

**Comment by vshcherb** [comment]
Documentation:
1. Split https://osmand.net/docs/user/personal/profiles/#profile-appearance into Profile appearance -> My location appearance
2. My location appearance mention 3D icon (rewrite)
3. My location mention that's possible to import custom 3D icon - link to technical structure? - similar to https://github.com/osmandapp/OsmAnd-Issues/issues/2663

**Comment by DmitryAlexei** [comment]
To docs:
- we need to add info about 3D icons from user (example 3D icon plugin).

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/2545#issuecomment-2310843949
