### ISSUE TITLE
Weather screen redesign, particles + animation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3779]
## Description

Redesign weather screen
- Allow slider to move every 10 min (tooltip)
- Move widgets to bottom
- Allow to select / deselect particles (similar Android)

> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/1899
> Separate next task  – Play button

# ToDo, [Figma](https://www.figma.com/design/u8oNqRHuKy04JkSHiqR0TC/Weather?node-id=425-14575&m=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/038582a3-d08d-492c-b378-1bd7713ab7a0"  width="180" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/abfcd630-59d4-419c-b984-29fe1dfa4b1d"  width="180" height="auto"/> </td>
  </tr>
</table>   

### NavBar

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c9b1228f-e7a2-43f4-9b2f-ab5c080afeac"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [x] Add action **Data source**, icon – `ic_navbar_settings`
- [x] Tap open Data source view

### Date switcher

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f475f2b1-f6db-4f9d-88af-823b758de71d"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [x] Remove dates
- [x] Use **Tomorrow** for the next day instead of day name
- [x] Use short day name instead of dates

### Widget & Timeline
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2392f58d-0e6d-44a5-80c7-66c5b0828003"  width="375" height="auto"/> </td>
</table>   

**Widgets**
- [x] Show widget for each weather data type.
- [x] Use widget icons

## Map Buttons

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1b58e854-4b0e-44b0-908f-6a9b04559c02"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [x] **Contours** – tap show context menu with the list of weather contour lines
- - [x] ON – icon `ic_custom_contour_lines`
- - [x] OFF – icon `ic_custom_contour_lines_disabled` 
- [x] **Layers** – tap show bottom view with the list of weather layers
- - [x] ON – icon `ic_custom_overlay_map`
- - [x] OFF – icon `ic_custom_overlay_map_disabled` 

## Menus

<table style="width:100%">
  <tr>
    <th>Contours</th>
    <th>Layers</th>
    <th>Data source</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/de780b1a-7a4f-47cc-b8b1-e367dfd9a49b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/11d4eed6-7688-41e0-a6f0-55f79fce55c0"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/257b6617-ea73-47f4-ab90-9f68f4c21899"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Contours
- [x] Show context menu with with the list of available contours
- [x] Only one type of weather contour lines could be enabled.
- [x] By default – None

### Layers menu
- [x] Show view in bottom state with the list of available weather map overlays:
- - [x] Temperature, icon – `ic_custom_thermometer`
- - [x] Precipitation, icon – `ic_custom_precipitation`
- - [x] Wind, icon – `ic_custom_wind`
- - [x] Clouds, icon – `ic_custom_clouds`
- - [x] Air pressure, icon – `ic_custom_air_pressure`
- [x] By default – all disabled
- [x] Add **Wind animation** item, should allow to turn on Wind animation separately from Wind layer.

### Data source

- [x] Title – `Data source`, description – `OsmAnd provides weather data from two sources: `
- [x] Options 1: `GFS`
- - [x] Second line – `Global Forecast System from National Centers for Environmental Prediction`
- - [x] Selected by default
- [x] Options 2: `ECMWF`
- - [x] Second line – `European Centre for Medium-Range Weather Forecasts`

**Comment by tigrim** [comment]
**Technical Plan:**

1. Adjust the slider step to 10 minutes, referencing the `layoutSelectingTitle` method.
   
2. Configure the group of buttons `weatherGroupBottonsView`: Layers menu, Contours [OAHudButton]. Apply the layout position similar to the OAHudButton - cancel.
   
3. For the section with widgets, maintain the UICollectionView and center-align it.
   
4. Disable the display of weather widgets when the weather menu is shown on the screen.
   
5. Synchronize settings keys with Android once their task is completed.

**Comment by Andrewschenko** [comment]
Weather forecast provider was thoroughly refactored. In order to enable animations, application should specify the needed time period when provider is being created and a time step. Provider will then try to load all necessary online resources for this particular period for each moment of time (between time steps specified). OsmAnd application for Android [has this code](https://github.com/osmandapp/OsmAnd/blob/fa643279712b8e589227a75961a4d24e2e5fd681/OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java#L91-L92) implemented.

**Comment by tigrim** [comment]
The 'Wind animation' settings section was hidden

**Comment by tigrim** [comment]
"Add Wind animation item, should allow to turn on Wind animation separately from Wind layer."  In this task, they asked not to do. The item has been added but is currently hidden

**Comment by dmpr0** [comment]
# Review 

### Mac OS

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/252dbeba-2800-4717-930f-b9172b1f0008"  width="auto" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] String is missed in NavBar

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cc0c09d6-2938-42e7-9352-22b3e68f10a9"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Add padding below slider

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/296f39c7-ea7c-4124-bb7f-abf9b5995b07"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Screen is collapsing while screen resize

**Comment by vshcherb** [comment]
- [ ] Play button - prepare and play weather animation 6h - only same day(similar to Android)
- [ ] Add Wind particles animation

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3896

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3898
https://github.com/osmandapp/OsmAnd-iOS/pull/3906
