### ISSUE TITLE
Add Driving region for India

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3857]
## Description
Migrate task from Android https://github.com/osmandapp/OsmAnd/issues/20227

## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f75f700b-3803-43f6-9c6b-1233bed91828"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new Driving region for **India**
- [x] Units – kilometers/meters
- [x] Left-hand driving

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3863
