### ISSUE TITLE
Compass button behaviour

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3859]
> Android tasks 
> * https://github.com/osmandapp/OsmAnd-Issues/issues/2504
> * https://github.com/osmandapp/OsmAnd/issues/17086
## ToDo
- [x] Set **Manually rotated** mode by default for all new users
- [x] Disable all map rotation for **North is up** mode 

### Compass button
- [x] Single tap — should rotate map orientation to the North in all orientations. Even if it will rotate back in a second (for example like in compass mode)
- [x] Double tap – should switch map orientations (previously works for single taps)
- [x] Long tap – without changes, should open bottom sheet with the list of available orientations.
- [x] Change button visibility by default to **Always visible**

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/3948

**Comment by dmpr0** [comment]
# Review


- [ ] **Manually rotated** should be first in the list
- [ ] **North is up** – last
- [ ] Use string keys from Android ` <string name="rotate_map_north_opt">North is up</string>`
