### ISSUE TITLE
Use POI categories as icons / icon selection component

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3942]
> Android task https://github.com/osmandapp/OsmAnd/issues/16223

## Description 

* Use POI categories as categories for icons. 
* Allow to search icons by sub category name 

- - -

## ToDo

- [ ] We could get categories and icons hierarchy from Custom Filter. 

## Icon group, component

<table style="width:100%">
  <tr>
    <th>Favorites, Waypoints</th>
    <th>Profile icon</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4cfd6606-a285-4cf4-a00c-e1bfa383f748"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3a3dd874-e15a-4803-ba38-06ec2d46ed77"  width="300" height="auto"/> </td>
  </tr>
</table>   

We need to create one component to use on all screen where icon selection will be needed
- [x] Use on: 
- - [x] Add / Edit Favorites
- - [x] Add / Edit Track Waypoint
- - [x] Profile appearance
- [x] Show title on the lift side – Icon
- [x] Show popup button on the right side (we use similar in Terrain)
- - [x] Tap on button, should show list of categories 
- - [x] After selecting different category icon list should change
- [x] Show icons from **Last used** group by default 
- [x] **All icons** button, tap should open **Select icon** view

## Select icon, view. [Figma](https://www.figma.com/design/0tOguKltp8m6UuLp7biZh5/My-places?node-id=3292-22973&m=dev)

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th>Select icon</th>
    <th>Jump to category</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0a3dc32c-37c9-4412-b6e5-34f8a102ea77"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/760328f0-c545-43b4-b413-2f34d5317311"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

### NavBar

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/bad8a921-f19f-4a41-8627-38aa5ea22d89"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Right action – tap should open list of available categories 
- - [x] Icon – `ic_navbar_list` 
- [x] Show search bar, should be visible by default

### Chips

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c6dfb2cc-5059-4f04-a968-8b4fa573f337"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show chips button as horizontal list to represent all categories 
- [x] Tap on button should scroll to the selected category
- [x] Categories order should be the same as in the list

### Sections

- [x] First group – Last used, show last used 12 icons.
- [x] Use icons from POI categories  (Search – Custom search)
- [x] Group icons into sections
- - [x] Section name = POI Category.
- [x] Skip sub categories with icon `ic_action_categories_search`, it used as placeholder, if category doesn't have separate icon
- [x] Show all icons from POI category in section
- [ ] Leave categories from [poi_categories.json](https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_categories.json)
- - [ ] **Special**
- - [ ] **Symbol**
- - [ ] **Travel**
- [ ] Show **Activities** from [activities.json](https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/activities.json)

## Search
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/54f5c834-632c-4f00-870d-c19ed4e104fd"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Search icons by sub category name
- [x] Show search results as a list (Similar to Custom Search > Search)

**Comment by Zirochkabila** [comment]
# **Testing 1**

`4.9.5.4990`

## 🟡 **Minor**

- [ ] **1. The icon is displayed empty initially**
- **Issue:** The icon is empty (without an icon), although a star correctly appears after adding it to the map.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/8bf0068b-81b9-43e6-a63b-ff3616519303"></video>
</details>

@dmpr0 

- [ ] **2. Selected category not displayed in the general list of icons**
- **Issue:** After selecting a category, returning to the Favorites settings screen does not display the selected category in the general list of icons, unlike the more logical implementation on Android.

<details><summary>Details</summary>
<table style="width:100%">
<tr>
<td><video src="https://github.com/user-attachments/assets/fd0dc6f9-b9c9-4c43-b79e-25e5b7e23799" width="300" height="auto"></video></td>
<td><video src="https://github.com/user-attachments/assets/ffd33460-8c73-4edc-97f7-610f769e0eec" width="300" height="auto"></video></td>
</tr>
</table>
</details>

- [ ] **3. Search results do not show categories**
- **Issue:** The search results currently do not display associated categories, which could enhance clarity and usability.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/eeeefde6-a5ff-4b67-8c1f-8016f4560cc1"></video>
</details>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/537fe0e6-5841-409e-a812-52d9bae7cc2b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/f510f6e5-8572-4ef4-a0b5-1f8babfa9a62"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Hide categories
- - [ ] Private access 
- - [ ] User defined
- - [ ] Wikipedia

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><video src="https://github.com/user-attachments/assets/f5067e57-3bb7-4bd4-a629-d0427e0dbfa6"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] All icon row is moves after tap on icon

**Comment by dmpr0** [comment]
# Review

## Select icon view

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Figma</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9cc39eb4-af45-45f1-824a-4124430e69de"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4a39423a-5d91-47f6-b6ed-baa2d62de71d"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Use regular view, not modal.

- - -

**Chips**

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Figma</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9cc39eb4-af45-45f1-824a-4124430e69de"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/5ba0c9d7-b5f2-454e-8ebc-88c92ce658f1"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Left and top padding are too big.

**Comment by dmpr0** [comment]
## UI Review 

- [ ] Lag while scrolling
- [ ] Strange loading process? See on Nautical category

**Comment by Zirochkabila** [comment]
# Testing 4
`5.0.1.5011`

Still present:
1. Lag while scrolling
2. Keyboard cannot be hidden after being displayed points

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/tracks/track-context-menu/#add-waypoint-to-a-track
https://osmand.net/docs/user/search/search-all#basic-queries
https://osmand.net/docs/user/personal/favorites#favorite-icons

**Comment by dmpr0** [comment]
## UI Review

- [ ] Crash trying to select icon group in Add favorite group UI.

**Comment by Zirochkabila** [comment]
# Testing 5
`5.0.2.5012`

Crash, lag when scrolling and displaying the keyboard - **Fixed**

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2ce51121-510a-4ca1-b6ae-688e1f32bfcf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ec41ad48-2a4a-4a64-b9b5-39914c59cc92"  width="300" height="auto"/> </td>
  </tr>
</table>   

> - [x]  First group – Last used, show last used 12 icons.

- [ ] One last icon is shown in **Last** used group

**Comment by Zirochkabila** [comment]
# **Testing 6**
`5.0.2.5016`

## 🟡 Minor

- [ ] **1. "Apply to existing" does not add the selected icon to "Last used" category**
- **Issue:** After applying an icon to existing items, it doesn't appear in the "Last used" section.

<details><summary>Details</summary>
<img width="900" src="https://github.com/user-attachments/assets/eea4db63-9fc9-4312-90f5-b7aec25f7831">
</details>

- [ ] **2. "Last used" category shows an empty icon before the default icon**
- **Issue:** The first slot in "Last used" is blank, followed by the default icon.

<details><summary>Details</summary>
<img width="900" src="https://github.com/user-attachments/assets/dc4e0ad3-6c9d-4cba-a226-f47b5e710738">
</details>

**Comment by dmpr0** [comment]
## UI Review

- [ ] POI icons should be added to Last used too. How to test, select any POI on the map, tap Add, POI icon is not visible in Last used category.

**Comment by Zirochkabila** [comment]
# **Testing 7**
`5020`

## 🟠 Major

- [ ] **The applied icon is not displayed in the “Last used” category — appears frozen.**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/f0204979-bcdc-4dbf-a8f2-198e39a02f20"></video>
</details>

**Comment by vshcherb** [comment]
https://osmand.net/docs/user/personal/favorites#favorite-icons
