### ISSUE TITLE
Map mode add option According to App theme

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3949]
> Android task https://github.com/osmandapp/OsmAnd/issues/3384

## ToDo

<table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/47a2dbe2-7206-4aa2-a627-c97f1bab01bc"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/60150533-9666-4b5a-a186-d6adc7073111"  width="300" height="auto"/> </td>
      </tr>
</table>
   
<details>
    <summary>All mode</summary>
    <table style="width:100%">
      <tr>
        <th>Day</th>
        <th>Night</th>
        <th>Sunrise/sunset</th>
        <th>Light sensor</th>
        <th>App theme</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/6bfd4f0d-3dd9-45e0-8034-7a17234a4345"  width="140" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/0659d901-a44f-49d1-8ec3-c0339b28183b"  width="140" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4a7273ef-1950-4d02-a2ae-e374188d2ea1"  width="140" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/33036e74-2fa1-41ea-822d-e43f3ef27d6a"  width="140" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/ede33dbc-490b-40bc-b39d-654bd77244d6"  width="140" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Switch from dialog to full screen view similar to Visibility screen (see Terrain)

### NavBar
- [x] Left action – Close, tap close screen without changes
- [x] Right actions – Reset to default

### Map mode card, [Figma](https://www.figma.com/design/IAYbdcU1GnqjH3yqweEpT1/Configure-Map?node-id=2813-27825&m=dev)
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3290e68f-b332-494b-a47b-fdf3833c1186"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Use segment control to switch between map modes
- [x] Switch mode after tap
- - [x] Apply by button 
- [x] Add new mode **App theme**, map mode should depend on App theme option
- [ ] Add new mode **Light sensor**, map mode should depend on light conditions

**Modes**
- [x] **Day**
- - [x] Description – `Always displays the map in a light theme, ideal for daytime visibility.`
- - [x] Default icon – `ic_custom_sun_outlined`
- - [x] Selected icon – `ic_custom_sun`
- [x] **Night**
- - [x] Description – `Always displays the map in a dark theme, suited for nighttime or low-light conditions.`
- - [x] Default icon – `ic_custom_moon_outlined`
- - [x] Selected icon – `ic_custom_moon`
- [x] **Sunrise/sunset**
- - [x] Description – `Automatically switches between day and night themes based on local sunrise and sunset times.`
- - [x] Show additional line with the information about next sunrise / sunset – `Sunrise – 05:22, sunset – 20:28`
- - [x] Default icon – `ic_custom_sunset_outlined`
- - [x] Selected icon – `ic_custom_sunset`
- [ ] **Light sensor**
- - [ ] Description – `Uses the device's light sensor to toggle between light and dark themes according to ambient light levels.`
- - [ ] Default icon – `ic_custom_map_light_sensor`
- - [ ] Selected icon – `ic_custom_map_light_sensor_filled`
- [x] **App theme**
- - [x] Description – `The map's display aligns with the app’s overall theme—day mode for a light theme and night mode for a dark theme`
- - [x] Default icon – `ic_custom_map_mode_app_theme`
- - [x] Selected icon – `ic_custom_map_mode_app_theme_filled`

**Comment by DmitryAlexei** [comment]
Investigate if Map mode according to Light sensor is possible to implement. We can also track the screen brightness. (>50% it is day)

**Comment by tigrim** [comment]
# Technical Plan for Light Sensor

## Objectives

- Explore the possibilities of using Apple SensorKit for reading light intensity data.
- Implement functionality for obtaining and processing brightness data.

## Implementation Steps

### 1. Check the possibility of using SensorKit

- Review the SensorKit documentation:
  - [SensorKit Documentation](https://developer.apple.com/documentation/sensorkit)
  
- Study the authorization request method:
  - [Request Authorization](https://developer.apple.com/documentation/sensorkit/srsensorreader/3666518-requestauthorization)

### 2. Example of using SRAmbientLightSample

- Review the SRAmbientLightSample example:
  - [SRAmbientLightSample Documentation](https://developer.apple.com/documentation/sensorkit/srambientlightsample)

- Use `lux` to obtain illumination values:
  - [Getting lux value](https://developer.apple.com/documentation/sensorkit/srambientlightsample/3377859-lux)

## Sample Code

```swift
import SensorKit

func requestAuthorization() {
    let sensorReader = SRSensorReader()
    sensorReader.requestAuthorization { success, error in
        if success {
            print("Authorization successful")
        } else {
            print("Authorization error: \(String(describing: error))")
        }
    }
}

func readAmbientLight() {
    let ambientLightSample = SRAmbientLightSample()
    
    ambientLightSample.lux { measurement in
        print("Light level: \(measurement.value) lux")
    }
}
```

## Conclusion

- After completing the above steps, it is necessary to test the sensor's functionality and ensure the accuracy of the read data.

**Comment by dmpr0** [comment]
# Review 
- [ ] Use NavBar similar to Terrain – Visibility screen
- [ ] Map buttons is missed

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/02594fd7-3338-4a7e-b1bb-628e3bc648b5"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] New UI doesn't looks good

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/7c33f962-cddd-49da-9adb-48f596c8a9b8"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Some header are broken? Tested on iPhone 16 Pro Max, iOS 18.2

**Comment by DmitryAlexei** [comment]
- cannot reproduce on iOS 18.1, probably issue can only be reproduced on beta

**Comment by vshcherb** [comment]
Will be reopened if the issue will be on the final ios release
