### ISSUE TITLE
Group translations for all POI types with `lang="true"`

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3951]
## Description
We need to group into one line translations for all poi types that can have it, currently we do it for: name, alt name, old name.

* POI Types – https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml
* Example – https://www.openstreetmap.org/node/7140575085

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5ee727bf-0f34-46ea-bea2-f3600d455330"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

## ToDo

- [x] Group translations
- [x] Use the same UI as for Name tag

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/f5db614a-0d1c-4e1f-b50f-5c4640fabee3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Doesn't work for [wheelchair:description:lang](https://wiki.openstreetmap.org/wiki/Key:wheelchair:description)=*.
* * Example https://www.openstreetmap.org/node/250624673

**Comment by tigrim** [comment]
<img width="1019" alt="Снимок экрана 2024-09-10 в 11 03 22" src="https://github.com/user-attachments/assets/5f16e9c3-3092-41e2-bbe4-15e6735118a9">
<img width="1022" alt="Снимок экрана 2024-09-10 в 11 04 12" src="https://github.com/user-attachments/assets/478158c5-2af8-4d15-96d6-a34a6cfbda01">

**Comment by dmpr0** [comment]
# Review 3


<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/39461eb3-94a7-4444-a90e-e76bbcd7d627"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/de03ed47-becd-43ca-ace8-0c6a97a56d80"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   



- [ ] English name is lost for 2 of 3 points

**Comment by tigrim** [comment]
We discussed it with @dmpr0, it didn't reproduce
