### ISSUE TITLE
Show battery level for external sensors 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3953]
> Android task https://github.com/osmandapp/OsmAnd/issues/20257

## ToDo

<table style="width:100%">
  <tr>
    <th>Sensor data</th>
    <th>Battery level</th>
    <th>Show dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/661cea3a-576d-4487-9b04-02b5bfd60b07"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/9923307c-ca0f-4669-9574-c6802f931925"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/aa6a7918-18fa-40d9-90b4-9f664d6012b8"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new option – **Show**
- - [x] **Sensor data**, show main data from sensor
- - [x] **Battery level**, show sensor batter level as main value
- [x] Show icon related to selected mode:
- -  [x] `ic_custom_sensor_heart_rate_battery_outlined`
- -  [x] `ic_custom_sensor_cadence_battery_outlined`
- -  [x] `ic_custom_sensor_bicycle_power_battery_outlined`
- -  [x] `ic_custom_sensor_speed_battery_outlined`
- -  [x] `ic_custom_sensor_distance_battery_outlined`
- [x] Tap on widget should switch it mode
- [x] Change widget icon and name depend on mode

### Modes
<table style="width:100%">
  <tr>
    <th>Main data</th>
    <th>Battery level</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/354c5ff3-f8ae-4637-bb0a-84529ff28626"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4656f8a4-77ff-455d-a8cb-cccf16f01aed"  width="auto" height="auto"/> </td>
  </tr>
</table>   

### Name & Icons
**Bicycle cadence**
- [x] `Bicycle cadence, battery`
- [x] Icon – `widget_sensor_cadence_battery_day/night`

**Bicycle power**
- [x] `Bicycle power, battery`
- [x] Icon – `widget_sensor_bicycle_power_battery_day/night`

**Heart rate**
- [x] `Heart rate, battery`
- [x] Icon – `widget_sensor_heart_rate_battery_day/night`

**Bicycle speed**
- [x] `Bicycle speed, battery`
- [x] Icon – `widget_sensor_speed_battery_day/night`

**Bicycle distance**
- [x] `Bicycle distance, battery`
- [x] Icon – `widget_sensort_distance_battery_day/night`

**Additionally:**
- [x] Use new icon for temperature sensors `widget_sensor_temperature_day/night`

**Comment by Zirochkabila** [comment]
# **Testing 1**

`4.9.5.4989`

Checked the UI part (displaying the corresponding icons on each of the widgets)

## 🟡 **Minor**

- [ ] **1. The icon in the Temperature widget settings and on the main screen are different**
- **Issue:** The displayed icon in the settings does not match the one shown on the main screen, causing potential confusion.


- [ ] **2. The charge icon is located to the left of the Temperature icon, not to the right as for other widgets**
- **Issue:** Inconsistency in the icon layout compared to other widgets, which may affect the user experience.


<details><summary>Temperature widget</summary>
<table style="width:100%">
<tr>
<th><img src="https://github.com/user-attachments/assets/8372b7c0-3f9f-468e-87db-104a8900180f"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/0eefbfc6-34e3-4c54-988b-9062132a2463"  width="300" height="auto"/> </th>
</tr>
</table>  
</details>

**Comment by dmpr0** [comment]
@Zirochkabila fixed by https://github.com/osmandapp/OsmAnd-iOS/commit/ae3b6490e5c7334e4f902e669a23cf948dd704dc

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c1c59b27-a261-4b7c-8f98-5efa7cf9a03b"  width="300" height="auto"/> </td>
  </tr>
</table>   



- [ ] Use `iconColorActive` instead of blue color from Android for **Source of data** and **Show**

**Comment by tigrim** [comment]
We decided to keep it as is since the icon color is tied to the profile color.
