### ISSUE TITLE
Context menu for widgets

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3954]
> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/2271

## ToDo, [Figma](https://www.figma.com/design/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?node-id=1568-69942&m=dev)
<table style="width:100%">
  <tr>
    <th>Top / Bottom</th>
    <th>Left / Right </th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9899ac82-db63-4d49-9d46-11017e1dd4b5"  width="300" height="auto"/> </td>
    <td valign=top><img src="https://github.com/user-attachments/assets/a6ec0b5a-7469-4c4d-9c12-e4bb5889889d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show context menu on long tap

### Actions
**Top / Bottom panels**
- [x] **Add widget to the right**
- - [x] Show add widget screen, after selection, new widget should be added to the right side.
- - [x] Icon – `ic_custom_add_item_right`
- [x] **Add widget to the left**
- - [x] Show add widget screen, after selection, new widget should be added to the right side.
- - [x] Icon – `ic_customn_add_item_left`

**Left / Right panels**
- [x] **Add widget above**
- - [x] Tap – Display available widgets
- - [x] Icon – `ic_custom_add_item_above`
- [x] **Add widget below**
- - [x] Tap – Display available widgets
- - [x] Icon – `ic_custom_add_item_below`

**Both**
- [x] **Settings**
- - [x] Tap – Open settings screen for selected widget.
- - [x] Icon – `ic_custom_settings_outlined`
- [x] **Delete**
- - [x] Delete selected widget
- - - [x] Show confirmation alert
- - [x] Icon – `ic_custom_trash_outlined`

**Comment by Zirochkabila** [comment]
`4.9.0.10`
Behavior has not changed 
At least on the M1 architecture, it is not possible to check

**Comment by dmpr0** [comment]
# Review

### Widget setting view

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/72ac2a1b-70c7-4a17-a6d5-6f9f7d5b5ecd"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/e765b874-5adb-40ae-8a4a-cb20b47a1979"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Use Native controls in NavBar if ont
- [ ] Replace Back with **Cancel**
- [ ] Add **Done** button to apply changes

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.0.16`

1. It is impossible to open the context menu in the lane widgets that have been added to the Bottom and Top panels
[Video](https://drive.google.com/file/d/1Zo9nNThIcih6K8suc8u53IRio2KOl3lt/view?usp=sharing)

**Comment by dmpr0** [comment]
> # Testing 2
> `4.9.0.16`
> 
> 1. It is impossible to open the context menu in the lane widgets that have been added to the Bottom and Top panels
>    [Video](https://drive.google.com/file/d/1Zo9nNThIcih6K8suc8u53IRio2KOl3lt/view?usp=sharing)

The old widgets don't have a menu.

**Comment by EugeneZmeuk** [comment]
## docs
- [Widget Context menu](https://osmand.net/docs/user/widgets/configure-screen#widget-context-menu)

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/web/commit/b220e4e79483fdaf3e02ae1d1e46b08dd8d4b491
