### ISSUE TITLE
Turn On / Off Touch screen lock – Quick action

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4059]
> Android task 
> * https://github.com/osmandapp/OsmAnd/issues/20742

## ToDo
<table style="width:100%">
  <tr>
    <th>Quick actions</th>
    <th>Interface group</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a78820b0-b85c-450c-8e97-0ada3e746eb7"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/87b9cbc4-774c-403e-a4f0-c674705e2245"  width="200" height="auto"/> </td>  </tr>
</table>   

- [x] Add new quick action group **Interface**
- - [x] Icon – `ic_custom_ui_customization`
- [x] Add new quick to this group
- [x] Icon – `ic_custom_touch_screen_lock`
- [x] Name – `Turn On / Off – Touch screen lock`
- [x] Description – `Enables or disables touch screen functionality to prevent accidental taps`
- [x] Touch screen functionality should be restored after app restart 

 **Custom button:**
- [x] Use icon `ic_custom_lock_closed`, for lock action (when screen is unlocked).
- [x] Use icon `ic_custom_lock_open`, for unlock action (when screen is locked).

**Toast messages**
- [x] Show toast messages:
- - [x] After screen is locked – `Touch screen is locked. Tap on button to unlock.`
- - [x] After screen in unlocked – `Touch screen is unlocked.`
- [ ] If screen was locked by external button, include button name in description `Touch screen is locked. To unlock, press the "Volume down" button, or tap the on-screen button.`
