### ISSUE TITLE
Gallery – Context menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4062]
> Android task 
> * https://github.com/osmandapp/OsmAnd-Issues/issues/2647

## ToDo
* Redesign image block in Context menu
* Add separate screen with list of all images related to the place
* Add full screen gallery

# Context menu

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Online photos</th>
    <th>Street-level imagery</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a9167f82-0572-4004-825d-953072024535"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/59b2fe66-3b13-48ad-a472-08a110f7bd3e"  width="200" height="auto"/> </td>
  </tr>
</table>   

</details>  

- [x] Add separate item for **Online photos**
- - [x] Icon – `ic_custom_photo`
- - [x] To show images from Wikimedia
- [x] Add separate item for **Street-level imagery**
- - [x] Icon – `ic_custom_photo_street`
- - [x] To show images from Mapillary

## Online photos, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=2810-47190&m=dev)

<table style="width:100%">
  <tr>
    <th>Closed</th>
    <th>Open</th>
    <th>No photos available</th>
    <th>No Internet connection</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d196614e-dcdd-4131-becd-37e41015ec32"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3f145081-ad80-47e0-80e2-fbdcb508a6ab"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a62d1703-cd7e-42ad-8003-f57d51e5df13"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/009eeb8b-902d-4c3d-84b4-429aa3239c79"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Show low resolution images (see Android)
- [x] Show as separate item
- - [x] Closed by default
- - [x] Always visible
- [x] Add button **View all**, below photos
- - [x] Tap should open Gallery view

### Photos

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a18168d8-f727-42d6-8734-d94f427b34f3"  width="400" height="auto"/> </td>
  </tr>
</table>   

- [x] Main photo size – `156 x 156 pt`
- [x] Show image provider logo above first photo – `ic_custom_logo_wikimedia`
- [x] Small photos – `72 x 72 pt`
- [x] Tap on photo should open this photo full screen
- [x] Add support for horizontal scroll, all next photos should be `72 x 72 pt`

### Empty states

<table style="width:100%">
  <tr>
    <th>No Internet connection</th>
    <th>No photos available</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0698b0ea-d843-4d07-90cb-9a17f4135f7d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/775f58f0-03b9-419d-bbde-2fb8c0e34fc2"  width="300" height="auto"/> </td>
  </tr>
</table>  

**No Internet connection**
- [x] Icon – `ic_custom_wifi_off`
- [x] Title – `No Internet connection`
- [x] Description – `Please check your connection and try again.`
- [x] Button – `Try again`

**No photos here**
- [x] Icon – `ic_custom_desert`
- [x] Title – `No photos available`
- [x] Description – `No user photos have been added to this location yet`

## Street-level imagery, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=2843-9097&m=dev)

<table style="width:100%">
  <tr>
    <th>Open</th>
    <th>Closed</th>
    <th>No photos here</th>
    <th>No Internet connection</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d8729e6b-d361-43fe-9b9e-dc2fdce2745d"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7dd048b1-f1ab-44b7-9e22-494e260cea8e"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c94dda1a-46aa-41b1-8c6e-516be463e29d"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d77b44d5-2dc6-47ea-9ef8-28e84590431d"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Show as separate item 
- - [x] Closed by default
- - [x] Visible if Mapillary plugin is On
- [x] Show 1 big and 4 small photos
- [x] Add button **Explore**, below photos
- - [x] Tap should open Mapillary view

### Banner

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e7c380ed-d144-4178-914a-66d3e9ab3a14"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show after photos block
- [x] Text – `Share your street-level view via Mapillary.`
- [x] Button
- - [x] Text - `Add photos`
- - [x] Icon – `ic_action_mapillary`
- [x] Background color – `bannerMapillaryBgColor`
- [x] Button background color – `buttonMapillaryBgColor`

### Photos

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/500b24f6-49ac-4c11-803b-5af5ca21ba52"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Main photo size – `156 x 156 pt`
- [x] Show image provider logo above first photo – `ic_custom_mapillary_color_logo`
- [x] Small photos – `72 x 72 pt`
- [x] Tap on photo should open Mapillary view
- [x] Add support for horizontal scroll, all next photos should be `72 x 72 pt`

### Empty states

<table style="width:100%">
  <tr>
    <th>No Internet connection</th>
    <th>No photos here</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3694eede-3621-4da9-8ff9-ba03fc59ec52"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c7f1be97-e389-4cfe-a0ba-05166ade0a94"  width="300" height="auto"/> </td>
  </tr>
</table>  

**No Internet connection**
- [x] Icon – `ic_custom_wifi_off`
- [x] Title – `No Internet connection`
- [x] Description – `Please check your connection and try again.`
- [x] Button – `Try again`

**No photos here**
- [x] Icon – `ic_custom_desert`
- [x] Title – `No photos available`
- [x] Description – `No user photos have been added to this location yet`
- [x] Button – `Add photos`

## Gallery, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=2811-23654&m=dev)

<table style="width:100%">
  <tr>
    <th>Open Gallery</th>
    <th>Context menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4df9b0c6-571f-4341-b25b-60c299bf08f7"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/57bf2070-afc1-40b9-b887-d79810ebbd47"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Show photos quantity
- [x] Show all images for the object
- [x] Long tap on image, should show image preview and context menu 

## Open photo, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=2816-7422&m=dev)

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1752fbe6-1aef-488d-9b12-e98d3b0c6faf"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a6075c06-cce4-4112-aecd-32c60246de55"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Show 1280px wide image

**Gestures**
- [x] Swipe Left – Right to view images
- [x] Add Support for two finger image zoom in
- [x] Tap on screen to hide UI

**Details, short:**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e55a73c0-b939-4d68-a663-79a442de88c1"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Show Image provider logo on the left
- [x] Show description in one line (if it present)
- [x] Show Date
- [x] Show Author name
- [x] License

**NavBar Menu:**

<table style="width:100%">
  <tr>
    <th>NavBar actions</th>
    <th>Actios menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/212190b7-4c05-459c-83e4-aec5e7b18a3e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ef355bb9-3f62-4731-b87e-6b221f518652"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Share**
- - [x] Icon – `ic_navbar_export`
- - [x] Allows to share link to the image, for example https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wikimedia_Commons_(cropped).jpg
- [x] **Details**
- - [x] Icon – `ic_custom_info_outlined`
- - [x] Tap open Details screen 
- [x] **Open in browser**
- - [x] Icon – `ic_custom_external_link`
- - [x] Tap should open image link in web browser
- [x] **Download**
- - [x] Icon – `ic_custom_download`
- - [x] Download image to device

### Details screen, [Figma](https://www.figma.com/design/8tRwgEFnQclUPq78UtuKWc/Context-menu?node-id=1067-18419&m=dev)

<table style="width:100%">
  <tr>
    <th>No description</th>
    <th>Two lines</th>
    <th>Full</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/05d5db04-9d50-4533-a62f-a9874ec59a2f"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3dcefa51-3680-49b1-bbe2-39d85c47390e"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/44fc7ecf-5ac9-4f13-aad0-43021da80f56"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [x] Show description if available
- - [x] Show only two lines (or N symbols)
- - [x] Add **Show more** / **Show less** button to show all description 
- [x] Date – photo date
- [x] Author – author name
- [x] License – licence name
- [x] Source, show source name, current – Wikimedia.
- - [x] Tap on source name should open image URL
- [x] Add **Close** button to close menu

**Comment by tigrim** [comment]
**Technical Plan (Swift Refactor & Enhancements)**
1. Refactor to Swift
- OACollapsableCardsView, 
- OAAbstractCard, 
- OANoImagesCard,
- OAImageCard, 
- OAUrlImageCard, 
- OAMapillaryContributeCard,
-  OAImageCardCell.
- OANoImagesCell
- OAMapillaryContributeCell.h

2. Add Caching Layer: Currently, images are loaded every time. Implement caching to avoid reloading images repeatedly.

3. Replace Old Cell Layout Approach: Do not use the old method for displaying cells. Instead, implement a composite layout for cells with images.

**Comment by dmpr0** [comment]
**Doc:**
If user set **Low data** mode in iOS settings, images will be load in 480px

**Comment by Zirochkabila** [comment]
# **Testing 1**

`4,9,5,4986`

## 🔴 **Critical**

- [ ] **1. The image is not displayed after clicking “Open in browser” (or after clicking the Wikimedia button)**
- **Issue:** The image fails to load when using the “Open in browser” or “Wikimedia” options, significantly impacting functionality.

<details><summary>Details</summary>
<table style="width:100%">
<tr>
<th><img src="https://github.com/user-attachments/assets/9a780239-e73c-491e-b55c-6e86e63fadfa"  width="300" height="auto"/></th>
<td><video src="https://github.com/user-attachments/assets/4df972db-e327-4ed6-b421-e514b7effd50"  width="300" height="auto"></video></td>
<th><img src="https://github.com/user-attachments/assets/d3e8ff4d-e689-4c74-902f-b2166c1017ad"  width="300" height="auto"/></th>
</tr>
</table>
</details>

## 🟠 **Major**

- [ ] **1. The saved photo is not displayed in the gallery (Stored in documents)**
- **Issue:** Saved photos are stored in documents instead of the gallery, causing significant usability issues on iOS devices.

<details><summary>Details</summary>
<table style="width:100%">
<tr>
<td><video src="https://github.com/user-attachments/assets/51cd7d95-1302-4613-8bcd-8f87316f2097"  width="300" height="auto"></video></td>
<th><img src="https://github.com/user-attachments/assets/7b54c9db-1268-4989-bfc1-def96961b2be"  width="300" height="auto"/></th>
<th><img src="https://github.com/user-attachments/assets/75df26a3-75a0-477f-9817-17125c7782ae"  width="300" height="auto"/></th>
</tr>
</table>
</details>

## 🟡 **Minor**

- [ ] **1. No animation when clicking on the “View all” button**
- **Issue:** The animation effect is missing when the “View all” button is clicked, leading to a lack of visual feedback.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/432526df-e435-4a50-9131-8394b69922a1"></video>
</details>

- [ ] **2. Displays artifacts at the bottom of the screen when viewing photos in landscape orientation**
- **Issue:** Visual artifacts appear at the bottom of the screen during photo viewing in landscape mode.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/949d6433-c560-4afb-9e06-b14f829828c1"></video>
</details>

- [ ] **3. The dividing line is absent in the deployed state (disappears after the first deployment)**
- **Issue:** After expanding, the dividing line is not visible, reducing the visual structure of the interface.

<details><summary>Details</summary>
<table style="width:100%">
<tr>
<td><video src="https://github.com/user-attachments/assets/2e54c848-a986-4bda-9aee-f74325166e5a"  width="300" height="auto"></video></td>
<th><img src="https://github.com/user-attachments/assets/253509d4-95a9-42f6-9e64-133f22efb04b"  width="300" height="auto"/></th>
</tr>
</table>
</details>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4289f019-efeb-4a37-8b8b-c2e58bd67885"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Hide bottom gradient in full screen mode

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/be988bfa-72e8-45b7-9f13-9a782e87dbfe"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Use POI type icon as placeholder for Wikimedia links

**Comment by tigrim** [comment]
1.Pictures still open at the bottom. Issue: Pictures continue opening at the bottom instead of a centered or expected position. Was fixed. https://github.com/osmandapp/OsmAnd-iOS/commit/68c8c64b8270f9fabbd4d4285421a0652fed6680

**Comment by dmpr0** [comment]
## UI Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Previous</th>
        <th>Now</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4289f019-efeb-4a37-8b8b-c2e58bd67885"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/c8172329-1727-4f6c-a2e5-64e7d3ac3fe3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Hide bottom gradient in full screen mode

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/map-context-menu#online-photos

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/2988
