### ISSUE TITLE
Unit of Volume and Fuel Tank capacity

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4104]
## Description

> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/2754

# ToDo

<table style="width:100%">
  <tr>
    <th>General settings</th>
    <th>Unit of volume</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c298b542-6e56-4dbb-a7c8-0cc8b9646794"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/bdab5ed5-361a-4327-b87a-0457d8dbec3c"  width="200" height="auto"/> </td>
  </tr>
</table>   

## General settings, [Figma](https://www.figma.com/design/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=2783-62577&m=dev)
We need to add few dividers to group related options.

### Units of volume

- [x] Name – `Unit of volume`
- - [x] Use key string – `unit_of_volume` 
- [x] Icon ` ic_custom_obd_fuel_tank`
- [x] Description – `Selected units will be applied to all volume-related data in the current profile.`
- - [x] Use key string – `unit_of_volume_description`
- [x] **Litres** 
- - [x] Set by default if **Driving region** is: Europe, Aisa.., Canada, Japan, India, Australia 
- - [x] Use key string – `litres`
- [x] **Imperial gallons**
- - [x] Set by default if Driving region is: **UK and similar**
- - [x] Use key string – `imperial_gallons`
- [x] **US gallons**
- - [x] Set by default if Driving region is: **United states**
- - [x] Use key string – `us_gallons`

## Vehicle parameters, [Figma](https://www.figma.com/design/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=3070-19230&m=dev)
<table style="width:100%">
  <tr>
    <th>Vehicle parameters</th>
    <th>Fuel tank capacity bottom sheet</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5d95676f-7419-421f-875a-dd9892e2a939" width="200"   height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/96bc5e9b-845f-42b8-8bea-982b4b96fddb" width="200"   height="auto"/> </td>
  </tr>
</table>   
    

- [x]  Divide screen into groups:
- - [x] Dimensions
- - [x] Fuel
- - [x] Other

**Fuel tank capacity**

- [x] Add new item Fuel tank capacity into Fuel group
- - [x] Icon – `ic_custom_obd_fuel_tank`
- - [x] Description – `Enter your tank capacity to accurately track fuel levels and consumption`, key string `fuel_tank_capacity_description`
- [x] Tap on item should open bottom sheet with TextField
- [x] Predefined params: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110
- [x] By default set to **None**

**Comment by Vladyslav-lys** [comment]
Check if the migration works correctly:

1. Remove the app
2. Switch to master branch, change driving region and unit of volume
3. Switch to the branch with fixes, look at the values in the settings if they're correct

**Comment by Zirochkabila** [comment]
# Testing 3
`5.1.2 (5103)`

Checked the correspondence of measurement units and capacity values between exports and imports - **Fixed**
