### ISSUE TITLE
Widgets: wrong layout, missed name

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4106]
## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4d9d249c-628a-4f48-a6e8-28d844b091e7"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Current time** – Missed name
- [x] **Battery level** – Missed name

- - -

- [ ] **Sun position** (all widgets) 
- - [x] Wrong layout in Small size
- - [ ] Wrong size is set in Export, file – [WalkingFromiOS.osf.zip](https://github.com/user-attachments/files/17662642/WalkingFromiOS.osf.zip)

- - - 

- [x] Glide ration – Missed name

- - - 

- [x] Check all widgets

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/1edc7402-7ee9-4e8f-aec1-f1b9b0b8bb2e"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Wrong layout. Value should be centered, names should be trimmed.
