### ISSUE TITLE
Add "Preview next turn" to control camera rotation while navigation (iOS)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4111]
## Description 
Android task https://github.com/osmandapp/OsmAnd/issues/20422

# ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/79801376-7e1a-4954-af65-a2444697e379"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new option **Preview next turn**
- - [x] Enabled by default
- - [x] Description – `Automatically rotates the map to preview the next turn or maneuver.`
- [x] Should be part of **Map during navigation** options list

**Comment by vshcherb** [comment]
Here we need to migrate algorithm but also double check some tests

**Comment by Zirochkabila** [comment]
# **Testing 1**

`5.0.5.5056`
[Driving (5).osf.zip](https://github.com/user-attachments/files/20653174/Driving.5.osf.zip)

**Severity:** 🟠 Major / **Priority:** 🟠 Normal

* [ ] **1. "Preview next turn" setting is lost when exporting a profile — on import (iOS or Android), the feature appears enabled even if it was disabled before export.**

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Disabled before export</th>
    <th>Enabled after import</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3a9d23f3-a8fe-428c-93eb-69457762cdaf" width="300"/></td>
    <td><img src="https://github.com/user-attachments/assets/771f6021-4ccb-4dc3-8f48-ea5f029efa47" width="600"/></td>
  </tr>
</table>
</details>
