### ISSUE TITLE
Smart folders – Tracks

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4119]
## ToDo
Introduce Smart folder functionality for iOS users. 

## My Places

<table style="width:100%">
  <tr>
    <th>Track context menu</th>
    <th>Add smart folder alert</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3cfefbd5-6cbf-448a-ad29-a03d4f47d857"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1c17dc2e-4960-4e26-a402-d0d980bddfa6"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Add context menu action **Add smart folder**, use `ic_custom_folder_smart_outlined`
- [x] Show alert on tap
- - [x] Title – **Add smart folder**
- - [x] Open created folder after saving

## Smart folder

<table style="width:100%">
  <tr>
    <th>Default look</th>
    <th>Menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/29a416f2-766b-4484-bf96-9fd8d6b61e0a"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/51e9321f-4176-4e6a-b806-0579b132e6e0"  width="200" height="auto"/> </td>
  </tr>
</table>   

* Can be added only as top level folder
* Default look - open after adding new Smart folder from My Places

**NavBar additonal Menu**
- [x] **Select** – open select mode with the lest of the tracks from the folder
- - [x] Icon – `ic_custom_select_outlined`
- [x] **Refresh** – app should check if there are any new matched tracks are present (check Files folders).
- - [x] Icon – `ic_custom_update`
- [x] **Edit filter** – open Edit filter screen
- - [x] Icon – `ic_custom_parameters`

### Edit filter

<table style="width:100%">
  <tr>
    <th>Edit filter</th>
    <th>Empty states</th>
    <th>Alert</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/defe56ce-8ae6-4251-ab44-ab6dedc9b780"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/68e2602c-1adf-4b45-a673-24a9e821877f"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f6b3d547-a332-41d7-ab9b-f1ffcdc196e9"  width="200" height="auto"/> </td>
  </tr>
</table>  

* Search like screen with the list of matched tracks and buttons to customize filters.

- [x] Show list of tracks that match to filters

**Empty state**
- [x] Show when no tracks is matched to filters.
- [x] Icon – `ic_custom_search`
- [x] Title – **No matched tracks**
- [x] Description – **Your filter criteria didn't match any of your tracks**

**NavBar actions**
- [x] **Cancel** - Allow to close Editing
- - [x] Show alert if there user weer made chanhes 
- [x] **Done** - Allows to save all changes that were made, even if there is no mathced tracks
- - [x] Go back to smart folder after taping

**ToolBar actions:**
- [x] **Reset all** – Allow to reset all filters state to defaults. Works without aprvoing.
- - [x] Aftet tap, list of tracks should be updated, but not saved fot Smart folder properties. 
 
### Empty state

<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Loading state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/10d42693-583d-41c7-bfc9-7e659665c994"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4d33b3d7-3148-43b1-900a-ddfe1f12b8d1"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Show empty state inside Smart Folder if there is no matched tracks.
- - [x] Title – **No matching track**
- - [x] Description – **All matching tracks will automatically appear here.**
- - [x] Action – **Edit filter**. Open Edit filter screen on tap

## Filters

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e0dfb4ff-3d7e-4ed9-bbd8-3823cf142313"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ed2bdebe-031e-4cc3-b96d-97af06accdce"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Add **Save** button. It will allows to create or update Smart Folder settings.
- - [x] Show alert for new folders 
- [x] Taping Show, should open previous screen. If opened from Edit filter, Edit filter should be used to show results.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4384

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.5.4980`

1. Smart folder disappears after reopening if filters have been applied to it

<details><summary>Disappears</summary>
<video src="https://github.com/user-attachments/assets/eded1d4a-95fd-436f-a7c1-7bf11a2abb3a
"></video>
</details> 

_____

2. In the Smart Folder, the My Places page displays the total number of tracks, but when going to the Smart Folder 0 is displayed (the filter is set so that 0 tracks are displayed)

> The correct number of tracks is displayed on the Selections page, and then correct number is displayed on the My Places page as well


<details><summary></summary>
<table style="width:100%">
  <tr>
    <th>Before Select menu will open</th>
    <th>After</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/3b4d87d7-d0fb-47d8-a977-8d86327c4c6f
"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/bc53c1b5-f256-4622-823f-6ffdabfdd7dc
"  width="300" height="auto"/> </td>
  </tr>
</table> </details> 


____


3. **Reset All** button does not work and causes freezing, flickering data


<details><summary>Reset All</summary>
<video src="https://github.com/user-attachments/assets/6f2d012a-b6e3-4d8c-899b-c4148b0048b9
"></video>
</details>

____

4. Data when entering 0 is not fixed; it can be changed after entering another digit less than 5


<details><summary>0 is not fixed</summary>
<video src="https://github.com/user-attachments/assets/8cb9ab7c-028f-4371-a06d-6bb9851432b1
"></video>
</details> 

____

5. The slider bar goes beyond fixed borders

<details><summary>Fixed borders</summary>
<video src="https://github.com/user-attachments/assets/3c72846e-94ba-4e76-9afd-1d9fff8aae29
"></video>
</details>

___

6. Perhaps it is worth limiting the limit values?


<details><summary>Limit values</summary>
<video src="![Image](https://github.com/user-attachments/assets/c0be7d0c-db6c-491a-b72b-1ca7ac22a35c)
"></video>
</details>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/6ad65f93-f290-43be-b8b4-27e88f3be87"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Duplicates is visible until app restart if track was moved. Create Smart folder, add tracks, find those tracks and move them into another folder.

**Comment by DmitrySvetlichny** [comment]
4. Input Field Behavior with "0" (Data Entry) - Fixed

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4408

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd/pull/21995

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.5.4987`


The following is present:
1. **Smart Folder Disappears After Reopening with Filters Applied** - Testing 1
2. **The Reset all button does not affect the Visible on map item**


<details><summary>Reset all</summary>
<video src="https://github.com/user-attachments/assets/e6bb324e-e116-4649-82af-5bcad08ea353
"></video>
</details>



3. **There are gaps between data**

<details><summary>Gaps</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/98f04df1-2553-4d48-9018-7ae6fd93a3d7">
</details> 

4. **Item with duplicates** - still present before restart (it is impossible to check after restart - blocks item 1) - Review

**Comment by Zirochkabila** [comment]
# **Testing 3**

`4991`

## 🟠 **Major**

- [ ] **1. Item with duplicates - still present before restart**
- **Issue:** Duplicate items appear before the app is restarted, potentially affecting data integrity. (Issue transferred from **Review**)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/e21b79a7-5f38-4cad-8924-fc399b0433ff
"></video>
</details> 

## 🟡 **Minor**

- [ ] **1. There are gaps between data (Mac version only)**
- **Issue:** Visual gaps are present between data elements on the Mac version, negatively impacting the visual consistency of the interface.

<details><summary>Gaps</summary>
<table style="width:100%">
<tr>
<th><img src="https://github.com/user-attachments/assets/eac97c51-8735-4220-bfd4-ecc361648050" width="600" height="auto"></img></th>
</tr>
</table>
</details>

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/myplaces#tracks
https://osmand.net/docs/user/personal/tracks/smart-folder
