### ISSUE TITLE
Incorrect behavior of the track menu 

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4123]
### Description
When displaying a hiking (or cycling, etc.) track from map (tracks should be enabled in menu > configure map > routes > hiking routes), track name is not shown. After downloading track into local memory and try to adjust some parameters - nothing happens. 

### Steps to reproduce
- [x] open a track from Hiking > take a look at its title > it is missing
- [x] save displayed track to the local memory and try to make some kind of interaction inside Track context menu > you will see that your changes are not applied

### Actual result
see video
- missing track's name 
- track disappears from map after saving
- track's name still missing after saving, changes are not applied to a track (for example make track visible)

https://github.com/user-attachments/assets/a2717f2c-eedb-4721-9b52-56522f87e4ae

### Todo
- [x] fix issues with tracks from configure map > tracks (for me hiking, cycling, mountain bike routes act the same)

_Originally posted by @Skalii in https://github.com/osmandapp/OsmAnd-iOS/issues/4033#issuecomment-2470876245_

**Comment by DmitryAlexei** [comment]
- [ ] when opening another screen from Track context menu, the track disappears from map (red line of the track is not visible on the map anymore)

**Comment by Skalii** [comment]
- [ ] no data on the graph after pressing another tab (altitude, speed)

**Comment by Skalii** [comment]
> * [ ]  when opening another screen from Track context menu, the track disappears from map (red line of the track is not visible on the map anymore)

- [ ] lost track after returning to track menu

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4156

**Comment by Zirochkabila** [comment]
Still present

<table style="width:100%">
  <tr>
    <th>4.9.0.9   ---   actual</th>
    <th>OsmAnd~ 5.0.0#3840m, Released: 2024-11-29   -----   expected</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/8cd60579-454d-4193-bcc8-a64a24ba5b95"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/8d9233be-a9bd-4915-8c1b-38f0ec52722d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
Each time you open a menu offering to save a track, even if it has already been saved, you create copies of the same track.
For example, in Android, this is implemented differently - if the track has already been downloaded, there is no more offer to download it


<table style="width:100%">
  <tr>
    <th>4.9.0.11</th>
    <th>OsmAnd~ 5.0.0#3870m, Released: 2024-12-03</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/6b03b242-f54d-43ec-99cd-96b260fba48e"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/user-attachments/assets/efda7ba2-f17e-45b9-ac7f-655a75f0f4d6"  width="300" height="auto"/></td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Yes we need to reuse same name and overwrite
