### ISSUE TITLE
Highlight contour for selected buildings

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4164]
## ToDo

<table style="width:100%">
  <tr>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1a5a9c9c-7f25-4967-b846-1dfd314ec1fc"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Highlight contour for selected buildings
* * Example – https://www.openstreetmap.org/way/5013364

**Comment by DmitryAlexei** [comment]
- [ ] long tap shows within raw 
- [ ] correct name of the buildgs

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.5.4961` - Fixed

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a1ef645a-fa69-47e8-b53a-3a8cc18e8194"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7d460bdc-05d1-47f7-b74f-40bfaa7428d7"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/bcf2e4e6-2cda-4617-b0de-8f6fb21109ff"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/27626c16-e60b-4b11-8260-4a0e43d277dd"  width="300" height="auto"/> </td>
  </tr>
</table>   

Object - ‎50.44832° N, 30.49468° E‎

- [ ] Icon is missing in **What's here** menu
- [ ] Part of the POI data is missing

**Comment by Zirochkabila** [comment]
# Testing 2
4.9.5.4973

**Part of the POI data is missing** - Still present


<details><summary>POI data</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e4395bb4-0d00-4fb1-8794-024a1b1c6d1a"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e29db85c-34a5-4653-8aec-78c4a3b5b2b2"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/map-context-menu

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/relation/5121502#map=17/50.448606/30.495488 

![Image](https://github.com/user-attachments/assets/e7198761-3f8f-448f-91b5-95115f799fb8)
```
education: university Національний педагогічний університет ім. Михайла Драгоманова Lat 50.448776 Lon 30.495537 osmid=2204267673600  [ man_made='education'  ]  poi_additional:[ official_name='Національний педагогічний університет імені Михайла Петровича Драгоманова' website='https://npu.edu.ua/' opening_hours='Mo-Sa 10:00-20:00' wikipedia='http://uk.wikipedia.org/wiki/Національний педагогічний університет імені М. П. Драгоманова' wikidata='Q4315056'  ]  name:uk='Національний педагогічний університет ім. Михайла Драгоманова'  cities:[name=Київ name:hi=कीव name:pt=Kiev name:hr=Kijev name:ht=Kyèv name:hu=Kijev name:hy=Կիև name:pms=Kijv name:id=Kyiv name:af=Kyiv name:is=Kænugarður name:it=Kiev name:zh=基辅 name:ar=كييف name:ja=キーウ name:az=Kiyev name:ro=Kiev name:be=Кіеў name:ru=Киев name:bg=Киев name:bn=কিয়েভ name:br=Kyyiv name:sc=Kiev name:bs=Kijev name:sh=Kyiv name:ka=კიევი name:sk=Kyjev name:sl=Kijev name:ca=Kíiv name:sq=Kievi name:sr=Кијев name:kk=Киев name:kn=ಕೀವ್ name:sv=Kyiv name:ko=키이우 name:sw=Kiev name:zh-hant=基輔 name:zh-hans=基辅 name:ku=Kîev name:ta=கீவ் name:cs=Kyjev name:te=క్యివ్ name:th=เคียฟ name:la=Kiovia name:cy=Kyiv name:lb=Kiew name:tl=Kiev name:nds=Kiew name:da=Kyiv name:tr=Kıyiv name:de=Kiew name:lt=Kijevas name:lv=Kijiva name:uk=Київ name:mk=Кијив name:ml=കിയേവ് name:mr=क्यीव name:ms=Kiev name:el=Κίεβο name:als=Kiew name:eo=Kijivo name:es=Kiev name:et=Kiiev name:eu=Kiev name:vi=Kyiv name:hsb=Kijew name:vo=Küyiv name:fa=کی‌یف name:nl=Kyiv name:nn=Kiev name:no=Kyiv name:fi=Kiova name:fr=Kiev name:fy=Kyiv name:oc=Kyiiv name:ga=Cív name:os=Киев name:gl=Kiev name:bpy=কিয়েভ name:ckb=کیێڤ name:pl=Kijów name:he=קייב place=city ]
```

**Comment by vshcherb** [comment]
- [ ] Non informative name ```<string name="poi_landuse_education">Education</string>``` - Should be "Educational landuse"

**Comment by vshcherb** [comment]
- [ ] **Critical**: Can't click on empty area, every click is recognized as click on POI. and opens Context menu!!!

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/map-context-menu/#select-an-object-single-tap
