### ISSUE TITLE
Quick actions for Trip recording

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4176]
## Description
Android task https://github.com/osmandapp/OsmAnd/issues/20800

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/20ff78dd-1450-4abf-a4b4-25662543e608"  width="200" height="auto"/> </td>
  </tr>
</table>   

## ToDo

- [x] **Start / Pause – Trip recording**
- - [x] Icon start – `ic_custom_trip_rec_start`
- - [x] Icons pause –  `ic_custom_trip_rec_pause`
- [x] **Start – New trip segment**
- - [x] Icon – `ic_custom_trip_rec_new_segment`
- [x] **Save – Recorded Trip & Continue**
- - [x] Icon – `ic_custom_trip_rec_save`
- [x] **Finish – Trip recording**
- - [x] Icon – `ic_custom_trip_rec_finish`
- [x] Add to **My Places** group

**Additionally:**
- [x] Check Import / Export

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4402

**Comment by Zirochkabila** [comment]
# Testing 1

**Comment by dmpr0** [comment]
# Review
Somehow color has changed for verb part of the action name "Save, Add".

- [ ] Fix verb text color

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4430

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.5.4996`

Color of the verb part looks like the `textColorActive` samples

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/quick-action#my-places
