### ISSUE TITLE
Allow to set Activity to recorded GPX with filter

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4177]
> Android tasks
> * https://github.com/osmandapp/OsmAnd/issues/17997
> * https://github.com/osmandapp/OsmAnd-Issues/issues/2758
## ToDo

* Add UI to select activity for each track
* Add UI to Trip recording plugin to to preselect activity 
* * Automatically preselect activity for recorded tracks depend on profile

# Track Context Menu, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=2329-30374&m=dev)

## Top part

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/54bda9cd-8596-4b8f-a274-78ede813f68c"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Show track or route activity next to the distance
- [x] Icon size – 20x20

## Info card

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1e285831-ea10-4c90-a6bc-39ae51a17ba3"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Add **Activity** item
- [x] Show selected activity name on the right side
- [x] Tap on item should open the list with Activities

## Activity selection, [Figma](https://www.figma.com/design/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=3045-18923&m=dev)

<table style="width:100%">
  <tr>
    <th>List</th>
    <th>Search</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/eae03a9f-1fe7-40b9-aadd-4db8c13a5a1f"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2a92a287-b937-46f5-a2d2-066ae032cd65"  width="150" height="auto"/> </td>
  </tr>
</table>  

Separate screen that allows to select activity for track or track segment.

- [x] Show list of available activities 
- [x] Show None as first item
- [x] Use https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/activities.json to get:
- - [x] Groups
- - [x] Labels
- - [x] Icons

# Filters, [Figma](https://www.figma.com/design/0tOguKltp8m6UuLp7biZh5/My-places?node-id=2516-31672&m=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/131cd93c-552d-4e29-afdd-ffa42c547e84"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new item **Type of activity** into Info group

**Item**
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d2a0c951-79fb-4252-acb6-346ed36e4fa9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/9cd3ffb6-0f70-4fa0-aa9e-9aaba35438a0"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show selected parameters on the right side (similar to Nearest cities)

## Type of activity, [Figma](https://www.figma.com/design/0tOguKltp8m6UuLp7biZh5/My-places?node-id=3573-80885&m=dev)
<table style="width:100%">
  <tr>
    <th>Full list</th>
    <th>Search</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b37dc76e-eb75-4f9e-93ce-f3e0485fcdf6"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2439dec0-3eef-4e87-8846-b727ab47c68a"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Use a UI template similar to **Nearest City**.
- [x] Display a list of activities present in the tracks.
- [x] Sort activities by track count, displaying those with the most tracks at the top.
- [x] Show checkboxes on the left side.
- - [x] Allow the selection of more than one activity.
- [x] Show tracks count on the right side

# Selection mode, [Figma](https://www.figma.com/design/0tOguKltp8m6UuLp7biZh5/My-places?node-id=2467-37745&m=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a034a790-1245-4649-a64c-f92e387f9ce9"  width="150" height="auto"/> </td>
  </tr>
</table>   
Add action that should allow to change activity for selected tracks.

- [x] Add action, name – **Change activity**. 
- - [x] Icon – `ic_custom_activity_outlined`
- [x] Open **Activity selection** view on tap
- [x] Selected activity should applies for selected tracks

# Trip recording

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4ffb9e40-b6ed-4c0d-9710-0212ee3552f9"  width="150" height="auto"/> </td>
  </tr>
</table>   

Option should allow pre-selection of activity type for profile. The selected activity should be automatically applied for all recorded tracks in the profile.

- [x] Add new option **Activity**
- - [x] Show current state on the right side
- [x] Tap on Activity, should open the list with Activity
- [x] Default activities:

**Comment by dmpr0** [comment]
# Part 2:
## Automatically add Activity to recorded GPX and Uploaded tracks #2758
https://github.com/osmandapp/OsmAnd-Issues/issues/2758

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4621

**Comment by Zirochkabila** [comment]
# **Testing 1**

`5.0.5.5054`

Currently, the default activity for profiles is **“None”**. You may want to bind the activity to the profile (e.g., Walking activity) as described in the ToDo (Automatically preselect activity for recorded tracks depending on profile).

## 🟡 Minor

* [ ] **1. Strange animation when clicking on activity types.**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/68dd5dab-6cf3-4b8d-8305-e36292c6b587"/>
</details>

**Comment by DmitrySvetlichny** [comment]
Point Strange animation when clicking on activity types - This is not a bug, this is the system behavior of the cell when selected.

**Comment by DmitryAlexei** [comment]
check with Android - The selected activity for a profile is not displayed in the track info during track recording. It starts to be displayed after saving

**Comment by Zirochkabila** [comment]
Android - displays the activity during track recording (after the end of recording, the activity of the last profile that was selected during track recording is displayed)

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/2b9ed177-c9c0-4e34-a490-b5c6acbaac48">
</details>
