### ISSUE TITLE
Min/max speed routing parameters

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#802]
# Review 5.01
- [x]  Increase navigation bar height
- [x] It's hard to move sliders because the screen tries to scroll down. (Default screen doesn't have such an issue).

# Review
- [x]  It's hard to move the "Min" pointer when it set's to the closest left side.
- [x]  Min pointer it slides off the screen in imported profiles. [Bicycle 1.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/5666572/Bicycle.1.osf.zip)
- [x]  Opens as full-screen activity. Should open as "Search" screen.
- [x] Min.max speed is not imported.

# ToDo
Min/max speed routing parameters

- [x]  Place in Navigation settings > Route parameters > **Road speeds**

**UI:**
https://www.figma.com/file/XvmmAiCVHlXnp93F6ZJDqaQk/OsmAnd-iOS-Screen-Template?node-id=5863%3A0
![Road speeds](https://user-images.githubusercontent.com/9365308/92574552-e685e080-f28f-11ea-86f6-daa7f11f965d.png)
