### ISSUE TITLE
Add "What's new" dialog after update

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#897]
🎯 Goal: Show "What's new dialog" after the app version update

# Review:
**Dialog:**
- [x]  decrease margins size top/bottom
- [x]  Check text size
- [x]  Tapping on "Read more" opens inapp safari https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller?language=objc 

Cancelled (complicated):
-  Bullet list https://blog.vinhis.me/2017/04/16/bullet-list-on-ios-with-textkit.html

# ToDo
- [x]  Show What's new dialog after the app version update
- [x]  Add button to open the dialog in Help-> Other-> -> what's new
to add:
- [x]  New release notes should be added to the app strings so our weblate community could help us to translate it (Example from Android https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml#L67)
- [x]  Provide instruction on how to change string for "What's New" dialog. 

### Additional (bonus task :)
- [x]  Add VK.com to the list of OsmAnd social networks: Help-> Follow us-> VK (vk.com/osmandapp)

### Instruction for checking:
[https://github.com/osmandapp/OsmAnd-Issues/blob/master/Adding%20release%20information%20to%20IOS.md](https://github.com/osmandapp/OsmAnd-Issues/blob/master/Adding%20release%20information%20to%20IOS.md)

![What's New](https://user-images.githubusercontent.com/9365308/98814420-4e8ea980-242e-11eb-8697-15df8c47f42b.png)
