### ISSUE TITLE
Adding Compass to Radius Ruler tool

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#910]
# Review 
- [ ]  2.5D Mode: degrees are overlaps on the line, move it up little.
![Снимок экрана 2021-01-26 в 12 48 11](https://user-images.githubusercontent.com/9365308/105835668-c0f63b00-5fd4-11eb-950d-23d508072dfe.png)
- [ ]  Lagging when rotating, when map mode is to compass
https://user-images.githubusercontent.com/9365308/105835746-e125fa00-5fd4-11eb-943e-afdddb29509e.MP4

# Double check:
- [x] Foot / miles (ruler values?)
- [x] Min zoom to display
- [x] Compass should fit screen (use 1st circle is needed)
# ToDo 
- [x] Add Cardinal direction points
- [x] Add notchec
- [x] Show anlge indication above "North" point.
- [x] Add arrow for current direction view
- [x] Add option to disable/enable "Compass ruller".

**Task:**
Needed to add Compass to Radius Ruler tool like in OsmAnd for Android
**iOS:**
<img src="https://user-images.githubusercontent.com/44466116/96885682-7fad3700-148b-11eb-8aad-4725e4a4d7c9.png"  height="500"/>
**Android:**
<img src="https://user-images.githubusercontent.com/44466116/96885884-b2efc600-148b-11eb-8251-9cb535598776.png"  height="500"/>

**Comment by EugeneZmeuk** [comment]
Distance info doesn't update in Ruler Widget like in Android.

**Comment by vshcherb** [comment]
Could be fixed in future as separate issue.
