### ISSUE TITLE
Navigation: Options should open new Navigation settings

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#970]
# Review 2
- [x]  Options switch is updated only after screen moving.(see video)
https://user-images.githubusercontent.com/9365308/105834731-84760f80-5fd3-11eb-9fba-9b6edc9eb2f0.MP4
 
# Review 
- [x]  Options doesn't show changed status right after closing Options > Navigation options screen.
- [x] Navigation bar height increase
# ToDo 
Navigation – Options – Navigation settings, currently open old settings UI, should open new "Navigation settings" screen for needed profile.
<img src="https://user-images.githubusercontent.com/9365308/101646018-b214f280-3a3f-11eb-85ca-e9cfb1ad5411.jpeg"  height="500"/>
